### ISSUE TITLE
[Source Code Activities] Welcome to participate Apache ShenYu Source Code Analysis

### ISSUE THREAD

**Issue by yu199195** [apache/shenyu#1944]
Hi community

We are preparing a comprehensive source code analysis on Apache ShenYu, 
to help more people understand and use it.
This event mainly focuses on source code analysis output technology blog.
So I have listed the following tasks according to the module:

## News Guide

- [ ] Setup for Apache ShenYu @plutokaito 
- [ ] How to use Apache ShenYu Proxy http protocol @plutokaito 
- [ ] How to use Apache ShenYu Proxy dubbo protocol @plutokaito 
- [ ] How to use Apache ShenYu Proxy sofa protocol @plutokaito 
- [ ] How to use Apache ShenYu Proxy spring-cloud protocol @plutokaito 
- [ ] How to use Apache ShenYu Proxy grpc protocol @plutokaito 
- [ ] How to use Apache ShenYu Proxy tars protocol @plutokaito 
- [ ] How to use Apache ShenYu Proxy websocket protocol @plutokaito 

## Data Structure && Data Sync Impl Analysis
- [ ] Data Sync for Websocket @4zd
- [ ] Data Sync for Zookeeper  @4zd
- [ ] Data Sync for Nacos @4zd
- [ ] Data Sync for Etcd  @4zd
- [ ] Data Sync for Http @4zd

## Desgin Analysis
- [ ] Data Structure Desgin 
- [ ] Data Sync SPI Desgin 
- [ ] Plugin Desgin  @impactCn 
- [ ] Register Center Desgin

## Plugin Impl Analysis 
- [ ] Rewrite Plugin  @ttttangzhen 
- [ ] Redirect Plugin @ttttangzhen 
- [ ] Request Plugin @ttttangzhen 
- [ ] Context-Path Plugin  @JooKS-me 
- [ ] Param-Mapping Plugin @JooKS-me 
- [ ] ModifyResponse Plugin @ttttangzhen 
- [ ] Divide Plugin to Proxy http protocol @stephenshen1993 
- [ ] Dubbo Plugin to Proxy dubbo protocol @JooKS-me 
- [ ] SpringCloud Plugin to Proxy spring-cloud protocol  @stephenshen1993 
- [ ] Sofa Plugin to Proxy sofa protocol 
- [ ] Grpc Plugin  to Proxy grpc protocol 
- [ ] Hystriy Plugin to Limiting and Fusing 
- [ ] Sentinel Plugin to Limiting and Fusing @zhaiweij 
- [ ] Resilience4j Plugin to Limiting and Fusing @zhaiweij 
- [ ] RateLimiter Plugin to Cluster Limiting  @JooKS-me 
- [ ] Waf Plugin to Prevent Attacks  
- [ ] Sign Plugin to Verify Request 
- [ ] JWT Plugin to Support Authorization  @impactCn 
- [ ] OAuth2 Plugin to Support Authorization
- [ ] Monitor Plugin to Observe the Gateway Metrics
- [ ] Logging Plugin to Print Request And Response Parameters
- [ ] How to custom Plugin    @hqgordon

## App Client Access Impl Analysis
- [ ] Register Center for Zookeeper 
- [ ] Register Center for Nacos  @kangarooking 
- [ ] Register Center for Http 
- [ ] Register Center for ETCD 
- [ ] Register Center for Consul 
- [ ] SpringMVC client 
- [ ] SpringCloud client  @kangarooking 
- [ ] Dubbo client 
- [ ] GRPC client 
- [ ] Tars client 
- [ ] Sofa client 

## SPI Impl Analysis
- [ ] SPI for ParameterData  @leven-space
- [ ]  SPI for PredicateJudge @changanjennifer 
- [ ]  SPI for MatchStrategy@changanjennifer 
- [ ] How to custom SPI @leven-space

There should be many missing places, volunteers are welcome to compensate.

If you would like to participate, please provide pull to :

> https://github.com/apache/incubator-shenyu-website/pulls

**Comment by zhaiweij** [comment]
'Data Structure && Data Sync Impl Analysis' I am more familiar with this code before I can try to write

**Comment by 4zd** [comment]
All the items under the topic[Data Structure && Data Sync Impl Analysis] are wanted. Please assign them to me.
 

- Data Sync for Websocket
-  Data Sync for Zookeeper
-  Data Sync for Nacos
-  Data Sync for Etcd
-  Data Sync for Http

**Comment by 4zd** [comment]
@yu199195 I think I can try the items below instead, which are parts of the topic "App Client Access Impl Analysis".

Register Center for Zookeeper
 Register Center for Nacos
 Register Center for Http
 Register Center for ETCD
 Register Center for Consul

**Comment by plutokaito** [comment]
get News Guide， I think i need to know how to use.

**Comment by changanjennifer** [comment]
I wanna try  SPI Impl Analysis:

 SPI for PredicateJudge
 SPI for MatchStrategy

**Comment by leven-space** [comment]
Please assign to me ：
【
SPI for ParameterData
SPI for PredicateJudge
SPI for MatchStrategy
 How to custom SPI
】

**Comment by yu199195** [comment]
@leven-space  hi ， can you  Participation to  SPI for ParameterData and SPI for ParameterData，The others are already taken.

**Comment by hqgordon** [comment]
I want a small part of it：

 How to custom Plugin

**Comment by JooKS-me** [comment]
Hi, I'd like to take some in **Plugin Impl Analysis**: 
1. Context-Path Plugin
2. Param-Mapping Plugin
3. Dubbo Plugin to Proxy dubbo protocol
4. RateLimiter Plugin to Cluster Limiting

**Comment by yu199195** [comment]
@JooKS-me  ok

**Comment by yu199195** [comment]
@plutokaito ok

**Comment by ttttangzhen** [comment]
Hi, I'd like to take some in Plugin Impl Analysis

> Rewrite Plugin
> Redirect Plugin
> Request Plugin
> ModifyResponse Plugin

**Comment by stephenshen1993** [comment]
I'd like to take some in Plugin Impl Analysis:

- Rewrite Plugin
- Redirect Plugin
- Request Plugin
- SpringCloud Plugin to Proxy spring-cloud protocol

**Comment by impactCn** [comment]
I'd like to take some in Plugin Impl Analysis:

- Plugin Desgin
- JWT Plugin to Support Authorization

**Comment by zhaiweij** [comment]
I'd like to take some in Plugin Impl Analysis
 Sentinel Plugin to Limiting and Fusing
 Resilience4j Plugin to Limiting and Fusing

**Comment by zhaiweij** [comment]
hi

I'd like to take some in Plugin Impl Analysis

Sentinel Plugin to Limiting and Fusing

Resilience4j Plugin to Limiting and Fusing





On 08/19/2021 ***@***.***> wrote：

I'd like to take some in Plugin Impl Analysis:

Plugin Desgin
JWT Plugin to Support Authorization

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kangarooking** [comment]
I want try Register Center for Nacos

**Comment by kangarooking** [comment]
can I try Register Center for Nacos and Data Sync for Nacos?

**Comment by kangarooking** [comment]
and SpringCloud client

**Comment by yu199195** [comment]
@kangarooking  ok

**Comment by changanjennifer** [comment]
Hi, 
      
   I've wrote analysis for PredicateJudge SPI （ see attached), I'm not sure whether it is qualified.  Can you give any suggestion?


  Or is there any recommend  Code Analysis materials to refer?  After tha I will supply English version. 

   




At 2021-08-19 17:51:06, "xiaoyu" ***@***.***> wrote:

Assigned #1944 to @changanjennifer.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yu199195** [comment]
@changanjennifer    Of course, you can

**Comment by midnight2104** [comment]
hi, @plutokaito ,  are you still doing it?

**Comment by midnight2104** [comment]
hi, @zhaiweij  ,  are you still doing it?

**Comment by midnight2104** [comment]
hi, @stephenshen1993  ,  are you still doing it?

**Comment by midnight2104** [comment]
hi, @4zd  ,  are you still doing it?

**Comment by 4zd** [comment]
> hi, @4zd , are you still doing it?

yes, I'm currently working on the part [Data Sync for Http].

**Comment by 4zd** [comment]
@midnight2104 Are you working on the [Data Sync for Nacos] and [Data Sync for Etcd], or could I work on it?

**Comment by midnight2104** [comment]
no, you can do it.



At 2021-11-07 17:05:43, "Zhang Dong" ***@***.***> wrote:

@midnight2104 Are you working on the [Data Sync for Nacos] and [Data Sync for Etcd], or could I work on it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 4zd** [comment]
> no, you can do it. At 2021-11-07 17:05:43, "Zhang Dong" ***@***.***> wrote: @midnight2104 Are you working on the [Data Sync for Nacos] and [Data Sync for Etcd], or could I work on it? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Got it.

**Comment by plutokaito** [comment]
> hi, @plutokaito , are you still doing it?

yes, i still doing it. I will submit a pr Today.
