### ISSUE TITLE
[Question] Can the error log be printed when the service is abnormal

### ISSUE THREAD

**Issue by li-keguo** [apache/shenyu#2066]
### Question

I start shenyu-bootstrap, shenyu-admin, and shenyu-examples-sofa-service

it ok all,

shenyu-examples-sofa-service log:

```
... sofa client register success:...

```

but I'am run:

```
POST http://localhost:9195/sofa/findById

HTTP/1.1 200 OK
Content-Type: application/json
content-length: 93

{
  "code": -103,
  "message": "Service invocation exception, or no result is returned!",
  "data": null
}

```

shenyu-bootstrap log:

```
INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - sofa selector success match , selector name :/sofa

```

I don't know why it is abnormal

Maybe the error log should be added，

eg: Plugin is not found, sofa is not register, zk is not start...

**Comment by ousinka** [comment]
The plugin information has been printed in the log of the new version of shenyu-bootstrap.
eg: load plugin:[sofa] [org.apache.shenyu.plugin.sofa.SofaPlugin]

**Comment by li-keguo** [comment]
ok！ thanks～
