### ISSUE TITLE
How to pass global parameters

### ISSUE THREAD

**Issue by monedory** [apache/shenyu#2092]
### Question

I want to use RpcContext.getContext().setAttachment() to pass parameters to the dubbo service, but I cannot get the value correctly
I implement AbstractWebFilter, get public parameters through exchange.getRequest().getHeaders(), and set the parameters

**Comment by yu199195** [comment]
This may require the use of the dubbo plugin, but there is no such interface out at the moment, and we are considering the next release to provide~

**Comment by siegezhang** [comment]
is there any way override ApacheDubboPlugin doDubboInvoker method to add some params?

**Comment by dragon-zhang** [comment]
Hi, do you checked&nbsp;https://shenyu.apache.org/docs/next/plugin-center/common/general-context-plugin ?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-shenyu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 下午4:58
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [apache/incubator-shenyu] How to pass global parameters (#2092)





 
is there any way override ApacheDubboPlugin doDubboInvoker method to add some params?

**Comment by dragon-zhang** [comment]
@monedory @siegezhang If you think there are still problems, please create a new issue.
