### ISSUE TITLE
[BUG] <title>Database  table meta_ data  path_ Desc field cannot be empty exception

### ISSUE THREAD

**Issue by mobaiLv** [apache/shenyu#2212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

1.网关接入Dubbo接口使用注解@ShenyuDubboClient(path = "/open/insert")
2.shenyu-admin项目出现数据库表字段不能为空异常

### Environment

```markdown
ShenYu version(s):2.4.0
```

### Debug logs

java.sql.SQLIntegrityConstraintViolationException: Column 'path_desc' cannot be null
; Column 'path_desc' cannot be null; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'path_desc' cannot be null

### Anything else?

一般情况下注解中描述性字段都是可以为空的

**Comment by yu199195** [comment]
pls in english
