### ISSUE TITLE
[BUG] <title>Database table meta_ data path_ Desc field cannot be empty exception

### ISSUE THREAD

**Issue by mobaiLv** [apache/shenyu#2214]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Steps To Reproduce

1. The gateway accesses the Dubbo interface and uses the annotation @ShenyuDubboClient (path = "/ open / insert")

2. The database table field of Shenyu admin project cannot be empty

### Environment

```markdown
ShenYu version(s):2.4.0
```

### Debug logs

java.sql.SQLIntegrityConstraintViolationException: Column 'path_desc' cannot be null
; Column 'path_desc' cannot be null; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'path_desc' cannot be null

### Anything else?

In general, descriptive fields in annotations can be left blank

**Comment by yu199195** [comment]
you can config path_ Desc  in annotation.

**Comment by dragon-zhang** [comment]
@mobaiLv Please try the latest code, and if there are still questions, please submit a new issue.
