### ISSUE TITLE
is it necessary to annotate @ShenyuspringCloudClient in the Controller layer?

### ISSUE THREAD

**Issue by 65725738** [apache/shenyu#2232]
### Question

To use Shenyu, is it necessary to annotate @ShenyuspringCloudClient (path = "/save") in the Controller layer?

 For example,

    @PostMapping("/save")
    @ShenyuSpringCloudClient(path = "/save")
    public OrderDTO save(@RequestBody final OrderDTO orderDTO) {
        orderDTO.setName("hello world spring cloud save order");
        return orderDTO;
    }

If so, Shenyu's code will invade the normal business system. Coupled to the code of the business service. If you want to change the gateway. I need to delete all the code.

**Comment by 65725738** [comment]
Why not use conventions?

Run @requestMapping ("/order") @getMapping ("/path/{ID}/name") to obtain information about the service interface to be registered

**Comment by dragon-zhang** [comment]
@65725738 How about @ShenyuRequestMapping , @ShenyuGetMapping and etc?

**Comment by uncarbon97** [comment]
you can easily configurate it in (http://localhost:9095/#/config/metadata)[http://localhost:9095/#/config/metadata] like:
![image](https://user-images.githubusercontent.com/75737767/204700525-be87bcf8-e1c6-4751-98c4-12424ffa5d60.png)
