### ISSUE TITLE
[Volunteer] <add compress plugin>

### ISSUE THREAD

**Issue by impactCn** [apache/shenyu#2325]
### Volunteer help

Support a variety of compression algorithms, such as gzip.

**Comment by hgaol** [comment]
Hi @impactCn , what will compression plugin do? Do you mean it will compress the response data from `shenyu-bootstrap`? If yes, I think maybe adding below properties can help.
```properties
server.compression.enabled=true
server.compression.min-response-size=1024 # min number to compress
```
If no, pls help to provide more information, so I may can help :p

**Comment by impactCn** [comment]
> Hi @impactCn , what will compression plugin do? Do you mean it will compress the response data from `shenyu-bootstrap`? If yes, I think maybe adding below properties can help.
> 
> ```ini
> server.compression.enabled=true
> server.compression.min-response-size=1024 # min number to compress
> ```
> 
> If no, pls help to provide more information, so I may can help :p

My idea is to do it in the gateway, not in the business. This is not good for the same management.

**Comment by hgaol** [comment]
I mean adding these properties in `shenyu-bootstrap`(gateway) directly, so all responses will be compressed no matter the response from service has already been compressed or not. Please correct me if any misunderstanding.

**Comment by impactCn** [comment]
It can support both configuration and management. What do you think of this way?

**Comment by hutaishi** [comment]
Consider supporting lz4,  Extremely Fast Compression algorithm

**Comment by impactCn** [comment]
> Consider supporting lz4, Extremely Fast Compression algorithm

I will.
