### ISSUE TITLE
[Integrated-Test] Add combination integrated test

### ISSUE THREAD

**Issue by JooKS-me** [apache/shenyu#2365]
### Description

To test scenes of mixing plugins, we can add the integrated test to `shenyu-integrated-test-combination`. 

IMO, the following test should be covered. But, if you have more idea, please propose and do it~

### Combination of Response Plugins

- [ ] test combination of Modify Response and Cryptor Response plugin. @songyuequan 
...

### Combination of Request Plugins

- [x] test combination of Param mapping and Rewrite plugin. @lxl910128 
- [x] test combination of Param mapping and Redirect plugin. @lxl910128 
- [x] test combination of RateLimiter and Rewrite plugin. @lxl910128 
- [x] test combination of RateLimiter and Redirect plugin. @lxl910128 
- [x] test combination of Request and Redirect plugin. @lxl910128 
- [x] test combination of Request and Rewrite plugin. @lxl910128 
- [x] test combination of JWT and RateLimiter plugin. @lxl910128 
- [x] test combination of JWT and Redirect plugin. @lxl910128  
- [x] test combination of JWT and Rewrite plugin. @lxl910128 
...

### Combination of Request and Response Plugins

- [x] test combination of Cryptor Request and Cryptor Response plugin. @songyuequan 
...

### Combination of Rpc and Request Plugins

- [x] test combination of Dubbo and Param Mapping plugin. @JooKS-me 
- [x] test combination of Dubbo and Cryptor Request plugin. @JooKS-me 
- [x] test combination of Dubbo and Ratelimiter plugin. @JooKS-me 
...

### Combination of Rpc and Response Plugins

- [ ] test combination of Dubbo and Modify Response plugin. @songyuequan 
- [ ] test combination of Dubbo and Cryptor Response plugin. @songyuequan 
...

> PS: Request plugin means the plugin acting on request, and so on.

**Comment by lxl910128** [comment]
let me try `Combination of Request Plugins`

**Comment by JooKS-me** [comment]
> let me try `Combination of Request Plugins`

Thanks for help!

**Comment by AhahaGe** [comment]
can I try  test combination of Cryptor Request and Cryptor Response plugin ?

**Comment by songyuequan** [comment]
let me try Cryptor Request and Cryptor Response plugin.

**Comment by JooKS-me** [comment]
> let me try Cryptor Request and Cryptor Response plugin.

Welcome~

**Comment by songyuequan** [comment]
hi~ , I have finishedCryptor Request and Cryptor Response plugin . please assign some else to me.

**Comment by JooKS-me** [comment]
> hi~ , I have finishedCryptor Request and Cryptor Response plugin . please assign some else to me. @JooKS-me
Thanks, could you take  `Combination of Response Plugins` and `Combination of Rpc and Response Plugins` ?

In `Combination of Rpc and Response Plugins` you can not only test dubbo plugin ,but more rpc plugins, such as `grpc`, `sofa` and so on.

**Comment by songyuequan** [comment]
> > hi~ , I have finishedCryptor Request and Cryptor Response plugin . please assign some else to me. @JooKS-me
> 
> @songyuequan Thanks, could you take `Combination of Response Plugins` and `Combination of Rpc and Response Plugins` ?
> 
> In `Combination of Rpc and Response Plugins` you can not only test dubbo plugin ,but more rpc plugins, such as `grpc`, `sofa` and so on.

OK,   I  would  like   to  do  it.  thank you
