### ISSUE TITLE
[BUG] SpringCloud-Plugin do not have url encoding when forwarding the request.

### ISSUE THREAD

**Issue by pmgcat** [apache/shenyu#2367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For example, when requesting the URL "http://127.0.0.1:9195/test/getQuery?name=%E4%B9%83%E4%B8%87NINEONE%23+%E9%99%90%E9%87%8F%E5%8F%91%E5%94%AE2021+RR+Tour%E5%AE%9A%E5%88%B6%E5%B8%86%E5%B8%83%E5%8C%85&uid=12". Downstream services will not get the uid parameter, and the value of the name parameter is not complete.

### Expected Behavior

The request url query received by the downstream service is 'name=乃万NINEONE'.

### Environment

```markdown
ShenYu version(s): 2.4.0
```

**Comment by yu199195** [comment]
we alreay fix it at master，you can try

**Comment by dragon-zhang** [comment]
@pmgcat Please try the latest code, and if there are still questions, please submit a new issue.
