### ISSUE TITLE
[new : feature]  register shenyu instance to registry center

### ISSUE THREAD

**Issue by yu199195** [apache/shenyu#2416]
### Description

Hi community

To better support cluster mode, we need to register our own instances to the registry.

So I intend to design this aspect of the work.

Broadly speaking, there will be some tasks as follows.

- [x] Architecture Design @yu199195 
- [x] register instance to zookeeper @yu199195 
- [x] create apache/incubator-shenyu-nginx
- [ ] support nginx upstream to registry @impactCn 

If you have good suggestions or would like to participate then you can follow

**Comment by AhahaGe** [comment]
Can I have a try, but I know little about it, and If it's not emergency, can anyone guide me to finish it.

**Comment by impactCn** [comment]
I want to try the function ‘support nginx upstream to registry’.
