### ISSUE TITLE
[Question] Unify mocking framework dependencies

### ISSUE THREAD

**Issue by tuohai666** [apache/shenyu#2418]
### Question

For now, in the project there are two mocking framework PowerMock and Mockito. I think we keep one of them is enough. 
I'd like to discuss with you of which one to retain. Here are some superficial comparisons I just investigated.
Last release:
PowerMock: 02 Nov 2020  Mockito: 07 Oct 2021
Last commit:
PowerMock: 02 Nov 2020  Mockito: 18 Nov 2021

Any suggestions?

**Comment by plutokaito** [comment]
the last release of PowerMock is one year ago, So i suggest the Mockito.

**Comment by misselvexu** [comment]
Mockito, +1

**Comment by JooKS-me** [comment]
I think so too, `Mockito` is better.

**Comment by homihq** [comment]
+1 Mocktio.
