### ISSUE TITLE
[Volunteer] Add integrated test for Oauth2 plugin

### ISSUE THREAD

**Issue by JooKS-me** [apache/shenyu#2496]
### Volunteer help

- [ ] Add integrated test for Oauth2 plugin

**Comment by erdengk** [comment]
Hi，@JooKS-me 
Can I contribute to this question? Please guide me how to start
I've already seen it  [How to start the integrated tests]( https://github.com/apache/incubator-shenyu/tree/master/shenyu-integrated-test) and [Integration Test Analysis](https://shenyu.apache.org/blog/IntegrationTest-Analysis/) 

Is it possible to accomplish this task with this knowledge?

**Comment by JooKS-me** [comment]
Hi @erdengk , sorry, this task should be a part of GSoC #2890 , do you want to take #2909 ?

**Comment by erdengk** [comment]
OK
