### ISSUE TITLE
[Question] <Sentinel Cluster Mode>

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#2633]
### Question

Shenyu support Sentinel cluster mode and calculate cluster flow?

**Comment by pmgcat** [comment]
No support for this part is found now. Here we have developed a set of related support.

**Comment by moremind** [comment]
> No support for this part is found now. Here we have developed a set of related support.

what is the part of shenyu?

**Comment by justlau** [comment]
RateLimiter?

**Comment by moremind** [comment]
> RateLimiter?

I don't think it's ok
