### ISSUE TITLE
[Question] Different name between plugin rows and resource setting  in English

### ISSUE THREAD

**Issue by plutokaito** [apache/shenyu#2657]
### Question

I find that `SHENYU.BUTTON.SYSTEM.EDIT` shows "modify" at Resource Setting, but plugin rows shows "Editor".  So is it necessary to change them to the same English?

**Comment by yu199195** [comment]
I think it can be unified

**Comment by ousinka** [comment]
I tested version 2.5(master branch code), which has been unified~
