### ISSUE TITLE
[BUG] < when server give http state 302 shenyu response change to 200  >

### ISSUE THREAD

**Issue by dingjian2** [apache/shenyu#2669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 when server give http state 302 shenyu response change to 200  in spring mvc http divide

### Expected Behavior

 when server give http state 302 shenyu should return 302 state

### Steps To Reproduce

1 .create a controller  method  :   response.sendRedirect("https://www.baidu.com");    with @ShenyuSpringMvcClient  
2. request shenyu gateway by divide url 
3. response is  http state 200  with no http body   ， but response header  location value  is correct . should return 302 

### Environment

```markdown
ShenYu version(s):2.4.1
```

**Comment by dragon-zhang** [comment]
Please try again on the `master` branch. This problem has been fixed (I tried and will report `500`), @dingjian2

**Comment by likedong** [comment]
1. Refer to the master branch for modification  shenyu-plugin-httpclient
