### ISSUE TITLE
[BUG] <CROSSSLOT Keys in request don't hash to the same slot>

### ISSUE THREAD

**Issue by locatino** [apache/shenyu#2808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This exception is caused by the rate_limiter plugin. My redis mode is **cluster** and the algorithm is SlidingWindow.
I fixed it temporarily by modified the 'getKeys' method in SlidingWindowRateLimiterAlgorithm.java like this: 

    public List<String> getKeys(final String id) {
        String prefix = getKeyName() + ".{" + id;
        String tokenKey = prefix + "}.tokens";
        String timestampKey = UUIDUtils.getInstance().generateShortUuid() + ".{" + id + "}";
        return Arrays.asList(tokenKey, timestampKey);
    }

And I think ConcurrentRateLimiterAlgorithm.java has the same problem but I havent tested yet.

### Steps To Reproduce

1. Config the rate_limiter plugin redis mode cluster.
2. Enable it and send requests.

### Environment

```markdown
ShenYu version(s):
```

### Anything else?

![UcSTAR20220125135407](https://user-images.githubusercontent.com/3146681/150919908-7986107a-2cec-45ac-a757-33ba3916a26e.jpg)
![UcSTAR20220125135254](https://user-images.githubusercontent.com/3146681/150919916-ced64ac1-a236-4c78-a295-2f2957f400a3.jpg)

**Comment by JooKS-me** [comment]
@locatino Hi, can you elaborate on what this exception is?

**Comment by yu199195** [comment]
@locatino  it  means  have  different values？

>  String timestampKey = UUIDUtils.getInstance().generateShortUuid() + ".{" + id + "}";

**Comment by locatino** [comment]
> @locatino Hi, can you elaborate on what the exception is?

Here are my plugin config and the exception screenshot.

**Comment by locatino** [comment]
@yu199195 i think the '{id}' parts in 2 keys are used to ensure the values be hashed in the same slot because redis cluster have lots of slots distributed in diffrent processes or servers. If the keys arent hashed in the same slots the scripts would not be executed properly.

**Comment by yu199195** [comment]
@locatino  hi， the id it is definite， id ： rule.getId() + resolverKey

you can see `org.apache.shenyu.plugin.ratelimiter.RateLimiterPlugin`

```java

 String resolverKey = Optional.ofNullable(limiterHandle.getKeyResolverName())
                .flatMap(name -> Optional.of("-" + RateLimiterKeyResolverFactory.newInstance(name).resolve(exchange)))
                .orElse("");
        return redisRateLimiter.isAllowed(rule.getId() + resolverKey, limiterHandle)
                .flatMap(response -> {
                    if (!response.isAllowed()) {
                        exchange.getResponse().setStatusCode(HttpStatus.TOO_MANY_REQUESTS);
                        Object error = ShenyuResultWrap.error(exchange, ShenyuResultEnum.TOO_MANY_REQUESTS, null);
                        return WebFluxResultUtils.result(exchange, error);
                    }
                    return chain.execute(exchange);
                });
```

**Comment by locatino** [comment]
@yu199195 It's not the id's problem. The leakyBucket and tokenBucket are working properly because they extend the 'getKeys' from AbstractRateLimiterAlgorithm.java whose timestampKey has the same part '{id}' to make sure two keys are hashed into same redis cluster slot.
I think every key in the list of keys must be hashed into the same slot of redis, by adding some same part into the redis hash tag '{}'
    
    public List<String> getKeys(final String id) {
        String prefix = getKeyName() + ".{" + id;
        String tokenKey = prefix + "}.tokens";
        String timestampKey = prefix + "}.timestamp";
        return Arrays.asList(tokenKey, timestampKey);
    }

The second key 'timestampKey' in SlidingWindow cannot be hashed into the slot in redis cluster because redis cluster uses the content of '{}' to do hash.

**Comment by yu199195** [comment]
@locatino  no, you can see sliding_window_request_rate_limiter.lua, 

>    redis.call('zadd', tokens_key, now, timestamp_key)

Is there a problem with it, and if so, can you fix it?

**Comment by locatino** [comment]
@yu199195 The script is correct and the exception shows that the code has a problem.

> Hash tags are documented in the Redis Cluster specification, but the gist is that if there is a substring between {} brackets in a key, only what is inside the string is hashed, so for example this{foo}key and another{foo}key are guaranteed to be in the same hash slot, and can be used together in a command with multiple keys as arguments.
--https://redis.io/topics/cluster-tutorial

I think I already fixed it and I will test it for some time. Then PR.

**Comment by yu199195** [comment]
Looking forward to your contribution

**Comment by yu199195** [comment]
@locatino hi，Looking forward to your pull request~
