### ISSUE TITLE
[Question] Problems writing cookies to browser

### ISSUE THREAD

**Issue by zhangxin766884** [apache/shenyu#2849]
### Question

My calling link is: H5-->shenyu gateway-->service A, service A is dedicated to user login and permissions. With this architecture, after successful login, the gateway cannot automatically write browser cookies. PS: The call is to use the dubbo framework

**Comment by yu199195** [comment]
if used dubbo ， maybe you can add custom plugin，then write result to cookie

**Comment by lzqdename** [comment]
maybe u can use customed filter to add token into header ,
