### ISSUE TITLE
[Question] Does the logging plug-in affect performance?

### ISSUE THREAD

**Issue by shihaoyan** [apache/shenyu#2852]
### Question

Does the logging plug-in affect performance? 
Is log printing performed asynchronously?

**Comment by yu199195** [comment]
hi，
1.  Logging plugin my be remove by next version.
2. The shenyu agent logging plugin will provide this functionality.
3. Of course, outputting logs will affect performance, so you can choose to match the traffic to output.

**Comment by shihaoyan** [comment]
Thank you. I would like to ask you another question. When is the execution time of this log printing? Does the response end and print the request parameters with the response parameters?
Are logs printed asynchronously?
I introduced the logging plug-in in the project, but the performance impact was not that great, or even the same as not printing the log.
