### ISSUE TITLE
Submit a pull request Partial check does not pass

### ISSUE THREAD

**Issue by afumu** [apache/shenyu#2881]
### Question

![b1f5238bee493bc1d008c5fdcef42d1](https://user-images.githubusercontent.com/50908453/154007040-15bc2f13-f614-43d7-95a0-d76bc488ecd0.png)
![36c57749993ec44636667fdf57ae61d](https://user-images.githubusercontent.com/50908453/154007052-605e7d4e-5ab7-42db-921d-3c2329920f29.png)

**Comment by hgaol** [comment]
Can't reproduce in my local machine, can you provide more details? Like the link to this log.

**Comment by yu199195** [comment]
@hgaol 
hi should refactor this test case , my be in multi-threaded environment

**Comment by hgaol** [comment]
I think we can make the time window larger to make sure it still in time window for shortcut in line 153.
`org.apache.shenyu.plugin.sentinel.SentinelPluginTest#testSentinelPluginDegradeException`
```diff
   public void testSentinelPluginDegradeException() {
...
+        sentinelHandle.setDegradeRuleTimeWindow(100);
-        sentinelHandle.setDegradeRuleTimeWindow(10);
...
        for (int i = 0; i < 5; i++) {
            StepVerifier.create(sentinelPlugin.doExecute(exchange, chain, selectorData, data))
                    .expectError(RuntimeException.class).verify();
        }
        // make sure it still in time window when running this test
        StepVerifier.create(sentinelPlugin.doExecute(exchange, chain, selectorData, data))
                .expectSubscription().verifyComplete();
       ....
}
```
If it's acceptable, I can submit PR for this issue.
