### ISSUE TITLE
The divide plugin successfully registered the https request, but the gateway forwarded abnormally[Question] <title>

### ISSUE THREAD

**Issue by yu65044** [apache/shenyu#2932]
### Question

My local https request can be successfully registered to divide, but the gateway forwarding keeps prompting:Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem

The version running locally is 2.4.2-tar, Windows 10 environment:

Both admin and bootstrap use the default configuration, the local client uses the p12 certificate generated by the local jdk8, and the service configuration is:

shenyu:
  register:
    registerType: http #zookeeper #etcd #nacos #consul
    serverLists: http://localhost:9095 #localhost:2181 #http://localhost:2379 #localhost:8848
    props:
      username: admin
      password: 123456
  client:
      http:
        props:
          contextPath: /message-center
          protocol: https://
          appName: message-center
          port: 8443

**Comment by yu65044** [comment]
tick tick tick...

**Comment by yu199195** [comment]
hi， you can see this config ： https://github.com/apache/incubator-shenyu/tree/master/shenyu-integrated-test/shenyu-integrated-test-https/src/main/resources

**Comment by yu199195** [comment]
hi， you can see this config ： https://github.com/apache/incubator-shenyu/tree/master/shenyu-integrated-test/shenyu-integrated-test-https/src/main/resources

**Comment by yu65044** [comment]
i got it,I refer to shenyu-examples-https, without adding keystore.p12 and configuration information in bootstrap...
