### ISSUE TITLE
[Question] admin-register-sync

### ISSUE THREAD

**Issue by chariles** [apache/shenyu#2997]
### Question

I configured the following，
shenyu:
  register:
    registerType: nacos  #zookeeper #etcd #nacos #consul
    serverLists: 172.16.3.139:8848  #localhost:2181 #http://localhost:2379 #localhost:8848
    props:
      nacosNameSpace: ShenyuRegisterCenter

The client configuration is the same as above，When the client down, the service list of admin is not updated， still route to the original IP address,Why this happened?

**Comment by yu199195** [comment]
whats the version？

> When the client down

its the real server?

**Comment by chariles** [comment]
version is 2.4.2

**Comment by yu199195** [comment]
> When the client down

its your real server?  in shenyu admin not update?

**Comment by chariles** [comment]
> its your real server? in shenyu admin not update?

yes，i'm sure.
