### ISSUE TITLE
[BUG] Page is missing action buttons

### ISSUE THREAD

**Issue by zzq1314zll** [apache/shenyu#3009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="583" alt="image" src="https://user-images.githubusercontent.com/33930711/157388237-45eeb0e9-d433-4ff5-b2b1-59223dcd97b5.png">

### Expected Behavior

<img width="699" alt="image" src="https://user-images.githubusercontent.com/33930711/157388299-1dacf5a0-8ce8-412d-9484-a5c203048269.png">

### Environment

```markdown
ShenYu version(s): 2.4.3-SNAPSHOT
```

**Comment by yu199195** [comment]
can you fix it?

**Comment by zzq1314zll** [comment]
em.... i can try

**Comment by dragon-zhang** [comment]
Does this fixed ? @zzq1314zll
