### ISSUE TITLE
[Question] why version is fixed？

### ISSUE THREAD

**Issue by ZZQ001010** [apache/shenyu#3010]
### Question

`org.apache.shenyu.plugin.sign.service.DefaultSignService#buildParamsMap`
<img width="898" alt="image" src="https://user-images.githubusercontent.com/33930711/157389953-38cd6efc-7429-481f-872b-8dd29e01517a.png">
Can shenyu be routed according to version?

**Comment by AhahaGe** [comment]
Currently not supported, as version is not passed to backend, and it's written to death。
And you can refer this [sign-plugin](https://shenyu.apache.org/zh/docs/plugin-center/authority-and-certification/sign-plugin) for more info.
