### ISSUE TITLE
[Task] <The JwtRuleHandle should be coustomerd>

### ISSUE THREAD

**Issue by lishuo5263** [apache/shenyu#3011]
### Description

1.JwtRuleHandle should be more slight
2.JwtRuleHandle can be coustomerd ,and invoke handle business

### Task List

1.Define AbstarctHandleClass and commond method.
2.Add @SPI to Extend AbstarctHandleClass and Impl this class .
3.Add juint test case .

**Comment by tian-pengfei** [comment]
can I try ？please.
