### ISSUE TITLE
[Task] shenyu-client-load

### ISSUE THREAD

**Issue by chariles** [apache/shenyu#3024]
### Description

can client's bean load on demand?
for emample,use bean on ConditionalOnProperty,which can  switch by config.

 @ConditionalOnProperty(prefix = "example.service", value = "enabled", havingValue = "true")
  ServiceA buildServiceA(){
        return new ServiceA();
    }

**Comment by KevinClair** [comment]
Don't add dependency if you don't want to upload api by `shenyu client`.

**Comment by chariles** [comment]
> Don't add dependency if you don't want to upload api by `shenyu client`.

But this is not flexible enough, and the code needs to be modified. If the configuration is passed on k8s, there is no need to modify the code, which is necessary

**Comment by yu199195** [comment]
which  shenyu client？

**Comment by chariles** [comment]
> which shenyu client？

springmvc client

**Comment by midnight2104** [comment]
If you do not use the plugin, you can sub ahadmin to close.
