### ISSUE TITLE
[BUG] <shenyu-admin>  can`t get Selector and Rule by shenyu/plugin/selectorAndRules

### ISSUE THREAD

**Issue by ZhangJiaLei123** [apache/shenyu#3032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<shenyu-admin UI>  can`t get Selector and Rule if i set it by 'curl --location --request POST 'http://localhost:9195/shenyu/plugin/selectorAndRules' '
![微信截图_20220311180544](https://user-images.githubusercontent.com/40969169/157846263-881d1bb2-c08d-44e1-b7ca-91c19b43a18c.png)

### Expected Behavior

![微信截图_20220311180659](https://user-images.githubusercontent.com/40969169/157846482-5b157699-497e-4d5d-a069-caf0cd7c6bfd.png)

### Steps To Reproduce

 'curl --location --request POST 'http://localhost:9195/shenyu/plugin/selectorAndRules' '

### Environment

```markdown
ShenYu version(s):master and 2.4.2
```

**Comment by JooKS-me** [comment]
> `http://localhost:9195/shenyu/plugin/selectorAndRules` 

Hi, I think this is a feature. We can use this endpoint in local mode. But it can't pass configuration to the control plane, configuration delivery is unidirectional.

**Comment by dragon-zhang** [comment]
Is this supported ?
