### ISSUE TITLE
[BUG] The host value in the original request header is lost after shenyu forwards it

### ISSUE THREAD

**Issue by wls981** [apache/shenyu#3052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/15735480/158784121-d0a8285c-f569-4edd-b4de-a6f176bcb49a.png)
![image](https://user-images.githubusercontent.com/15735480/158783560-caa763ee-7475-4348-bf2b-cdc3ebd67c64.png)
![image](https://user-images.githubusercontent.com/15735480/158782396-95c5f6a8-ba84-48c9-854f-f7185280bb5b.png)

**As shown in the figure above, the above figure is the list of headers in the web request output in the back-end application after forwarding by shenyu. The value of the host header is not the value of the host header in the original request.**

**My deployment environment is as follows:**
![image](https://user-images.githubusercontent.com/15735480/158784926-64e9ecf4-faef-4c3e-ba3f-bb1982dad3b9.png)

### Expected Behavior

Expect to get the host header value in the original request.

### Steps To Reproduce

The deployment environment as described above is reproducible.

### Environment

```markdown
ShenYu version(s):2.4.1
```

**Comment by yu199195** [comment]
you can used shenyu least version

**Comment by wls981** [comment]
The latest version still has the problem.

**Comment by yu199195** [comment]
shenyu will remove original host

>  headers.remove(HttpHeaders.HOST);

**Comment by wls981** [comment]
![image](https://user-images.githubusercontent.com/15735480/163661946-f202c0a5-7f26-471a-9364-f8e4fe2d6101.png)

Yes, I saw that the host header was removed from the webclient plugin. Currently, I modified the plugin and commented out this line, but I don't understand the reason for this.

**Comment by hutaishi** [comment]
> ![image](https://user-images.githubusercontent.com/15735480/163661946-f202c0a5-7f26-471a-9364-f8e4fe2d6101.png)
> 
> Yes, I saw that the host header was removed from the webclient plugin. Currently, I modified the plugin and commented out this line, but I don't understand the reason for this.

The latest version has been modified.  removed:
```java
headers.remove(HttpHeaders.HOST);
```
