### ISSUE TITLE
[Volunteer] Add skywaliking plugin for support shenyu gateway

### ISSUE THREAD

**Issue by yu199195** [apache/shenyu#3076]
### Volunteer help

Hi Community

We need to add skywaliking plugin [1]  for support shenyu gateway

The identified interception points are ：

  * org.apache.shenyu.plugin.global.GlobalPlugin.execute(), create root span 

  * org.apache.shenyu.plugin.response.ResponsePlugin.execute() finish end span 

links:

1. https://github.com/apache/skywalking-java/tree/main/apm-sniffer/apm-sdk-plugin

**Comment by hutaishi** [comment]
I want do this. think

**Comment by hutaishi** [comment]
Thank you very much. I will do this well

**Comment by hutaishi** [comment]
skywalking pr: https://github.com/apache/skywalking-java/pull/147
we should support http and other rpc.
Next need to support more rpc

**Comment by hutaishi** [comment]
These have all been supported: `HTTP`,`Spring Cloud`,`gRPC`,`Dubbo`,`SOFARPC`,`Motan`,`Tars` .
I will write a post about integrating skywalking to achieve observability

**Comment by hutaishi** [comment]
The blog has been written. welcome to use.
---
[**chinese blog**](https://skywalking.apache.org/zh/2022-05-08-apache-shenyuincubating-integrated-skywalking-practice-observability/)
---
[**english blog**](https://skywalking.apache.org/blog/2022-05-08-apache-shenyuincubating-integrated-skywalking-practice-observability/)
