### ISSUE TITLE
[BUG] <Sign plugin has some front bug>

### ISSUE THREAD

**Issue by AhahaGe** [apache/shenyu#3090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

1. use the latest code of master branch and start bootstrap and admin
2. enable sign plugin and add data in Authentication
3. when I click EditResourcesDetail in PathOperation Column, there is no response.
<img width="1429" alt="WeChatWorkScreenshot_261adc0a-e071-47bb-ba27-e65ebc22073f" src="https://user-images.githubusercontent.com/6198217/159504694-496aadee-48f5-4aae-ba7d-76a0baa8561e.png">
4. When I click Edit in Operation column, I can't see operation button, and can't edit the path content.
<img width="1267" alt="WeChatWorkScreenshot_8e5f39ee-fa50-4298-b3bc-ccc058879bc9" src="https://user-images.githubusercontent.com/6198217/159505167-b712343d-cccb-46bc-9cd6-69153f9698b1.png">
5. When I click Edit in Operation column, I can't see operation button, but When I click add button, I can see operation button, but I can't input content in the second row.
<img width="1289" alt="WeChatWorkScreenshot_6f216f1a-61f0-46df-b852-23be6d675a84" src="https://user-images.githubusercontent.com/6198217/159505762-42f39bc2-e36d-41d2-a196-102d61c902bc.png">

### Environment

```markdown
ShenYu version(s):2.4.3
```

**Comment by yu199195** [comment]
@AhahaGe  can you fix it？

**Comment by AhahaGe** [comment]
I will have a try, but I know little about front code.

**Comment by wklong** [comment]
@AhahaGe  @yu199195   The third step is a back-end bug
