### ISSUE TITLE
[BUG] The selector action page should be centered.

### ISSUE THREAD

**Issue by midnight2104** [apache/shenyu#3125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Start the shenyu-admin management system. When modifying the selector information of a plugin, the selector action page should be centered, not at the bottom.

http://localhost:9095/#/plug/5/divide

### Expected Behavior

 the selector action page should be centered, not at the bottom.

### Steps To Reproduce

1. Start the shenyu-admin
2. login `http://localhost:9095`
3. PluginList -> Proxy -> Divide -> modify Selector 

### Environment

```markdown
ShenYu version(s): current
`win10` , `jdk8`
```

### Debug logs

![2022-03-25_183749](https://user-images.githubusercontent.com/13334620/160107887-daebfa5b-8cb6-4bf6-9824-bc64ccf80933.png)

### Anything else?

Maybe a front-end engineer is needed to fix the problem

**Comment by li-keguo** [comment]
Can't reproduce

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/33576070/160163142-64366ee3-d006-49e4-87d4-a0fa6192886e.png">

**Comment by midnight2104** [comment]
oh...I just tried it and the problem still exists. my env is `win10` , `jdk8`, `chrome  99.0.4844.84`

**Comment by li-keguo** [comment]
I reproduced the problem with Window10, maybe it's the browser itself

Zoom less than 110

<img width="376" alt="image" src="https://user-images.githubusercontent.com/33576070/160267503-4e559585-72c9-4ec2-9262-5bd1dbf7d4dc.png">

mac os is no problem

**Comment by midnight2104** [comment]
Yes, a scaling ratio less than 100% is normal, greater than or equal to this problem will occur, It requires front-end adaptation.
