### ISSUE TITLE
[Volunteer] <add alert plugin>

### ISSUE THREAD

**Issue by impactCn** [apache/shenyu#3133]
### Volunteer help

Support health check for downstream services and issue warnings when services are unhealthy.

Warning docking dingding, SMS, email, etc.

Also customize the alarm format.

**Comment by seedscoder** [comment]
Can I add other alert plugin (e.g. feishu)?

**Comment by impactCn** [comment]
> Can I add other alert plugin (e.g. feishu)?

Good idea, I think you can.
