### ISSUE TITLE
[question]ShenYu Agent  tracing support skywalking

### ISSUE THREAD

**Issue by chariles** [apache/shenyu#3143]
### Description

does ShenYu Agent  tracing support skywalking?

**Comment by hutaishi** [comment]
Thank you for your attention. At present, I am developing this plug-in and will support it soon. Please pay attention.

issue:https://github.com/apache/incubator-shenyu/issues/3076

**Comment by hutaishi** [comment]
skywalking pr: https://github.com/apache/skywalking-java/pull/147
we should support http and other rpc.

**Comment by yu199195** [comment]
good job，you can go on 
>skywalking pr: https://github.com/apache/skywalking-java/pull/147
we should support http and other rpc.

**Comment by hutaishi** [comment]
These have all been supported: HTTP,Spring Cloud,gRPC,Dubbo,SOFARPC,Motan,Tars .
I will write a post about integrating skywalking to achieve observability

**Comment by hutaishi** [comment]
The blog has been written. welcome to use.
---
[**chinese blog**](https://skywalking.apache.org/zh/2022-05-08-apache-shenyuincubating-integrated-skywalking-practice-observability/)
---
[**english blog**](https://skywalking.apache.org/blog/2022-05-08-apache-shenyuincubating-integrated-skywalking-practice-observability/)
