### ISSUE TITLE
[BUG] Docker-Compose db(mysql) image not support arm64(Raspberry Pi 4 Model B) architecture

### ISSUE THREAD

**Issue by myesn** [apache/shenyu#3163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Docker-Compose file: 

[master/shenyu-dist/shenyu-docker-compose-dist/src/main/resources/stand-alone-mysql/docker-compose.yaml](https://github.com/apache/incubator-shenyu/blob/master/shenyu-dist/shenyu-docker-compose-dist/src/main/resources/stand-alone-mysql/docker-compose.yaml)

Operation system version: 

```bash
ubuntu@ubuntu:~/apache-shenyu/shenyu-master$ uname -a
Linux ubuntu 5.4.0-1055-raspi #62-Ubuntu SMP PREEMPT Wed Mar 2 14:43:34 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

Running on Raspberry Pi 4 Model B(arm64): 

```bash
ubuntu@ubuntu:~/apache-shenyu/shenyu-master$ docker-compose up -d
Pulling db (docker.io/mysql:5.7)...
5.7: Pulling from library/mysql
5.7: Pulling from library/mysql
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
```

### Expected Behavior

Make it work, thanks.

### Steps To Reproduce

An error occurs after executing the following command:

```bash
curl https://raw.githubusercontent.com/apache/incubator-shenyu/master/shenyu-dist/shenyu-docker-compose-dist/src/main/resources/install.sh | bash -s master mysql
```

### Environment

```markdown
ShenYu version(s): 2.4.2
```

### Anything else?

Using the `biarms/mysql:5.7.30-linux-arm64v8` image in our project can run successfully.

**Comment by yu199195** [comment]
Do you have any good solutions?

**Comment by myesn** [comment]
I think we need to first split the docker-compose.yml file according to different CPU architectures, and then modify the install.sh script to execute different docker-compose.yml file for different CPU architectures, with pseudo code like:
```javascript
kind = ""

switch os.architecture:
  case x64:
    kind = "x64"; break;    
  case arm64:
    kind = "arm64"; break;
  default:
      throw error("not supported");

docker-compose -f docker-compose-${kind}.yml up  -d
```

Here are some references:
- [Changing the image in Docker Compose based on the host OS](https://stackoverflow.com/questions/53543445/changing-the-image-in-docker-compose-based-on-the-host-os)
- [How can I get distribution name and version number in a simple shell script?](https://unix.stackexchange.com/questions/6345/how-can-i-get-distribution-name-and-version-number-in-a-simple-shell-script)

**Comment by JooKS-me** [comment]
> Using the biarms/mysql:5.7.30-linux-arm64v8 image in our project can run successfully.

Hi, I think we can change `mysql` to `mariadb` which support both amd64 and arm64 arch.

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/62384022/161217623-e000f226-793b-411b-b7b3-933c5e6e8c0e.png">

**Comment by myesn** [comment]
> Hi, I think we can change mysql to mariadb which support both amd64 and arm64 arch.

It should work, I haven't used mariadb, all I know is that it's a mysql based distribution.

But now there is a new problem, the `shenyu-admin` and `shenyu-bootstrap` are not working properly(on arm64 architecture), I created a new issue #3166 to illustrate this new problem.
