### ISSUE TITLE
[Monta example configuration a bit complex] <Suggest add configuration in starter>

### ISSUE THREAD

**Issue by AhahaGe** [apache/shenyu#3176]
### Volunteer help

1. Check shenyu-exampels-motan,  we used shenyu-spring-boot-starter-client-motan
2. Configure motan example
<img width="759" alt="image" src="https://user-images.githubusercontent.com/6198217/161361926-c23c8a9f-b1db-4a02-91f7-9cc9545a9d92.png">

3. add properties bean 
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/6198217/161361939-a8c24d25-869e-434c-b273-247496d95635.png">

4. add config bean
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/6198217/161361996-c008ff93-03f6-4ce7-a41f-73bd5c8ceb6c.png">

I suggest it's a bit complex, can we improve it?

**Comment by dragon-zhang** [comment]
@lahmXu @ChineseTony can you provide these features ?

**Comment by lahmXu** [comment]
OK，please assign to me, thanks!!
