### ISSUE TITLE
[Volunteer] <How about add some handle for thread pool error>

### ISSUE THREAD

**Issue by AhahaGe** [apache/shenyu#3185]
### Volunteer help

For example:
1. add a new exception type
2. record metric 
3. dump jps to see jvm snapshot
4. send to alter module
5. publish event to listener for customize handle
6. ...

**Comment by UniverseInHeart** [comment]
I'm not sure how to do that.

**Comment by dragon-zhang** [comment]
> I'm not sure how to do that.

When https://github.com/apache/incubator-shenyu/issues/3026 is completed, we can easily implement it in `ShenyuThreadPoolExecutor`.

**Comment by UniverseInHeart** [comment]
> > I'm not sure how to do that.
> 
> When #3026 is completed, we can easily implement it in `ShenyuThreadPoolExecutor`. Also, maybe we can use `GlobalErrorHandler`.

copy that

**Comment by AhahaGe** [comment]
Yes, we can implement it in ShenyuThreadPoolExecutor's RejectPolicy or AOP

**Comment by dragon-zhang** [comment]
@UniverseInHeart can you provide this feature ?
