### ISSUE TITLE
which condition may delete the divide plugin handle(the upstream config) in the selector table

### ISSUE THREAD

**Issue by justlemontree** [apache/shenyu#3223]
### Question

which condition may delete the divide plugin handle in the selector table
the upstreamCheck enabled is false;

**Comment by yu199195** [comment]
What method of  access are you using?  http register？ or  other register center？ or  youself？

**Comment by justlemontree** [comment]
I have configed like that,&nbsp; I find some condition may delete the upstrem from the front page, such as copy the divide selector and edit it, so the divide handle fileld is empty, so the upsteam in the db is removed.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月12日(星期二) 下午3:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/incubator-shenyu] which condition may delete the divide plugin handle(the upstream config) in the selector table (Issue #3223)





 
if you can config this in shenyu-admin， it not be check upstream：
 shenyu:   register:     props:       checked: false

**Comment by yu199195** [comment]
so，


copy the divide selector and edit it, so the divide handle fileld is empty？  maybe it a bug in shenyu-dashborad

if you not edit，it be removed？

**Comment by justlemontree** [comment]
if&nbsp; not edit，it will not be removed.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月12日(星期二) 下午3:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/incubator-shenyu] which condition may delete the divide plugin handle(the upstream config) in the selector table (Issue #3223)





 
so，
 
copy the divide selector and edit it, so the divide handle fileld is empty？  maybe it a bug in shenyu-dashborad
 
if you not edit，it be removed？

**Comment by AhahaGe** [comment]
For latest code, use shenyu-examples-http, handle field is null for divide plugin
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/6198217/162918715-0075cebe-350b-4e6c-9ed1-9e042775b2a9.png">
