### ISSUE TITLE
[Question] <Is it possible to add mock plugins to the gateway project>

### ISSUE THREAD

**Issue by hutaishi** [apache/shenyu#3232]
### Question

In the front and back-end development scenario, sometimes the back-end interface is not yet developed, but the front-end wants to call the mock data test.
 If there is a mock plugin may be able to improve the efficiency of collaboration

**Comment by erdengk** [comment]
I think this is a good idea. A similar tool is [apifox](https://www.apifox.cn/), which can implement mock data for the front end to call directly. Maybe we can get some inspiration from its design.
