### ISSUE TITLE
[BUG] <There are more than 8 configuration items in the generalcontext plugin and an error is reported.>

### ISSUE THREAD

**Issue by lianjunwei** [apache/shenyu#3244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/13819823/163129954-7a2596f1-36fc-46a8-adfc-e6b0fe9f506d.png)

### Expected Behavior

Solution:
1.The size of the "handle" field in the "rule" table of the database is 1024. Should the capacity be expanded.
2.Compress the JSON string volume by shortening the field name (consider how to upgrade smoothly)

### Environment

```markdown
ShenYu version(s): 2.4.2 and master.
```

**Comment by yu199195** [comment]
it can be fixed?

**Comment by lianjunwei** [comment]
> I can fix it.
Consider optimizing from the following two points.
1. Increase the length of the database field.
2. Consider compress the JSON string volume by shortening the field name.
