### ISSUE TITLE
[BUG] there are remaining references to alibaba dubbo jar that should probably be changed to apache dubbo jar

### ISSUE THREAD

**Issue by pjfanning** [apache/shenyu#3263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

* https://github.com/apache/incubator-shenyu/blob/master/pom.xml#L96
* https://github.com/apache/incubator-shenyu/blob/master/pom.xml#L263-277

Also appears in other pom files

* https://github.com/advisories/GHSA-gw4j-4229-q4px - one CVE in alibaba dubbo
* possibly other issues that might be fixed in apache version but not alibaba version

### Expected Behavior

Use apache dubbo everywhere

### Environment

```markdown
ShenYu version(s): dev
```

**Comment by yu199195** [comment]
hi， we should support alibab duoob and apache dubbo。 

BTW ，apache dubbo fully compatible with alibaba dubbo?

**Comment by hutaishi** [comment]
> hi， we should support alibab duoob and apache dubbo。
> 
> BTW ，apache dubbo fully compatible with alibaba dubbo?

I have tested that using apache dubbo client to access alibaba dubbo service is normal, this is protocol compatible, but I have not fully tested.
