### ISSUE TITLE
[Task] Polish the document 

### ISSUE THREAD

**Issue by erdengk** [apache/shenyu#3271]
## Description

Please review the Contributor Guidelines before starting to contribute.
[contributor-guide](https://shenyu.apache.org/zh/community/contributor-guide/)

This part of the task is to help newbies familiarize themselves with the process of submitting PR, please give this opportunity to other newbies if you have participated in similar tasks：）

The repository for this part of the document is at [incubator-shenyu-website](https://github.com/apache/incubator-shenyu-website ).
You can find the address of the document by clicking the Edit this document link at the bottom of the page.

If you are interested in these tasks, please leave a comment about the tasks you want to do, and then you can start contributing.

###  esay task

**These two tasks require you to be familiar with Chinese.**

- [x] 将说明中的 "还容许用户使用” ，改为“允许用户使用” @ST-SHASK

[redirect-plugin](https://shenyu.apache.org/zh/docs/next/plugin-center/http-process/redirect-plugin)
[request-plugin](https://shenyu.apache.org/zh/docs/next/plugin-center/http-process/request-plugin)
[rewrite-plugin](https://shenyu.apache.org/zh/docs/next/plugin-center/http-process/rewrite-plugin)

- [x] In Chinese documents, it is better to use Chinese descriptions.

Translate the English expressions of the description column and help column in this document into Chinese, please make sure that your translation expresses the original English meaning as much as possible.
[metrics-plugin](https://shenyu.apache.org/zh/docs/next/plugin-center/observability/metrics-plugin)
<img width="50%" alt="image" src="https://user-images.githubusercontent.com/37730787/163812405-c22ca678-1d74-4344-a948-983c34a73353.png">

<img width="50%" alt="image" src="https://user-images.githubusercontent.com/37730787/163812982-46589586-2e92-4bda-9c60-e136a7169ed0.png">

### medium task 

If you are already familiar with the process of submitting pr, it is recommended to

- [ ] write unit tests for shenyu

You can check the code coverage of shenyu at this [site](https://app.codecov.io/gh/apache/incubator-shenyu).

You can also try to solve this [issue](https://github.com/apache/incubator-shenyu/issues/2404
).

Some pr you can refer to:

- [in test](https://github.com/apache/incubator-shenyu/pulls?page=2&q=is%3Apr+is%3Aclosed+test+label%3A%22in%3A+test%22)
- [add pathUtils test](https://github.com/apache/incubator-shenyu/pull/2734)
- [Add unit test for LocalMetadataController](https://github.com/apache/incubator-shenyu/pull/2167)
- [Add unit test for ShenyuClientRegisterTarsServiceImpl ](https://github.com/apache/incubator-shenyu/pull/2461)

**Comment by ST-SHASK** [comment]
let me try esay task 1

**Comment by damonxue** [comment]
ok, let me try esay task 2

**Comment by damonxue** [comment]
The easy-task2 was already merged to main.

**Comment by acmday** [comment]
let me try medium task
