### ISSUE TITLE
[Task] write unit tests for ShenYu

### ISSUE THREAD

**Issue by erdengk** [apache/shenyu#3274]
### medium task 

If you are already familiar with the process of submitting pr, it is recommended that you write unit tests for ShenYu

You can check the code coverage of ShenYu at this [site](https://app.codecov.io/gh/apache/incubator-shenyu).

You can also try to solve this [issue](https://github.com/apache/incubator-shenyu/issues/2404
).

Some pr you can refer to:

- [in test](https://github.com/apache/incubator-shenyu/pulls?page=2&q=is%3Apr+is%3Aclosed+test+label%3A%22in%3A+test%22)
- [add pathUtils test](https://github.com/apache/incubator-shenyu/pull/2734)
- [Add unit test for LocalMetadataController](https://github.com/apache/incubator-shenyu/pull/2167)
- [Add unit test for ShenyuClientRegisterTarsServiceImpl ](https://github.com/apache/incubator-shenyu/pull/2461)

**Comment by Mayank-KS** [comment]
Is there some material you recommend for writing the unit tests? I want to contribute but I don't know where to get started.

**Comment by erdengk** [comment]
@Mayank-KS 

Before you start contributing, I recommend that you read the [Contributor Guidelines](https://shenyu.apache.org/community/contributor-guide).

You can check the code coverage of ShenYu at this [site](https://app.codecov.io/gh/apache/incubator-shenyu).

Some pr you can refer to:

[in test](https://github.com/apache/incubator-shenyu/pulls?page=2&q=is%3Apr+is%3Aclosed+test+label%3A%22in%3A+test%22)

https://github.com/apache/incubator-shenyu/pull/2734
