### ISSUE TITLE
[Volunteer] Improve unit test coverage of shenyu-common

### ISSUE THREAD

**Issue by JooKS-me** [apache/shenyu#3275]
### Volunteer help

As a branch of #3274 .

At present, the test coverage of shenyu-common module is not high. Please try to make the test coverage of each class reach more than 80% (in the case of ensuring the stability of the test).

If you would like to help, please leave a message under this issue. BTW, you can use `Run 'Test in 'xxx'' With Coverage` in IntelliJ IDEA  to see the approximate coverage.
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/62384022/163818963-37ab02fb-cf6b-4d53-9d8f-192a87222178.png">

PS: If the modified code is too much, it can be divided into several pr submissions.

- [x] org.apache.shenyu.common.cache @selectbook 
- [x] org.apache.shenyu.common.concurrent @Albertsirius 
- [x] org.apache.shenyu.common.config @Nick-fengzl
- [x] org.apache.shenyu.common.dto @luoweijr
- [ ] org.apache.shenyu.common.timer @jun0315
- [ ] org.apache.shenyu.common.utils (maybe a large job) @zhangcly

**Comment by selectbook** [comment]
@JooKS-me Hi, I would like to participate in this and pick the package of  org.apache.shenyu.common.cache

**Comment by Albertsirius** [comment]
@JooKS-me Hello, I would like to participate in this task. Can you assign the package of org.apache.shenyu.common.concurrent to me ?

**Comment by JooKS-me** [comment]
> @JooKS-me Hello, I would like to participate in this task. Can you assign the package of org.apache.shenyu.common.concurrent to me ?

Good luck

**Comment by luoweijr** [comment]
@JooKS-me  Hello, I would like to hava a try and pick the package of org.apache.shenyu.common.dto

**Comment by jun0315** [comment]
@JooKS-me Hi, I would like to participate in this and pick the package of org.apache.shenyu.common.timer

**Comment by fengzhili12** [comment]
Hello, I would like to participate in this task. Can you assign the package of org.apache.shenyu.common.config to me ?

**Comment by fengzhili12** [comment]
@JooKS-me Hello, I would like to participate in this task. Can you assign the package of org.apache.shenyu.common.config to me ?

**Comment by zhangcly** [comment]
@JooKS-me can you assigin `org.apache.shenyu.common.utils` to me? thanks

**Comment by JooKS-me** [comment]
@Nick-fengzl @zhangcly OK :)

**Comment by MichaelDeSteven** [comment]
@JooKS-me @selectbook Hi, I see org.apache.shenyu.common.cache is no complete, can I take this task?

**Comment by JooKS-me** [comment]
> @JooKS-me @selectbook Hi, I see org.apache.shenyu.common.cache is no complete, can I take this task?

@MichaelDeSteven Hi, I found the cache package unnecessary to enhance the test. You can find small packages that need to improve test coverage in https://app.codecov.io/gh/apache/incubator-shenyu, and then create an issue to indicate what you want to do. Generally, we need to increase the test coverage to 80%.

BTW, ping @jun0315 @zhangcly, are you still doing it?

**Comment by jun0315** [comment]
> > @JooKS-me @selectbook Hi, I see org.apache.shenyu.common.cache is no complete, can I take this task?
> 
> @MichaelDeSteven Hi, I found the cache package unnecessary to enhance the test. You can find small packages that need to improve test coverage in https://app.codecov.io/gh/apache/incubator-shenyu, and then create an issue to indicate what you want to do. Generally, we need to increase the test coverage to 80%.
> 
> BTW, ping @jun0315 @zhangcly, are you still doing it?

Sorry, I find it a little difficult. Please assign this task to others.

**Comment by selectbook** [comment]
> > > @JooKS-me @selectbook Hi, I see org.apache.shenyu.common.cache is no complete, can I take this task?
> > 
> > 
> > @MichaelDeSteven Hi, I found the cache package unnecessary to enhance the test. You can find small packages that need to improve test coverage in https://app.codecov.io/gh/apache/incubator-shenyu, and then create an issue to indicate what you want to do. Generally, we need to increase the test coverage to 80%.
> > BTW, ping @jun0315 @zhangcly, are you still doing it?
> 
> Sorry, I find it a little difficult. Please assign this task to others.

@JooKS-me  I will try to finish the task of org.apache.shenyu.common.timer

**Comment by JooKS-me** [comment]
> @JooKS-me I will try to finish the task of org.apache.shenyu.common.timer

Thanks and good luck!

**Comment by xcsnx** [comment]
Hello, I would like to participate in this task. Can you assign the package of org.apache.shenyu.common.utils.ReflectUtils to me
