### ISSUE TITLE
[Question] some code is not used in shenyu-client-dubbo?

### ISSUE THREAD

**Issue by midnight2104** [apache/shenyu#3317]
### Question

1. org.apache.shenyu.client.apache.dubbo.ApacheDubboServiceBeanListener
```java
    public ApacheDubboServiceBeanListener(final PropertiesConfig clientConfig, final ShenyuClientRegisterRepository shenyuClientRegisterRepository) {
        Properties props = clientConfig.getProps();
        String contextPath = props.getProperty(ShenyuClientConstants.CONTEXT_PATH);
        String appName = props.getProperty(ShenyuClientConstants.APP_NAME);
        if (StringUtils.isBlank(contextPath)) {
            throw new ShenyuClientIllegalArgumentException("apache dubbo client must config the contextPath or appName");
        }
        this.contextPath = contextPath;
        this.appName = appName;
        this.host = props.getProperty(ShenyuClientConstants.HOST);
        this.port = props.getProperty(ShenyuClientConstants.PORT);
        executorService = Executors.newSingleThreadExecutor(new ThreadFactoryBuilder().setNameFormat("shenyu-apache-dubbo-client-thread-pool-%d").build());
        publisher.start(shenyuClientRegisterRepository);
    }
```

A thread pool(executorService ) was created in the constructor, but not used. Is it possible to delete it?

2. ShenyuDubboClient
Does ShenyuDubboClient only work on methods and not on classes?
The current definitions are as follows:
```java

@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD})
@Inherited
public @interface ShenyuDubboClient {

    /**
     * Path string.
     *
     * @return the string
     */
    String path();

    /**
     * Rule name string.
     *
     * @return the string
     */
    String ruleName() default "";

    /**
     * Desc string.
     *
     * @return String string
     */
    String desc() default "";

    /**
     * Enabled boolean.
     *
     * @return the boolean
     */
    boolean enabled() default true;
}
```
Shouldn't we change `@Target({ElementType.TYPE, ElementType.METHOD}) ` to `@Target({ElementType.METHOD})`?

**Comment by dragon-zhang** [comment]
I think we should add the logic of annotation on the splicing class. Guys,what do you think ?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-shenyu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月25日(星期一) 上午10:08
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[apache/incubator-shenyu] [Question] some code is not used in shenyu-client-dubbo? (Issue #3317)





 
Question
  
org.apache.shenyu.client.apache.dubbo.ApacheDubboServiceBeanListener
      public ApacheDubboServiceBeanListener(final PropertiesConfig clientConfig, final ShenyuClientRegisterRepository shenyuClientRegisterRepository) {         Properties props = clientConfig.getProps();         String contextPath = props.getProperty(ShenyuClientConstants.CONTEXT_PATH);         String appName = props.getProperty(ShenyuClientConstants.APP_NAME);         if (StringUtils.isBlank(contextPath)) {             throw new ShenyuClientIllegalArgumentException("apache dubbo client must config the contextPath or appName");         }         this.contextPath = contextPath;         this.appName = appName;         this.host = props.getProperty(ShenyuClientConstants.HOST);         this.port = props.getProperty(ShenyuClientConstants.PORT);         executorService = Executors.newSingleThreadExecutor(new ThreadFactoryBuilder().setNameFormat("shenyu-apache-dubbo-client-thread-pool-%d").build());         publisher.start(shenyuClientRegisterRepository);     }
 
A thread pool(executorService ) was created in the constructor, but not used. Is it possible to delete it?
  
ShenyuDubboClient
 Does ShenyuDubboClient only work on methods and not on classes?
 The current definitions are as follows:
  @Retention(RetentionPolicy.RUNTIME) @Target({ElementType.TYPE, ElementType.METHOD}) @Inherited public @interface ShenyuDubboClient {     /**      * Path string.      *      * @return the string      */     String path();     /**      * Rule name string.      *      * @return the string      */     String ruleName() default "";     /**      * Desc string.      *      * @return String string      */     String desc() default "";     /**      * Enabled boolean.      *      * @return the boolean      */     boolean enabled() default true; }
 
Shouldn't we change @Target({ElementType.TYPE, ElementType.METHOD})  to @Target({ElementType.METHOD})?

**Comment by midnight2104** [comment]
yes, I think so.

**Comment by dragon-zhang** [comment]
> yes, I think so.

How about publishing tasks and asking friends in the community to help?

**Comment by midnight2104** [comment]
> > yes, I think so.
> 
> How about publishing tasks and asking friends in the community to help?

It's ok

**Comment by midnight2104** [comment]
> I checked the `TarsServiceBeanPostProcessor` and `GrpcClientBeanPostProcessor` and found that maybe `all RPC client` has this bug.

good job
