### ISSUE TITLE
[Task] Shenyu Gateway Config Based On Service

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#3364]
### Description

I find most selectors hava common config, I think shenyu maybe provide another config mode in new page：Base On Service Configuration.
<img width="576" alt="无标题" src="https://user-images.githubusercontent.com/20184263/165973366-9e521554-5a01-46b0-bcfd-f13d8f2c6c6b.png">

### Task List

task1. develop shenyu gateway admin service display page and add rule page.
task2. develop batch add selector api for shenyu gateway.

**Comment by moremind** [comment]
please assign me, After I think a lot, I will submit my suggestion for the design.

**Comment by moremind** [comment]
https://lanhuapp.com/url/oUtSl
project: shenyu
password: YWnR
I have designed the archetype，please check this design.

**Comment by li-keguo** [comment]
What function does this page want to achieve?
Can you describe it in detail?
In addition, the admin can't perceive how many services there are now. This needs to provide the corresponding service meta information when registering. Can you contribute to this?

Looking forward to your contribution

**Comment by moremind** [comment]
> What function does this page want to achieve? Can you describe it in detail? In addition, the admin can't perceive how many services there are now. This needs to provide the corresponding service meta information when registering. Can you contribute to this?
> 
> Looking forward to your contribution

you can look at ` https://lanhuapp.com/url/oUtSl project: shenyu password: YWnR` about this issue detail.

this like common config, for most plugins, these have may have common selector in a server, they can config simply by this feature.

I will contribute this feature in three weeks.
