### ISSUE TITLE
[BUG] shenyu-admin change password , report error(parameter error: role is not null)，only change password is not valid

### ISSUE THREAD

**Issue by IceFoxs** [apache/shenyu#3381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Only change password is not valid.
<img width="623" alt="image" src="https://user-images.githubusercontent.com/26451038/166858414-e1d19df9-feac-455c-ac72-85e9670bac3e.png">

### Expected Behavior

Modify password success.

### Environment

```markdown
ShenYu version(s):2.4.3
```

**Comment by li-keguo** [comment]
I will fix it

**Comment by ilikepomelo** [comment]
2.5.1-SNAPSHOT， still have this issue
