### ISSUE TITLE
[BUG] when json body is {},and dubbo method has ParameterType，can not find dubbo method

### ISSUE THREAD

**Issue by siegezhang** [apache/shenyu#3394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when json body is {},and dubbo method has ParameterType，can not find dubbo method

in ApacheDubboProxyService  genericInvoker method:

`        if (StringUtils.isBlank(metaData.getParameterTypes()) || ParamCheckUtils.dubboBodyIsEmpty(body)) {
            pair = new ImmutablePair<>(new String[]{}, new Object[]{});
        } else {
            pair = dubboParamResolveService.buildParameter(body, metaData.getParameterTypes());
        }
`
![Untitled](https://user-images.githubusercontent.com/7414806/167387906-5b7852d1-0bef-42d1-9bac-519496a3a01a.png)

when StringUtils.isBlank(metaData.getParameterTypes() is false, and ParamCheckUtils.dubboBodyIsEmpty(body) is true（we input an {} to dubbo method),the dubbo method has parameterTypes,because of:

`
pair = new ImmutablePair<>(new String[]{}, new Object[]{});
`

we lost the parameterTypes,then invoke dubbo throw java.lang.NoSuchMethodException

we should handle the above code carefully

### Environment

```markdown
ShenYu version(s):2.4.3
```

**Comment by dragon-zhang** [comment]
Can you show the dubbo code part?

**Comment by siegezhang** [comment]
> Can you show the dubbo code part?

dubbo method :

![image](https://user-images.githubusercontent.com/7414806/167395944-2526ce76-813a-41cd-8968-213bf29946c9.png)


input ：

![image](https://user-images.githubusercontent.com/7414806/167396044-b150e2d8-fe37-4e7c-97f6-55f3f30e5e0c.png)


dubbo  GenericFilter  filter handle:

![image](https://user-images.githubusercontent.com/7414806/167396351-d3605424-08ce-4ea2-ae72-fb17f3d18fe6.png)


`Method method = ReflectUtils.findMethodByMethodSignature(invoker.getInterface(), name, types);`

will throw Exception:


![image](https://user-images.githubusercontent.com/7414806/167396646-a36e94db-418f-4d80-baa3-72479870386d.png)

the root reason is lost the parameterTypes info i mentioned above

**Comment by dragon-zhang** [comment]
Does the class of request have a field? 
If have at least one filed, please do not use `{}`; 
If not have filed, please remove the request parameter of the dubbo method.

**Comment by siegezhang** [comment]
> Does the class of request have a field? If have at least one filed, please do not use `{}`; If not have filed, please remove the request parameter of the dubbo method.

the request has fields,but all of them is not required

not use {}:

![image](https://user-images.githubusercontent.com/7414806/167417270-9dbf5076-c001-4bc1-98fd-2ef81cb00dc6.png)

**Comment by dragon-zhang** [comment]
Can you fix it? Don't forget `alibaba dubbo` @siegezhang

**Comment by siegezhang** [comment]
> Can you fix it? Don't forget `alibaba dubbo` @siegezhang

ok , has time limited? now avoid this problem  is to add space between {} like:
{ }

**Comment by dragon-zhang** [comment]
There is no time limit, enjoy the contribution !




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-shenyu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月9日(星期一) 晚上9:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/incubator-shenyu] [BUG] when json body is {},and dubbo method has ParameterType，can not find dubbo method (Issue #3394)





  
Can you fix it? Don't forget alibaba dubbo @siegezhang
  
ok , has time limited? now avoid this problem  is to add space between {} like:
 { }
