### ISSUE TITLE
[Question] The WAF plug-in is not running properly in black model

### ISSUE THREAD

**Issue by Once2012** [apache/shenyu#3416]
### Question

我在配置waf插件时遇到了这样一个问题，按文档说明，当waf的model为black时，任何匹配的流量都会被拦截，结果我测试下来没有拦截畅通无阻。然而当我加了permission条件为reject之后，就真正被拦截了。不是说black模式下不需要配permission的么？是不是我哪里配错了？
![13f7bfaa580afa74482b4f584189029](https://user-images.githubusercontent.com/19165279/169006315-458f3725-dd79-46e4-99f7-4901600af3a2.png)
![18f7076e338ffa61d8e7189e6c14198](https://user-images.githubusercontent.com/19165279/169006385-7c3aa8a6-8194-4ad2-b3f2-8d3a940bcb7f.png)
![994a1ef4846c67d74628f370cdb29fb](https://user-images.githubusercontent.com/19165279/169006407-a3f65a97-feb7-4438-9a95-daa11c8af47a.png)
permission设为reject之后，拦截就生效了
![b0ac76f8f7fffa4ad90b2b7ba47746a](https://user-images.githubusercontent.com/19165279/169006483-06e0f229-0816-417f-b4f5-5d9b0d47c57f.png)

**Comment by yu199195** [comment]
see this ： https://shenyu.apache.org/docs/next/plugin-center/authority-and-certification/waf-plugin
