### ISSUE TITLE
[Task] add BrpcPlugin to support brpc

### ISSUE THREAD

**Issue by dragon-zhang** [apache/shenyu#3450]
### Description

brpc is an industrial-grade RPC framework used throughout Baidu, with 1,000,000+ instances(not counting clients) and thousands kinds of services.

As for `shenyu-client-brpc`, we can use [`brpc-spring` module](https://github.com/baidu/brpc-java/tree/master/brpc-spring) to implment it.

As for `shenyu-spring-boot-starter-client-brpc`, we can use [`brpc-spring-boot-starter` module](https://github.com/baidu/brpc-java/tree/master/brpc-spring-boot-starter) to implment it.

As for `shenyu-plugin-brpc`, we can use [`brpc-java` module](https://github.com/baidu/brpc-java/tree/master/brpc-java-governance) to implment it.

### Task List

1. - [x] add `shenyu-client-brpc` module, @MichaelDeSteven ;
2. - [x] add `shenyu-spring-boot-starter-client-brpc` module, @MichaelDeSteven ;
3. - [x] add `shenyu-examples-brpc` module, @MichaelDeSteven ;
4. - [x] add doc for `shenyu-client-brpc`, @MichaelDeSteven ;
5. - [x] ~~support `generic call` for `brpc`, @dragon-zhang~~;
6. - [x] ~~support `generic call` for `brpc-java`, @dragon-zhang~~;
7. - [x] add `shenyu-plugin-brpc` module with BrpcPlugin module, @MichaelDeSteven ;
8. - [x] add `shenyu-spring-boot-starter-plugin-brpc` module, @MichaelDeSteven ;
9. - [x] add `shenyu-integrated-test-brpc` module; @dragon-zhang 
10. - [x] add doc for `shenyu-plugin-brpc`, @MichaelDeSteven ;

**Comment by MichaelDeSteven** [comment]
can I task this task？

**Comment by dragon-zhang** [comment]
sure, thanks

**Comment by dragon-zhang** [comment]
I listed all the tasks. It seems that the workload is heavy. What tasks would you like to complete? @MichaelDeSteven

**Comment by MichaelDeSteven** [comment]
here is my progress: brpc-java not support generic call, so this is a challenge for me. Now I have refer some doc and code, almost complete brpc plugin, but there need some debug and test. 
So I would like to complete brpc plugin（task 1、2、5、6、7） at lease.

**Comment by MichaelDeSteven** [comment]
If the grpc plugin part is no emergency, I can task all this task.

**Comment by dragon-zhang** [comment]
No emergency, just make it the best. As for `generic call`, I will try to provide this feature for `brpc`.

**Comment by dragon-zhang** [comment]
task6 is depend on task3 and task5

**Comment by MichaelDeSteven** [comment]
all right. My previous solution was `bytebuddy` which can `dynamic generate class` instead of `generic call`. This way is refer to `tars-plugin`.

**Comment by MichaelDeSteven** [comment]
BTW, at the beginning I thought task3 is about grpc part which names `shenyu-plugin-grpc`.  But when I look it describe again, maybe this is typo. It should display like that add `shenyu-plugin-brpc`.

**Comment by dragon-zhang** [comment]
> BTW, at the beginning I thought task3 is about grpc part which names `shenyu-plugin-grpc`. But when I look the describe again, maybe this is typo. It should display like that add `shenyu-plugin-brpc`.

yes, text had been fixed.

**Comment by dragon-zhang** [comment]
> 



> all right. My previous solution was `bytebuddy` which can `dynamic generate class` instead of `generic call`. This way refers to `tars-plugin`.

Sounds good, you can do this first as you think. If the brpc supports it, then do the transformation. How it's feel?

**Comment by MichaelDeSteven** [comment]
> > 
> 
> > all right. My previous solution was `bytebuddy` which can `dynamic generate class` instead of `generic call`. This way refers to `tars-plugin`.
> 
> Sounds good, you can do this first as you think. If the brpc supports it, then do the transformation. How it's feel?

Sure. brpc task3 is critical. I will finish it first.

**Comment by dragon-zhang** [comment]
> > > 
> > 
> > 
> > > all right. My previous solution was `bytebuddy` which can `dynamic generate class` instead of `generic call`. This way refers to `tars-plugin`.
> > 
> > 
> > Sounds good, you can do this first as you think. If the brpc supports it, then do the transformation. How it's feel?
> 
> Sure. Task3 is critical. I will finish it first.

BTW, have you joined the contributor wechat group ?

**Comment by MichaelDeSteven** [comment]
> > 
> 
> > all right. My previous solution was `bytebuddy` which can `dynamic generate class` instead of `generic call`. This way refers to `tars-plugin`.
> 
> Sounds good, you can do this first as you think. If the brpc supports it, then I do the transformation. How it's feel?

Not yet. Maybe I can join now.

**Comment by dragon-zhang** [comment]
Please add wechat Z18179469818







------------------ Original ------------------
From: SongTao Zhuang ***@***.***&gt;
Date: Sun,Jun 5,2022 1:01 PM
To: apache/incubator-shenyu ***@***.***&gt;
Cc: dragon-zhang ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [apache/incubator-shenyu] [Task] add BrpcPlugin to support brpc(Issue #3450)





     
all right. My previous solution was bytebuddy which can dynamic generate class instead of generic call. This way refers to tars-plugin.
  
Sounds good, you can do this first as you think. If the brpc supports it, then I do the transformation. How it's feel?
  
Not yet. Maybe I can join now.

**Comment by MichaelDeSteven** [comment]
@dragon-zhang Sorry about that I can't solve task3 currently. Which must use `generic call` to make it success. I have tried `bytebuddy`  such complex way. But `brpc-java` has many difference with `tars-java` so the way isn't work it. I suppose that task3 can be done if `brpc-java` support `generic call`.  After that I can continue finish other subtask during this time I can do other contribution. If there's anything I need to do,keep me informed plz.

**Comment by dragon-zhang** [comment]
> @dragon-zhang Sorry about that I can't solve task3 currently. Which must use `generic call` to make it success. I have tried `bytebuddy` such complex way. But `brpc-java` has many difference with `tars-java` so the way isn't work it. I suppose that task3 can be done if `brpc-java` support `generic call`. After that I can continue finish other subtask during this time I can do other contribution. If there's anything I need to do,keep me informed plz.

Got it,I readjusted the task sequencing, task6,7,8,9 will be blocked now. You can continue to complete other tasks. When you feel that the code of each module has been completed, you can submit PR by module.

**Comment by 847850277** [comment]
any task can i support？

**Comment by MichaelDeSteven** [comment]
> any task can i support？

Maybe you can do other contribute first? This feature need `brpc` support `generic call`.  If there any task need to support I will give you. anyway, thx:-)

**Comment by dragon-zhang** [comment]
Sorry, I'm learning c++ now, and contributing code to brpc will be late.

**Comment by zhouyao1994** [comment]
may be , we can use "github project" to "project management"
