### ISSUE TITLE
[Task] develop  mock plugin 

### ISSUE THREAD

**Issue by zouchangfu** [apache/shenyu#3464]
### Description

Develop a mock plugin that allows users to return mock data through configuration.

### Task List

1. add MockPlugin
2. thie admin side can configure mock data

**Comment by li-keguo** [comment]
than is good idea.

Interested friends can participate

**Comment by LiuTianyou** [comment]
please assign to me.

**Comment by LiuTianyou** [comment]
@zouchangfu  Is it convenient to leave your contact information?

**Comment by zouchangfu** [comment]
@LiuTianyou ok

**Comment by moremind** [comment]
close via #3571 #3599
