### ISSUE TITLE
Signature plugin extension

### ISSUE THREAD

**Issue by ZkeyZzz** [apache/shenyu#3507]
### Question

How does the signature plugin add body or form request parameters to signature verification?

**Comment by yu199195** [comment]
We will consider adding this feature in the future, and you can provide it as well~

**Comment by ZkeyZzz** [comment]
> 以后我们会考虑增加这个功能，你也可以提供~

I have never used webFlux, I am very unfamiliar with this, I feel confused when I read the source code, I have read it for a long time and don't know how to judge the request parameters

**Comment by ZkeyZzz** [comment]
> We will consider adding this feature in the future, and you can provide it as well~

I want to extend an open platform plug-in to provide external interface services, I need to ensure the security of the interface

**Comment by yu199195** [comment]
> I have never used webFlux, I am very unfamiliar with this, I feel confused when I read the source code, I have read it for a long time and don't know how to judge the request parameters


maybe you can learn about webFlux, you can also enter the shenyu community (dev@shenyu.apache.org or wechat)for help

**Comment by dajitui** [comment]
DefaultSignService unable to meet demand?
