### ISSUE TITLE
[Task] selector/rule uses tree query matching algorithm

### ISSUE THREAD

**Issue by dragon-zhang** [apache/shenyu#3509]
### Description

I checked all the implementations of `org.apache.shenyu.plugin.base.condition.judge.PredicateJudge`, and now I only think of these two optimization points. If you have some better ideas, please leave a message below.

### Task List

1. - [ ] uses tree query matching algorithm in `org.apache.shenyu.plugin.base.condition.judge.MatchPredicateJudge`; @damonxue 
2. - [ ] use `KMP` in `org.apache.shenyu.plugin.base.condition.judge.ContainsPredicateJudge`; @dragon-zhang 

### Useful Information
https://github.com/npgall/concurrent-trees
https://github.com/julienschmidt/httprouter
https://github.com/viz-rs/path-tree
https://github.com/Nugine/nuclear-router
https://tech.meituan.com/2021/05/20/shepherd-api-gateway.html

**Comment by damonxue** [comment]
I'm interested in it,pls assign to me. After discussing with you, I will finish it.

**Comment by dragon-zhang** [comment]
> I'm interested in it,pls assign to me. After discussing with you, I will finish it.

ok, thanks, I will detail this task as soon as possible.

**Comment by damonxue** [comment]
U can find me in wechat group 'Apache Shenyu社区交流4群' by name 'Fibonacci'.

**Comment by dragon-zhang** [comment]
see https://github.com/apache/shenyu/pull/4536
