### ISSUE TITLE
[GLCC 2022]Optimize the front-end page of ShenYu-admin

### ISSUE THREAD

**Issue by erdengk** [apache/shenyu#3515]
### Description

The purpose of this project is to optimize the front-end of ShenYu-admin. At present, the front-end function of admin is not perfect. The project requires to optimize the front-end page effect and add verification codes for the login function.

### Task

- [ ] Optimize the front-end page effect
- [ ] Login function added verification code

### Project technical requirements

Familiar with JavaScript and basic front-end technologies

### Expected completion results

(1) ShenYu-admin's page is optimized
(2) Complete the verification code for the login function

### Mentor

XiaoYu | xiaoyu@apache.org

GLCC Project Link : https://www.gitlink.org.cn/glcc/subjects/detail/147

**Comment by zzq1314zll** [comment]
google authenticator?

**Comment by ChenchengY** [comment]
Hi, I have a question regarding this issue, is this a pure front-end project? I would like to confirm that the verification code is generated and used only in the front end and we don't need to use Shiro or other backend code to control the verification code generation.
