### ISSUE TITLE
接入客户端sofa时，泛化调用网关层拿到的结果会默认加上type, fileds，fieldNames 这些字段

### ISSUE THREAD

**Issue by zhangchenbiao** [apache/shenyu#3544]
### Question

sofa服务接入网关，调用暴露的接口会对返回结果做一些封装处理，sofa泛化调用 结果会统一封装成GenericObject对象，GenericObject中重写了toString方法，而GenericObject是只读模式，改不了源代码，
![image](https://user-images.githubusercontent.com/26429176/173295178-0ae60412-12ba-4809-b1aa-58d19146eed8.png)，导致正常的请求返回成了这样，
![image](https://user-images.githubusercontent.com/26429176/173295899-475f07d5-7e23-4609-8672-3a9d0a44f069.png)
，实际期望的返回结果应该是这样的
![image](https://user-images.githubusercontent.com/26429176/173296136-99a8cceb-804d-4322-a2d8-d31482446863.png)

在网关层 更多的是请求转发，不需要对出参进行二次处理，希望考虑优化

**Comment by zhangchenbiao** [comment]
还有一点 如果下游服务返回Array，程序会报错，ArrayList 无法转GenericObject
![image](https://user-images.githubusercontent.com/26429176/173311674-db69cca1-c41b-40a8-930d-69def56b101d.png)
![image](https://user-images.githubusercontent.com/26429176/173312091-3dce6b9b-b3c0-498c-8d9f-5fe6060ac0bf.png)

**Comment by dragon-zhang** [comment]
@zhangchenbiao can you fix this ?

**Comment by zhangchenbiao** [comment]
本地已修复，自测通过，但是否达到通用标准需要更多场景覆盖

**Comment by dragon-zhang** [comment]
> 本地已修复，自测通过，但是否达到通用标准需要更多场景覆盖

It doesn't matter. Submit the PR and the community will help you improve it together.
