### ISSUE TITLE
can shenyu support httpcopy 

### ISSUE THREAD

**Issue by yuzhijia88** [apache/shenyu#3555]
### Question

i want to copy http request in some condition to my test enviroment  . can shenyu support it ?

**Comment by yuzhijia88** [comment]
> You just need to copy data from the database.

no,no,no ,i not want data from database;

i want to copy online real time request to my test enviroment to do some real test. it looks like tcpcopy ,but i think if  shenyun can support this freature ,it's more convenient

**Comment by yuzhijia88** [comment]
> > You just need to copy data from the database.
> 
> no,no,no ,i not want data from database;
> 
> i want to copy online real time request to my test enviroment to do some real test. it looks like tcpcopy ,but i think if shenyun can support this freature ,it's more convenient

it also looks like  nginx  ngx_http_mirror_module 
ngx_http_mirror_module模块
nginx官网公布了nginx1.13.4最新的ngx_http_mirror_module模块，利用mirror模块，业务可以将线上实时访问流量拷贝至其他环境，基于这些流量可以做版本发布前的预先验证，进行流量放大后的压测等等

**Comment by KevinClair** [comment]
Sounds great, maybe it's a new feature.You can pull request if you are instreated in.

**Comment by prFor** [comment]
It feels like a nice feature
