### ISSUE TITLE
[Question] gateway use dubbo3.0.8 has error

### ISSUE THREAD

**Issue by LBJWt** [apache/shenyu#3558]
### Question

I change  the gateway bootstrap  apache dubbo version to 3.0.8. it does not  work.
I see that `org.apache.shenyu.plugin.apache.dubbo.cache.ApacheDubboConfigCache` method uses `ApplicationModel.getConfigManager().getDefaultConsumer()`, this `getDefaultConsumer()` does not have this method in dubbo3.0.8

**Comment by moremind** [comment]
unsupport dubbo 3.0
