### ISSUE TITLE
[BUG] Curator need upgrade to new version to avoid endless 'ConnectionState.LOST' log

### ISSUE THREAD

**Issue by qixiaobo** [apache/shenyu#3567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

You may refer to this https://issues.apache.org/jira/browse/CURATOR-405

> It's unclear how it got into this state, but a client started endlessly logging "Session timeout has elapsed while SUSPENDED". Curator 3.0 is supposed to go to LOST and inject a session expiration but it's not working in this case.
For our case , shenyu prints lots of log like this 
![image](https://user-images.githubusercontent.com/2881751/173993277-7f099263-07cf-46c9-a743-0b1fd238e1a8.png)
And this cause filebeat using lots of cpu
![image](https://user-images.githubusercontent.com/2881751/173993398-7f6e9609-387f-46b3-be9b-9fad4f0073f4.png)

Indeed we should to upgrade Curator to a new version above 4.1.0
https://github.com/apache/incubator-shenyu/search?l=Maven+POM&q=curator.version

![image](https://user-images.githubusercontent.com/2881751/173993846-53038f50-5547-49f8-9d69-20be2ed92cb1.png)

### Expected Behavior

Never print these endless logs

### Environment

```markdown
ShenYu version(s):2.4.0
```

### Debug logs

2022-06-15 21:01:23,830 [WARN] [Curator-ConnectionStateManager-0] o.a.c.f.s.ConnectionStateManager:307 Session timeout has elapsed while SUSPENDED. Injecting a session expiration. Elapsed ms: 2851944. Adjusted session timeout ms: 40000

**Comment by qixiaobo** [comment]
> Curator 5.0 Breaking Changes
> Curator 5.0 contains a few non-backward compatible/breaking changes from previous versions.
> 
> ZooKeeper 3.4.x is no longer supported (the associated Compatibility classes/methods have been removed). If you still need to use Curator with ZooKeeper 3.4.x you will need to use a previous version. [Click here for details](https://curator.apache.org/zk-compatibility-34.html).
> The old ListenerContainer classes have been removed so as not to leak Guava classes into Curator APIs. Instead use the new StandardListenerManager.
> Exhibitor support has been removed.
> ConnectionHandlingPolicy and related classes have been removed.
> The Reaper and ChildReaper classes/recipes have been removed. You should use ZooKeeper container nodes instead.
> newPersistentEphemeralNode() and newPathChildrenCache() were removed from GroupMember.
> ServiceCacheBuilder<T> executorService(CloseableExecutorService executorService) was removed from ServiceCacheBuilder.
> ServiceProviderBuilder<T> executorService(CloseableExecutorService executorService) was removed from ServiceProviderBuilder.
> static boolean shouldRetry(int rc) was removed from RetryLoop.
> static boolean isRetryException(Throwable exception) was removed from RetryLoop

https://curator.apache.org/breaking-changes.html
So maybe we should upgrade to 4.3.0
https://mvnrepository.com/artifact/org.apache.curator/curator-client/4.3.0

**Comment by hgaol** [comment]
Hi @qixiaobo , thanks for your advice! we're considering curator version 4.3. We'll do more testing for examples like sofa/dubbo/motan to make sure it works well with them. For now, I've tested it works well with sofa example. More details can refer to this issue #3556 .

**Comment by hgaol** [comment]
I also met this before, that's may caused by the net issue. If you want to avoid the endless log, you may can also set log level for specific package or class. Anyway, upgrade to version 4.3 is a good topic, thank you!

**Comment by qixiaobo** [comment]
> I also met this before, that's may caused by the net issue. If you want to avoid the endless log, you may can also set log level for specific package or class or change the connection/session timeout. Anyway, upgrade to version 4.3 is a good topic, thank you!
So glad to hear this.
Since this is not the common case, I just want to follow your step to upgrade curator version.

**Comment by hgaol** [comment]
Hi @qixiaobo , the curator version has been updated to 4.3.0, you can pull the newest master branch and try again. You can refer to this PR #3569 . If still any issue, welcome to investigate and contribute~

**Comment by qixiaobo** [comment]
> Hi @qixiaobo , the curator version has been updated to 4.3.0, you can pull the newest master branch and try again. You can refer to this PR #3569 . If still any issue, welcome to investigate and contribute~

Thanks for remind, I will try but may not reproduce because it is such a rare case
