### ISSUE TITLE
when thrift can be supported?

### ISSUE THREAD

**Issue by wbzhou** [apache/shenyu#3601]
### Question

when thrift can be supported?

**Comment by dragon-zhang** [comment]
Now Shenyu has supported Dubbo which can support `thrift protocol`, but some changes need to be made; Or directly add a `thrift plugin`. Would you like to provide this feature?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-shenyu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月22日(星期三) 晚上7:55
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[apache/incubator-shenyu] when thrift can be supported? (Issue #3601)





 
Question
 
when thrift can be supported?

**Comment by noorall** [comment]
> Now Shenyu has supported Dubbo which can support `thrift protocol`, but some changes need to be made; Or directly add a `thrift plugin`. Would you like to provide this feature?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apache/incubator-shenyu" ***@***.***&gt;; 发送时间:&nbsp;2022年6月22日(星期三) 晚上7:55 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[apache/incubator-shenyu] when thrift can be supported? (Issue #3601) Question when thrift can be supported? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

Hello, I want to try this job. Can you assign it to me?
