### ISSUE TITLE
[BUG] shenyu-bootstrap High memory usage

### ISSUE THREAD

**Issue by qicz** [apache/shenyu#3613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/2174082/175500449-09ae067d-b399-4b41-b954-ae9ad9804cff.png)

### Environment

```markdown
ShenYu version(s): 2.4.3
```

**Comment by dengliming** [comment]
@qicz Can you try to provide the file of Java Heap Dumps?

**Comment by homihq** [comment]
Can you provide more details so that this issue can be replicated?

**Comment by homihq** [comment]
Can someone assign this issue to me, I can check in the weekend on local and AWS. Suggest mentioning product version when logging issues.
