### ISSUE TITLE
[Question] <license and dependencies license check script>

### ISSUE THREAD

**Issue by damonxue** [apache/shenyu#3696]
### Question

a script to check dependencies license.

when release a new version, we should check dependencies license one by one with eyes now. so i see dubbo done this in a script[1][2], so rise this question.

[1]  https://github.com/apache/dubbo/issues/3840
[2]  https://github.com/apache/dubbo/pull/3941

**Comment by yu199195** [comment]
i think maybe add this license check

**Comment by damonxue** [comment]
ok,  i will switch this to a task.
