### ISSUE TITLE
[Task] <license and dependencies license check script>

### ISSUE THREAD

**Issue by damonxue** [apache/shenyu#3697]
### Description

task about : [#3696](https://github.com/apache/incubator-shenyu/issues/3696)

1. Every file should check license-header.txt.
    refer to [dubbo #6060](https://github.com/apache/dubbo/pull/6060)
2. dependencies license check script.
    refer to 
    [dubbo #3941](https://github.com/apache/dubbo/pull/3941)
    [history licenseCheck.sh](https://github.com/apache/dubbo/commits/3.0/licenseCheck.sh)

### Task List

- [x] 1. codeStyle: file license header check.
- [ ] 2. dependencies license check script.

**Comment by damonxue** [comment]
@yu199195 so, should i make a module with the name 'shenyu-build-tools' or some other name?  and the licenseCheck use shell script or language script?

**Comment by yu199195** [comment]
add license check plugin in root pom.xml

**Comment by damonxue** [comment]
ok.

**Comment by yu199195** [comment]
@yu199195 hi，can you add apache shenyu contributor wechat group？ if not add my wechat：13786298670

**Comment by damonxue** [comment]
chat with @yunlongn , i realize that `apache-rat-plugin` plugin has checked dependences license. and combine the license and notice is complex when release. so the task 2 is unuseless. 
> Rat check: Summary over all files. Unapproved: 0, unknown: 0, generated: 0, approved: 7 licenses.
@yu199195
