### ISSUE TITLE
I want to ask, if the calling method is Dubbo or sofa, is it supported

### ISSUE THREAD

**Issue by Summary-wcj** [apache/shenyu#3726]
### Question

I want to ask, if the calling method is Dubbo or sofa, is it supported

**Comment by KevinClair** [comment]
see [Dubbo proxy](https://shenyu.apache.org/docs/user-guide/dubbo-proxy)

**Comment by Summary-wcj** [comment]
> see [Dubbo proxy](https://shenyu.apache.org/docs/user-guide/dubbo-proxy)

Maybe I didn't make it clear. My question is: is it Dubbo or sofa on the consumer side,

Dubbo (consumer) - > Gateway -- > Dubbo or sofa (provider)

**Comment by KevinClair** [comment]
It sounds a bit strange, why do requests between dubbo services need to go through a gateway?

**Comment by Summary-wcj** [comment]
> It sounds a bit strange, why do requests between dubbo services need to go through a gateway?

We have a scenario where each caller (consumer) may be Dubbo or sofa to call sofa services or Dubbo services.
dubbo --> dubbo
dubbo-->sofa
sofa-->dubbo
sofa-->sofa

**Comment by KevinClair** [comment]
`Sofa` has been supported `Dubbo protocol`, if you want it, you can use it.However, `Dubbo` didn't support 'Sofa protocol'. Maybe you should try `Http protocol`, both of them have been supported.

**Comment by Summary-wcj** [comment]
> `Sofa` has been supported `Dubbo protocol`, if you want it, you can use it.However, `Dubbo` didn't support 'Sofa protocol'. Maybe you should try `Http protocol`, both of them have been supported.

That is to say, soft -- > gatway -- > Dubbo is supported, right?

**Comment by Summary-wcj** [comment]
> I don't understand, why need to go through a gateway?

Well, I was confused by you. Is Shenyu a gateway system? Soft -- > gatway -- > Dubbo. If it's strange, how about HTTP requesting Dubbo or soft through Shenyu?

**Comment by dragon-zhang** [comment]
How about add `Sofa protocol` SPI in `dubbo` directly ? @Summary-wcj

**Comment by Summary-wcj** [comment]
> How about add `Sofa protocol` SPI in `dubbo` directly ? @Summary-wcj

Sorry, I misunderstood

**Comment by KevinClair** [comment]
Of course, shenyu is a gateway system.

**Comment by dragon-zhang** [comment]
@Summary-wcj please close this issue if you think no problem.

**Comment by dragon-zhang** [comment]
@Summary-wcj If you think there are still problems, please create a new issue.

**Comment by Jimbean0615** [comment]
I encountered the same problem, and I think it is a universal problem. So I created a dubbo consumer client myself to solve the problem of how dubbo consumers quickly accessing the Shenyu gateway.
[Dubbo Consumer Client for Shenyu](https://github.com/Jimbean0615/shenyu-gateway-client)
