### ISSUE TITLE
I want to expand the modifyResponse plug-in， If the value corresponding to a key, including XXX, is replaced to YYY

### ISSUE THREAD

**Issue by huangdangxlp** [apache/shenyu#3727]
For example, the original return value:

{
   "code": "500",
   "MSG": "repeated request"
}

Final return value:
{
   "code": "500",
   "MSG": "request exceeded this month, please try again next month"
}

I see the existing functions are related to key: removebodykeys, addbodykeys, replacebodykeys. I want to add a replacebodyvalues. Config has three functions: key, regexvalue, replacevalue.

Where should I start? Thanks for your advice

**Comment by yu199195** [comment]
pls used english，
