### ISSUE TITLE
[Task] add upload file example and integrated test

### ISSUE THREAD

**Issue by dragon-zhang** [apache/shenyu#3740]
### Description

Currently, although ShenYu supports the upload interface of forwarding files, there are no relevant examples and integration tests. This task needs you to finish these.

The upload file can be committed to `shenyu-examples/shenyu-examples-common/src/main/resources`, just upload one file.

During integration testing, ~~you may need to unzip the fat jar of `SpringBoot`~~.

just create and write new file, check https://github.com/apache/shenyu/pull/3768

### Task List

1. - [x] add file upload example for `shenyu-examples-http`; @847850277 
2. - [x] add file upload example for `shenyu-examples-https`; @lahmXu 
3. - [x] add file upload example for `shenyu-examples-springmvc`; @847850277 
4. - [x] add file upload example for `shenyu-examples-springmvc-tomcat`; @847850277 
5. - [x] add file upload example for `shenyu-examples-websocket`; @mahaitao617
6. - [x] add file upload integration test for `shenyu-integrated-test-http`; @847850277 
7. - [x] add file upload integration test for `shenyu-integrated-test-https`; @lahmXu 
8. - [x] add file upload integration test for `shenyu-integrated-test-spring-cloud`; @lahmXu 
9. - [x] add file upload integration test for `shenyu-integrated-test-websocket`; @mahaitao617
10. - [x] add file upload example for `shenyu-examples-springcloud`; @lahmXu

**Comment by mahaitao617** [comment]
please assign task5 and task9 to me

**Comment by 847850277** [comment]
please assign task 1、3、4、6 to me.

**Comment by lahmXu** [comment]
Please assign task 2,7,8,10 to me, thanks!

**Comment by dragon-zhang** [comment]
Thanks for your contribution !
