### ISSUE TITLE
[Task] use `pathPatter` as default rule condition operator

### ISSUE THREAD

**Issue by dragon-zhang** [apache/shenyu#3741]
### Description

`PathPatternPredicateJudge` has better performance than `MatchPredicateJudge`, but `PathPatternPredicateJudge` does not support writing `**` in the middle of the path (such as `/api/**/xxx`), so when `param value` of `rule condition` has `**` in the middle, we should still use `MatchPredicateJudge`. Otherwise, use `PathPatternPredicateJudge`.

Major code changes in `org.apache.shenyu.admin.service.register.AbstractShenyuClientRegisterServiceImpl#buildRpcDefaultRuleDTO`.

### Task List

- [ ] use `pathPatter` as default rule condition operator when path not has `**` in the middle.

**Comment by 847850277** [comment]
i want to try,can assign to me?

**Comment by dragon-zhang** [comment]
sure, thanks







------------------ Original ------------------
From: zhengpeng ***@***.***&gt;
Date: Fri,Jul 22,2022 9:18 AM
To: apache/shenyu ***@***.***&gt;
Cc: dragon-zhang ***@***.***&gt;, Assign ***@***.***&gt;
Subject: Re: [apache/shenyu] [Task] use `pathPatter` as default rule condition operator (Issue #3741)





 
i want to try,can assign to me?
