### ISSUE TITLE
[Question] If the admin is multi-instance, how does websocket synchronize data to the gateway?

### ISSUE THREAD

**Issue by sheepblueblue** [apache/shenyu#3748]
### Question

If the admin is multi-instance, how does websocket synchronize data to the gateway?

**Comment by yu199195** [comment]
config multi admin url

**Comment by sheepblueblue** [comment]
> 

In production environments, we often configure domain names. Is it better to use the redis/mq publish-subscribe mode on the admin side to notify other admins?

**Comment by sheepblueblue** [comment]
@yu199195

**Comment by KevinClair** [comment]
> > 
> 
> In production environments, we often configure domain names. Is it better to use the redis/mq publish-subscribe mode on the admin side to notify other admins?

I dong't understand,  why need to nodify other admins?

**Comment by sheepblueblue** [comment]
If both the gateway and the admin are multi-instances, the gateway uses the domain name to connect to the admin through the websocket, and one gateway instance can only connect to one admin instance. How to update other gateway instances? If the admin does not notify other admins?



---- Replied Message ----
| From | Kevin ***@***.***> |
| Date | 07/26/2022 11:43 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [apache/shenyu] [Question] If the admin is multi-instance, how does websocket synchronize data to the gateway? (Issue #3748) |

In production environments, we often configure domain names. Is it better to use the redis/mq publish-subscribe mode on the admin side to notify other admins?

I dong't understand, why need to nodify other admins?
