### ISSUE TITLE
Shenyu Gateway forwarding URL parameter urldecode problem

### ISSUE THREAD

**Issue by bluewu** [apache/shenyu#3769]
### Question

shenyu 2.4.3 

Get request  
url is like queryTaskPage?examState=0&orders%5B0%5D.asc=true&size=9&current=1&examName=&_t=1658991926619
Gateway forwarding URL parameter urldecode  change to 
queryTaskPage?examState=0&orders[0].asc=true&size=9&current=1&examName=&_t=1658991926619

tomcat webservice response 400

but i find use nginx forwarding URL is also the same
 queryTaskPage?examState=0&orders%5B0%5D.asc=true&size=9&current=1&examName=&_t=1658991926619

response is success。

You can use the GET request receive array argument to reproduce the problem

**Comment by impactCn** [comment]
I will follow up on this issue.

**Comment by yangguihua** [comment]
Has this problem been solved?
