### ISSUE TITLE
[Task] use `#exchangeToMono` replace `#exchange`

### ISSUE THREAD

**Issue by dragon-zhang** [apache/shenyu#3773]
### Description

use `org.springframework.web.reactive.function.client.WebClient.RequestHeadersSpec#exchangeToMono` replace `org.springframework.web.reactive.function.client.WebClient.RequestHeadersSpec#exchange`, but make sure https://github.com/apache/shenyu/issues/3686 and https://github.com/apache/shenyu/issues/3687 not happens.

### Task List

1. - [ ] use `#exchangeToMono` replace `#exchange` in `WebClientPlugin` @spicydev
2. - [x] add integrated test for https://github.com/apache/shenyu/issues/3158 @moremind 
3. - [x] add integrated test for https://github.com/apache/shenyu/issues/3687 @moremind

**Comment by moremind** [comment]
maybe exchangeToMono?

**Comment by spicydev** [comment]
Hi @moremind / @dragon-zhang , 
I have created below pr with changes to completely implement new WebClient request/response spec using retrieve() method instead of exchange().
https://github.com/apache/shenyu/pull/3775

I need some help in validating these client changes before we can merge the pr.

**Comment by moremind** [comment]
hi,@spicydev, exchangeToMono or exchangeToFlux process request more than retrive, and shenyu process http response by response plugin. So, I think you must think a lot.

**Comment by dragon-zhang** [comment]
> maybe exchangeToMono?

I remember there seemed to be a bug before. It was said that `Mono` had a size limit, and changed to `Flux` as final.

**Comment by moremind** [comment]
> > maybe exchangeToMono?
> 
> I remember there seemed to be a bug before. It was said that `Mono` had a size limit, and changed to `Flux` as final.

it can change

**Comment by moremind** [comment]
> > > maybe exchangeToMono?
> > 
> > 
> > I remember there seemed to be a bug before. It was said that `Mono` had a size limit, and changed to `Flux` as final.
> 
> it can change

maybe change body to byte[], and write to DataBuffer

**Comment by moremind** [comment]
about lose data, maybe think `DataBufferUtils.join()`

**Comment by dragon-zhang** [comment]
> about lose data, maybe use `DataBufferUtils.join()`

got, I've seen it in https://github.com/apache/shenyu/issues/3158

**Comment by moremind** [comment]
i have writed use this

![image](https://user-images.githubusercontent.com/20184263/182013151-ff289ce5-e16f-44ab-8098-7bd9cf8e8229.png)

**Comment by dragon-zhang** [comment]
> maybe exchangeToMono?

I've changed title and task description.

**Comment by dragon-zhang** [comment]
As for https://github.com/apache/shenyu/issues/3158 and https://github.com/apache/shenyu/issues/3687 , can you add these two case to our integrated tests? @moremind

**Comment by moremind** [comment]
> As for #3158 and #3687 , can you add these two case to our integrated tests? @moremind

ok, I will do it.
