### ISSUE TITLE
[BUG] upgrade nacos-client due to security issue

### ISSUE THREAD

**Issue by pjfanning** [apache/shenyu#3784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/advisories/GHSA-2g86-r6w2-wqqr

### Environment

```markdown
ShenYu version(s):
```

**Comment by yu199195** [comment]
ok, maybe upgrade.  can  you  provider pr ?

**Comment by pjfanning** [comment]
@yu199195 I created #3787
