### ISSUE TITLE
[BUG] Typo in the architecture image

### ISSUE THREAD

**Issue by Hongbo-Miao** [apache/shenyu#3786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The architecture in the readme has a typo https://github.com/apache/shenyu#architecture

### Expected Behavior

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/3375461/182324219-f8adb5ba-2359-43f2-8c20-a6892a307658.png">

**Comment by yu199195** [comment]
@Hongbo-Miao Hi， Thanks， we will fix it.

**Comment by mkrivoshein** [comment]
Hello @yu199195 , looks like this is not an issue any longer. Could you please check? Unable to find this image within the latest README.md

**Comment by yu199195** [comment]
@mkrivoshein Yes，Now，This image is no longer used~
