### ISSUE TITLE
[Question]  support clickhouse-log plugin 

### ISSUE THREAD

**Issue by 847850277** [apache/shenyu#3801]
### Question

   Hi, community,
    Is support necessary clickhouse-log plugin. if need ,i will Implement it.

**Comment by yu199195** [comment]
of cause， you can send eamil to dev@shenyu.apache.org.

How to design, how to implement , etc.

**Comment by 847850277** [comment]
when i finish some design，i will sent to this mail.

**Comment by 847850277** [comment]
@yu199195  I've already sent it. It seems that the other party hasn't received it. so i comment on this issues.

## background
In some scenarios, the storage method of the log system may be the ES solution, which can also solve most problems. But in some scenarios, it also has its shortcomings. For example, to count some data with a long time span, there are enough data in the ES index. It takes some time to match them. At the same time, with the expansion of the system scale, the access volume of the log system has increased. If es is used, its maintenance cost and learning cost will also be large. Under the log system, for the above scenario, Clickhouse is another storage scheme of the log system.
In some enterprises, such as BiliBili and Ctrip, there are also many practices of Clickhouse in the log system.
Therefore, if someone uses Shenyu gateway and also wants to use Clickhouse as the database of the logging system, we can provide Shenyu's LoggingClickHousePlugin support.

## functional design
- The following figure
![clickhouseplugin](https://user-images.githubusercontent.com/12622645/183236249-4cdefb5b-2b23-40eb-a2be-73e7fdc23058.png)

- 1 LoggingClickHousePlugin extends AbstractLoggingPlugin ,AbstractLoggingPlugin extends AbstractShenyuPlugin.
    LoggingClickHousePlugin#doLogExecute() method can get data about Request and Response.
- 2 ClickHouseLogCollector extends AbstractLogCollector
    ClickHouseLogCollector#collect() method can collect log datas
- 3 ClickHouseLogCollectClient implements LogConsumeClient interface
    ClickHouseLogCollectClient#consume() method can save data to clickhouse database
