### ISSUE TITLE
[WeOpen-Star] Using agent technology to rewrite client

### ISSUE THREAD

**Issue by dragon-zhang** [apache/shenyu#3806]
## How to Participation

1. reply: [WeOpen Star]I would like to help 
2. add this wechat.  note : 摘星
<img width="430" alt="image" src="https://user-images.githubusercontent.com/9673503/183059212-152376b4-e08c-41cb-bb28-7339262e9cb0.png">

### Description

The inspiration for this task comes from `istio`.

Nowadays, Shenyu clients are `embedded SDKs`, and the cost of upgrading clients is high. Using `java agent` technology to rewrite clients can greatly reduce the upgrade cost.

[byte-buddy](https://github.com/raphw/byte-buddy) and [one-java-agent](https://github.com/alibaba/one-java-agent) are  good choices.

### Task List

1. - [ ] add `shenyu-client-agent-alibaba-dubbo` module; @847850277 
2. - [ ] add `shenyu-client-agent-apache-dubbo` module; @847850277 
3. - [ ] add `shenyu-client-agent-grpc` module; @runqi-zhao 
4. - [ ] add `shenyu-client-agent-springcloud` module; @mahaitao617 
5. - [ ] add `shenyu-client-agent-springmvc` module; @mahaitao617 
6. - [ ] add `shenyu-client-agent-motan` module; @mangoGoForward 
7. - [ ] add `shenyu-client-agent-sofa` module; @Albertsirius 
8. - [ ] add `shenyu-client-agent-tars` module; @runqi-zhao 
9. - [ ] add `shenyu-client-agent-websocket` module; @lahmXu 

### How to contributor

You can see this : [Contributor Guide](https://shenyu.apache.org/zh/community/contributor-guide/)

1. I suggest you subscribe to shenyu dev mailing list, and when you encounter any problems, or when you finish,
you can send an email to dev@shenyu.apache.org

2.  I suggest you git clone the source code and finish the changes. like this : 

fork  this to you repository :   https://github.com/apache/shenyu.git

```
git clone git@github.com:${YOUR_USERNAME}/${TARGET_REPO}.git

git checkout -b a-dev-branch

git push origin a-dev-branch
```

### Verification

After you modify file in verify local and you can see this : [How to build shenyu](https://github.com/apache/shenyu/blob/master/README.md) .

After you pull request merged. You can verify to this :  [en-doc](https://shenyu.apache.org/docs/next/user-guide/property-config/gateway-property-config) ,  [zh-doc](https://shenyu.apache.org/zh/docs/next/user-guide/property-config/gateway-property-config)

**Comment by mahaitao617** [comment]
please assign task4 and task5 to me

**Comment by lahmXu** [comment]
Please assign task 9 to me, thanks!

**Comment by 847850277** [comment]
pls assign task 1、2 to me，thanks.

**Comment by mangoGoForward** [comment]
[WeOpen Star]I would like to help, please assign task 6 to me, thanks!

**Comment by dragon-zhang** [comment]
> please assign task4 and task5 to me

Please reply [WeOpen Star]I would like to help and task number to get the task.

**Comment by dragon-zhang** [comment]
> pls assign task 1、2 to me，thanks.

Please reply [WeOpen Star]I would like to help and task number to get the task.

**Comment by 847850277** [comment]
[WeOpen Star]I would like to help, please assign task 1、2 to me, thanks!

**Comment by Albertsirius** [comment]
[WeOpen Star]I would like to help, please assign task 7 to me, thanks!

**Comment by runqi-zhao** [comment]
[WeOpen Star]I would like to help, please assign task 3、8 to me, thanks!

**Comment by dragon-zhang** [comment]
sorry, it's better to wait https://github.com/apache/shenyu/issues/3932 finish and then starting.
