### ISSUE TITLE
[Task] Consolidate etcd dependencies into one

### ISSUE THREAD

**Issue by hgaol** [apache/shenyu#3807]
### Description

Currently, there're 2 different etcd dependencies in Shenyu. And Can not even start `admin` by etcd registration.

In admin, it now uses
```xml
        <dependency>
            <groupId>io.etcd</groupId>
            <artifactId>jetcd-core</artifactId>
            <version>${jetcd-core.version}</version>
        </dependency>
```

In `shenyu-register-client-server-etcd`, it now uses
```xml
 <dependency>
            <groupId>com.coreos</groupId>
            <artifactId>jetcd-core</artifactId>
            <version>${jetcd.version}</version>
        </dependency>
```

When start admin, it will occur below errors because of this issue.

```log
Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.coreos.jetcd.internal.impl.ClientConnectionManager.defaultChannelBuilder(ClientConnectionManager.java:187)

The following method did not exist:

    'io.grpc.netty.NettyChannelBuilder io.grpc.netty.NettyChannelBuilder.usePlaintext(boolean)'

The calling method's class, com.coreos.jetcd.internal.impl.ClientConnectionManager, was loaded from the following location:

    jar:file:/Users/hgao/.m2/repository/com/coreos/jetcd-core/0.0.2/jetcd-core-0.0.2.jar!/com/coreos/jetcd/internal/impl/ClientConnectionManager.class

The called method's class, io.grpc.netty.NettyChannelBuilder, is available from the following locations:

    jar:file:/Users/hgao/.m2/repository/io/grpc/grpc-netty/1.27.1/grpc-netty-1.27.1.jar!/io/grpc/netty/NettyChannelBuilder.class

The called method's class hierarchy was loaded from the following locations:

    io.grpc.netty.NettyChannelBuilder: file:/Users/hgao/.m2/repository/io/grpc/grpc-netty/1.27.1/grpc-netty-1.27.1.jar
    io.grpc.internal.AbstractManagedChannelImplBuilder: file:/Users/hgao/.m2/repository/io/grpc/grpc-core/1.27.1/grpc-core-1.27.1.jar
    io.grpc.ManagedChannelBuilder: file:/Users/hgao/.m2/repository/io/grpc/grpc-api/1.27.1/grpc-api-1.27.1.jar
```

It's better to consolidate to only one dependency for etcd, and the preference is https://mvnrepository.com/artifact/io.etcd/jetcd-core/0.7.3.

### Task List

1. add io.etcd.jetcd into dependency management part in root pom file.
2. remove the other etcd dependency in whole project and replace by above one.
3. refine the code if any error.
4. test the whole process to make sure it works well. The whole process includes starting `admin`, `bootstrap` and an example like `http example application` using etcd as registration configuration.

**Comment by mahaitao617** [comment]
please assign these four tasks to me

**Comment by hgaol** [comment]
> please assign these four tasks to me

Good luck to you!

**Comment by mahaitao617** [comment]
> > please assign these four tasks to me
> 
> Good luck to you!

ths

**Comment by hgaol** [comment]
Hi @mahaitao617 , any update about this task?

**Comment by wanghuan0606** [comment]
> 
hello，can you assign these four tasks to me~

**Comment by mahaitao617** [comment]
> > 
> 
> hello，can you assign these four tasks to me~

ok

**Comment by wanghuan0606** [comment]
> > > 
> > 
> > 
> > hello，can you assign these four tasks to me~
> 
> ok

I have push pr~

**Comment by hgaol** [comment]
Hi @wanghuan0606 , can you run `http-example` successfully? I can't run it without changing the grpc version to a higher version. Can you try it? Thanks!

**Comment by wanghuan0606** [comment]
ok～I'll try it tonight.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Han Gao ***@***.***>
发送时间: Tuesday, August 16, 2022 9:52:26 AM
收件人: apache/shenyu ***@***.***>
抄送: huanccwang ***@***.***>; Mention ***@***.***>
主题: Re: [apache/shenyu] [Task] Consolidate etcd dependencies into one (Issue #3807)


Hi @wanghuan0606<https://github.com/wanghuan0606> , can you run http-example successfully? I can't run it without changing the grpc version to a higher version. Can you try it? Thanks!

―

**Comment by wanghuan0606** [comment]
> Hi @wanghuan0606 , can you run `http-example` successfully? I can't run it without changing the grpc version to a higher version. Can you try it? Thanks!

Hello, I can run http-example successfully without any other operate.
