### ISSUE TITLE
[BUG] hystrix plugin can't circuitBreaker

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#3820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have config rule in rule No.1, and I change executionIsolationStrategy semaphore and thread, but I change from semaphore to thread, hystrix pluign can't circuitBreaker, this need restart or delete this rule and reconfig can circuitBreaker?

### Expected Behavior

change rule in same rule, can circuitBreaker.

### Environment

```markdown
ShenYu version(s):2.5.0
```

### Debug logs

 [WebSocketConnectReadThread-262] INFO  org.apache.shenyu.plugin.sync.data.websocket.client.ShenyuWebsocketClient - handleResult({"groupType":"RULE","eventType":"UPDATE","data":[{"id":"1556813932145938432","name":"/http/test/**","pluginName":"hystrix","selectorId":"1556813671167954944","matchMode":0,"sort":1,"enabled":true,"loged":true,"handle":"{\"requestVolumeThreshold\":\"5\",\"errorThresholdPercentage\":\"5\",\"sleepWindowInMilliseconds\":\"50000\",\"executionIsolationStrategy\":0,\"callBackUri\":\"\",\"groupKey\":\"\",\"commandKey\":\"\",\"hystrixThreadPoolConfig\":{\"coreSize\":10,\"maximumSize\":10,\"maxQueueSize\":12}}","conditionDataList":[{"paramType":"uri","operator":"startsWith","paramName":"/","paramValue":"/http/"}]}]})

[WebSocketConnectReadThread-262] INFO  org.apache.shenyu.plugin.sync.data.websocket.client.ShenyuWebsocketClient - handleResult({"groupType":"RULE","eventType":"UPDATE","data":[{"id":"1556813932145938432","name":"/http/test/**","pluginName":"hystrix","selectorId":"1556813671167954944","matchMode":0,"sort":1,"enabled":true,"loged":true,"handle":"{\"requestVolumeThreshold\":\"5\",\"errorThresholdPercentage\":\"5\",\"sleepWindowInMilliseconds\":\"50000\",\"executionIsolationStrategy\":1,\"callBackUri\":\"\",\"groupKey\":\"\",\"commandKey\":\"\",\"maxConcurrentRequests\":\"0\"}","conditionDataList":[{"paramType":"uri","operator":"startsWith","paramName":"/","paramValue":"/http/"}]}]})

**Comment by yunlongn** [comment]
pls assign me
