### ISSUE TITLE
[BUG] RateLimiterPlugin concurrent hanlder  error.

### ISSUE THREAD

**Issue by yunlongn** [apache/shenyu#3829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

look setting.
![image](https://user-images.githubusercontent.com/38271111/184076949-965f32d5-b0e4-47df-b3ed-a3e02a933bba.png)

start jmeter.  request http://localhost:9195/http/test/findByUserId?userId=1

![image](https://user-images.githubusercontent.com/38271111/184077109-2f9da540-b473-45cf-9536-58f33a8a71a0.png)

view results
![image](https://user-images.githubusercontent.com/38271111/184077338-68dd0a7c-c8dc-4ddc-a083-d93554d5cca5.png)

### Environment

```markdown
ShenYu version(s):
```

### Anything else?

I think it's caused by `doFinally` deleting the redis key.
![image](https://user-images.githubusercontent.com/38271111/184077547-3fe4e09d-459c-41cc-a9d8-c215b278aa00.png)

**Comment by yunlongn** [comment]
pls assign me

**Comment by yunlongn** [comment]
I understand what this handler does is:
For example: Limit 100 simultaneous access requests. If those 100 requests are not processed, no new requests will come in

**Comment by dragon-zhang** [comment]
If there is still problem, please reopen this issue. @yunlongn
