### ISSUE TITLE
[BUG] <title> base on 2.4.3-release, bootstrap startup error

### ISSUE THREAD

**Issue by bigbug-dachong** [apache/shenyu#3830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

base on 2.4.3-release branch

admin start first. and i can operate the sys normally.

bootstrap sync config through http-longpolling. i have test it work nomal.

but, the bootstrap server often start failed.

i log and debug the bootstrap. i found when first start, need sync plugin config,  and need sort Plugin.

when step into method, begin to send event. this program will hold on.
![image](https://user-images.githubusercontent.com/46708615/184077909-45988be2-260d-4a47-b924-c498d0f9cfc1.png)

i step into ,and found when run to synchronized(). the plugin load process will hold . the other scheduler-task are normal running. and i test 'http://127.0.0.1:9195/actuator/health' has no resp. the bootstrap strat faild.
![image](https://user-images.githubusercontent.com/46708615/184078118-bc2d5676-1b06-4391-a02c-33c4df3617b2.png)
![image](https://user-images.githubusercontent.com/46708615/184078387-cbdbb97a-cdc6-49af-aa04-bb4291c0a75f.png)
![image](https://user-images.githubusercontent.com/46708615/184078453-01f72915-a99d-4480-9f31-c4f2cc4d30e4.png)

### Environment

```markdown
ShenYu version(s):
```

**Comment by bigbug-dachong** [comment]
i found the resolve ，but i don't understand what's the reason

i change the parallelStream to stream, this question can be fixed.
![image](https://user-images.githubusercontent.com/46708615/184087460-44b2c2d0-df08-41a4-a6d6-7f4492ca05c5.png)

**Comment by KevinClair** [comment]
Thanks for your question, this bug has been fixed in #3469
