### ISSUE TITLE
[Question]  How to access the skywalking extension log plugin

### ISSUE THREAD

**Issue by raffiagk** [apache/shenyu#3842]
### Question

1.I have implemented log plugin format output

2. local env   shenyu-2.4.3   shenyu-bootstarp （change logback  encoder ）  start with skywalking agent  

I noticed that in the log plugin, because the asynchronous call cannot get the tid, it shows N/A, what should I do now, help

**Comment by dengliming** [comment]
Can you provide your demo code? and the steps to reproduce : )
