### ISSUE TITLE
shenyu High availability

### ISSUE THREAD

**Issue by dajitui** [apache/shenyu#3849]
### Question

At present, I see that most of the data are obtained based on the configuration of Shenyu. If the network is delayed or hangs, it will directly affect the performance of the gateway. Do you consider making backups to improve the availability

**Comment by yu199195** [comment]
pls in english

**Comment by dajitui** [comment]
At present, I see that most of the data are obtained based on the configuration of Shenyu. If the network is delayed or hangs, it will directly affect the performance of the gateway. Do you consider making backups to improve the availability

**Comment by yu199195** [comment]
Now, Register And Data sncy support zookeeper，nacos，consul，ETCD .....
