### ISSUE TITLE
It is required to provide the ability that a gateway can only access a single service under a certain policy under a microservice cluster

### ISSUE THREAD

**Issue by jjxliu306** [apache/shenyu#3857]
### Description

For example, there is already a set of micro service clusters, and there are many services. It is impossible to start all services locally. When debugging is required, only service a needs to be started locally. After some configuration is made on the gateway side, the locally accessed service a will only flow to the local service, and other services will normally access.

**Comment by jjxliu306** [comment]
thanks

**Comment by damonxue** [comment]
Maybe this contains two point:
  * env profiles.
  * Cluster priority.
