### ISSUE TITLE
[Task] refactor shenyu-admin selector and rule

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#3858]
### Description

refactor shenyu admin selector and rule code

### Task List

1. [ ] refactor shenyu admin selector @lanseBlue 
2. [ ] refactor shenyu admin rule @tian-pengfei

**Comment by yunlongn** [comment]
Please assign task 2 to me

**Comment by Lifeng-Lv** [comment]
Can I try the first task？:-）

**Comment by moremind** [comment]
> Can I try the first task？:-）

I create for me

**Comment by Lifeng-Lv** [comment]
:-)

**Comment by lanseBlue** [comment]
hi,I want to try the first task

**Comment by tian-pengfei** [comment]
hi,I want to try .

**Comment by moremind** [comment]
> hi,I want to try the first task

assigned, thanks for your contributions!

**Comment by moremind** [comment]
> hi,I want to try .

assigned, thanks for your contributions!
