### ISSUE TITLE
[Task] desensitization of main fields in logs

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#3861]
### Description

desensitization of main fields in logs,for example:

requestbody:{"idCard": "361222xxxxxxxxxxx00", "name":"赵x明"},this rule can config.

![image](https://user-images.githubusercontent.com/20184263/185434790-04532f80-37e4-4116-b231-e0ecae95aa41.png)

### Task List

1. [ ] desensitization of main fields in logs for all log plugin

**Comment by yunlongn** [comment]
pls assign to me

**Comment by moremind** [comment]
> I want to try,please assign me.

ok, I have assigned, if you have some questions, please contact me

**Comment by wanghuan0606** [comment]
> 

I will contact you promptly if I have any question.

**Comment by moremind** [comment]
> > 
> 
> I will contact you promptly if I have any question.

my wechat is yijia1949
