### ISSUE TITLE
[BUG] 官网文档Spring Cloud服务接入描述有误

### ISSUE THREAD

**Issue by WattsNie** [apache/shenyu#3865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

官网文档版本 【2.4.3】
链接  [https://shenyu.apache.org/zh/docs/next/user-guide/spring-cloud-proxy](url)
示例3的描述中使用如下配置启动服务有误，配置的key少了spring cloud
![image](https://user-images.githubusercontent.com/18160403/185597347-542949dd-73a6-4e79-a8a1-02e85ce39b8f.png)

### Expected Behavior

应改为
![image](https://user-images.githubusercontent.com/18160403/185597475-15882eac-3e68-4c9d-ba78-9918ad239336.png)

### Steps To Reproduce

read doc

### Environment

```markdown
ShenYu version(s):2.4.3
```

### Debug logs

read doc

### Anything else?

read doc

**Comment by dragon-zhang** [comment]
can you fix it ?

**Comment by moremind** [comment]
can you fix it in shenyu-website, if you can't,I will fix it in next week.

**Comment by yu199195** [comment]
@WattsNie Hi， It be resolved.

**Comment by WattsNie** [comment]
> @WattsNie Hi， It be resolved.

Thanks
