### ISSUE TITLE
[BUG] <title> Request plugin can't replaceCookie

### ISSUE THREAD

**Issue by qizhq** [apache/shenyu#3870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/80200776/185831767-911f0501-b979-4137-81fc-1be368005d74.png)
Request plugin add new Rule to ReplaceCookie，But can't do it。

### Environment

```markdown
ShenYu version(s):
```

**Comment by JairoSun** [comment]
This is indeed a bug, and I successfully reproduced it. I'll fix it
