### ISSUE TITLE
[Volunteer] When a plugin changes, it should be initialized

### ISSUE THREAD

**Issue by shihuili1218** [apache/shenyu#3883]
### Volunteer help

When plugin parameters change, the common logic should be initialized and should not be computed each time a request is processed.

e.g. When using LoadBalance, Divide、Dubbo、Http plugin needs to calculate the weight for each request. To calculate the weight, you should only need to calculate it once when the configuration changes.

I don't know much about Shenyu yet, and I don't know if there is similar situation in other places. If this optimization is necessary and there are others that need to be optimized, please supplement, I can finish it together.

My thoughts are as follows:
In `CommonPluginDataSubscriber#onSelectorSubscribe`, sending the update or delete events, performs initialization logic in the corresponding plugin.

**Comment by yu199195** [comment]
Yes，I think it is necessary.  can you  provider this pr ?

**Comment by shihuili1218** [comment]
> 

of course

**Comment by shihuili1218** [comment]
This issue has been completed, please review
https://github.com/apache/shenyu/pull/3894

**Comment by KevinClair** [comment]
> This issue has been completed, please review #3894

TotalWeight is dynamic, see org.apache.shenyu.loadbalancer.entity.Upstream#warmup

**Comment by shihuili1218** [comment]
> > This issue has been completed, please review #3894
> 
> TotalWeight is dynamic, see org.apache.shenyu.loadbalancer.entity.Upstream#warmup

Oops, I see. the total weight cannot be calculated when the parameter is changed, so I will close this pr and open it again if necessary

**Comment by KevinClair** [comment]
Thanks a lot, if you have more question, you can reopen this issue.
