### ISSUE TITLE
[Question] <title> 如何拿到真实请求IP

### ISSUE THREAD

**Issue by bigbug-dachong** [apache/shenyu#3887]
### Question

查看了代码，插件中IP功能是通过 ForwardedRemoteAddressResolver 来实现获取真实ip的

但是在代码中，有2个点，没想清楚。

1、在extractXForwardedValues方法中，通过.split(", ")来切分ip，确定能切分开？是否多了空格？
![image](https://user-images.githubusercontent.com/46708615/187157316-ffeb0dee-f852-4346-ad24-80bf2d7abe66.png)

2、在判断XForwarded中可信值时，默认是取1，而且还倒序了。
加入中间经过代理层，这里是只信任上一跳吗？或者说只信任上一层代理地址？那和直接获取remote-ip不是一样了么？
![image](https://user-images.githubusercontent.com/46708615/187157406-35dd1018-10ea-499c-93a4-60227a613f52.png)

**Comment by bigbug-dachong** [comment]
刚好看到 阿里云SLB文档，里面x-forward-for确实有空格
![image](https://user-images.githubusercontent.com/46708615/187168597-350d0441-0475-4648-926c-63c189b1f434.png)

这个有固定标准吗。。

**Comment by yu199195** [comment]
pls in english
