### ISSUE TITLE
[BUG] open shenyu-admin page but is blank

### ISSUE THREAD

**Issue by ilikepomelo** [apache/shenyu#3888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[https://elk-pub.oss-cn-hangzhou.aliyuncs.com/shenyu-1.jpeg](url)

### Steps To Reproduce

1、click BasicConfig-》Plugin   page
2、click next page，met blank page

### Environment

```markdown
ShenYu version(s):2.5.1-SNAPSHOT
```

### Debug logs

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at render (index.a0c1819b.js:1:388633)
    at t.value (index.a0c1819b.js:1:1964926)
    at ur (index.a0c1819b.js:1:119668)
    at cr (index.a0c1819b.js:1:119463)
    at Au (index.a0c1819b.js:1:184255)
    at to (index.a0c1819b.js:1:144486)
    at $r (index.a0c1819b.js:1:144411)
    at Wr (index.a0c1819b.js:1:141332)
    at index.a0c1819b.js:1:98030
br @ index.a0c1819b.js:1
n.callback @ index.a0c1819b.js:1
ln @ index.a0c1819b.js:1
Mr @ index.a0c1819b.js:1
ao @ index.a0c1819b.js:1
WifJ.t.unstable_runWithPriority @ index.a0c1819b.js:1
Wt @ index.a0c1819b.js:1
oo @ index.a0c1819b.js:1
Wr @ index.a0c1819b.js:1
(anonymous) @ index.a0c1819b.js:1
WifJ.t.unstable_runWithPriority @ index.a0c1819b.js:1
Wt @ index.a0c1819b.js:1
qt @ index.a0c1819b.js:1
Bt @ index.a0c1819b.js:1
Hr @ index.a0c1819b.js:1
enqueueSetState @ index.a0c1819b.js:1
o.setState @ index.a0c1819b.js:1
s.onStateChange @ index.a0c1819b.js:1
notify @ index.a0c1819b.js:1
e.notifyNestedSubs @ index.a0c1819b.js:1
s.onStateChange @ index.a0c1819b.js:1
notify @ index.a0c1819b.js:1
e.notifyNestedSubs @ index.a0c1819b.js:1
s.onStateChange @ index.a0c1819b.js:1
notify @ index.a0c1819b.js:1
e.notifyNestedSubs @ index.a0c1819b.js:1
s.onStateChange @ index.a0c1819b.js:1
notify @ index.a0c1819b.js:1
e.notifyNestedSubs @ index.a0c1819b.js:1
s.onStateChange @ index.a0c1819b.js:1
s @ index.a0c1819b.js:1
(anonymous) @ index.a0c1819b.js:1
(anonymous) @ index.a0c1819b.js:1
(anonymous) @ index.a0c1819b.js:1
dispatch @ index.a0c1819b.js:1
(anonymous) @ index.a0c1819b.js:1
(anonymous) @ index.a0c1819b.js:1
r @ index.a0c1819b.js:1
c @ index.a0c1819b.js:1
o @ index.a0c1819b.js:1
C @ index.a0c1819b.js:1
E @ index.a0c1819b.js:1
l @ index.a0c1819b.js:1
n @ index.a0c1819b.js:1
Promise.then (async)
O @ index.a0c1819b.js:1
M @ index.a0c1819b.js:1
E @ index.a0c1819b.js:1
l @ index.a0c1819b.js:1
c @ index.a0c1819b.js:1
w @ index.a0c1819b.js:1
E @ index.a0c1819b.js:1
l @ index.a0c1819b.js:1
n @ index.a0c1819b.js:1
(anonymous) @ index.a0c1819b.js:1
r @ index.a0c1819b.js:1
c @ index.a0c1819b.js:1
o @ index.a0c1819b.js:1
(anonymous) @ index.a0c1819b.js:1
t @ index.a0c1819b.js:1
(anonymous) @ index.a0c1819b.js:1
(anonymous) @ index.a0c1819b.js:1
t @ index.a0c1819b.js:1
(anonymous) @ index.a0c1819b.js:1
(anonymous) @ index.a0c1819b.js:1
r.query @ index.a0c1819b.js:1
ln @ index.a0c1819b.js:1
Mr @ index.a0c1819b.js:1
ao @ index.a0c1819b.js:1
WifJ.t.unstable_runWithPriority @ index.a0c1819b.js:1
Wt @ index.a0c1819b.js:1
oo @ index.a0c1819b.js:1
Wr @ index.a0c1819b.js:1
(anonymous) @ index.a0c1819b.js:1
WifJ.t.unstable_runWithPriority @ index.a0c1819b.js:1
Wt @ index.a0c1819b.js:1
qt @ index.a0c1819b.js:1
Bt @ index.a0c1819b.js:1
v @ index.a0c1819b.js:1
xe @ index.a0c1819b.js:1
Show 49 more frames
index.a0c1819b.js:1 uncaught at t SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)

**Comment by yu199195** [comment]
pls modify title to english

**Comment by damonxue** [comment]
U can open this link [http://47.96.252.138:9095/](http://47.96.252.138:9095/), It's ok.

**Comment by ilikepomelo** [comment]
root cause:   
      HttpProcess request's config is Null.

now i set HttpProcess request's config to "{"ruleHandlePageType":"custom"}",   it goes ok
