### ISSUE TITLE
[api document] <No document>

### ISSUE THREAD

**Issue by LBJWt** [apache/shenyu#3893]
### Question

api document has not documentation

**Comment by KevinClair** [comment]
It will be added later, welcome to join.Contact @lianjunwei if you have more question.

**Comment by LBJWt** [comment]
> 

Thankyou ,and  About what time

**Comment by KevinClair** [comment]
Maybe in the next version.

**Comment by KevinClair** [comment]
I will close this issue, you can reopen it if you have more question.

**Comment by LBJWt** [comment]
> Maybe in the next version.

this feature in this version, why the  doc in the next version?  Does it mean that this function is not available.
