### ISSUE TITLE
[Question] 如何直接使用dubbo泛化调用

### ISSUE THREAD

**Issue by lossend** [apache/shenyu#3895]
### Question

dubbo客户端注册方式对业务侵入比较大，有没有办法直接通过dubbo泛化调用实现对后端dubb服务的调用

**Comment by JooKS-me** [comment]
If the way of annotation is too intrusive, you can manually configure it on the admin. And we are currently trying to implement non-intrusive client registration with javaagent, in #3806, which may be available soon.
