### ISSUE TITLE
[Question] k8s下websokcet数据同步方案会不会造成数据不一致？

### ISSUE THREAD

**Issue by lossend** [apache/shenyu#3900]
### Question

首选要保证可用性，admin要3个pod，gateway3个，这样要求gateway的websocket client要链接所有的admin，这里要填写多个urls，但是k8s下不能填写ip，多个pod一般是暴露service，这里只能填写一个url，那么会不会存在操作前端页面的时候请求到了其中一个admin，admin发送数据更新事件，可能只会通知到其中一个client，剩下两个client就不会数据更新？

**Comment by yu199195** [comment]
pls in english

**Comment by lossend** [comment]
answer myself:
when use websocket for data sync，admin is a stateful application，so deploy admin as StatefulSet Workload and create headless service for pod，and `sync.websoket.urls` is `pod1.stable.svc;pod2.stable.svc;pod13stable.svc`

**Comment by dengliming** [comment]
测试

**Comment by yu199195** [comment]
@lossend Hi，I guess you already know how to use it, I will close this issue~
