### ISSUE TITLE
[Question] Is possible to get wrong parameter order  when call http to dubbo rpc invoke

### ISSUE THREAD

**Issue by lossend** [apache/shenyu#3904]
### Question

the default dubbo param build function is following：
<img width="961" alt="image" src="https://user-images.githubusercontent.com/49791601/187884509-16eb08b3-9518-4843-8076-3274fba820f7.png">

Is possible to get wrong parameter order when gson deserialize the json？or keySet return unsorted set

**Comment by KevinClair** [comment]
Dubbo invoke doesn't care about the order of parameters.

**Comment by lossend** [comment]
> Dubbo invoke doesn't care about the order of parameters.

if paramTYpes is (int, int), also dont'care?

**Comment by KevinClair** [comment]
> > Dubbo invoke doesn't care about the order of parameters.
> 
> if paramTYpes is (int, int), also dont'care?

Why not use java obejct?

**Comment by lossend** [comment]
> > > Dubbo invoke doesn't care about the order of parameters.
> > 
> > 
> > if paramTYpes is (int, int), also dont'care?
> 
> Why not use java obejct?

rest api with two id

**Comment by lossend** [comment]
> > > Dubbo invoke doesn't care about the order of parameters.
> > 
> > 
> > if paramTYpes is (int, int), also dont'care?
> 
> Why not use java obejct?

get resource with two id

**Comment by KevinClair** [comment]
i mean replace two paramters with a java object.

**Comment by lossend** [comment]
> Dubbo invoke doesn't care about the order of parameters.
you are wong, dubbo params must be ordered
![image](https://user-images.githubusercontent.com/49791601/188114556-19f26845-d581-4b95-b76d-2bb0339bc191.png)

**Comment by lossend** [comment]
the desgin should be refer to dubbo office doc：

**Comment by lossend** [comment]
https://dubbo.apache.org/zh/docs3-v2/dubbo-go-pixiu/user/appendix/http-to-dubbo-default-stragety/#http-request

**Comment by KevinClair** [comment]
I mean dubbo invoke doesn't care about the order of parameters if you replace two paramters with a java object.
