### ISSUE TITLE
[Question] Why is shenyu-bootstrap jvm heap size fixed?

### ISSUE THREAD

**Issue by jbh2507** [apache/shenyu#3916]
### Question

Below is a part of the shell file executed when using shenyu-bootstrap 2.5.0 docker image. (line 34 of start.sh)

`JAVA_OPTS=" -server -Xmx2g -Xms2g -Xmn1g -Xss512k -XX:+DisableExplicitGC   -XX:LargePageSizeInBytes=128m"`

I think this should be non-static and should be selectable via environment variables.

I'd like to know if this setting is the best setting for most situations or if there is a way to set it up separately.

Full file can be found here: [start.sh](https://github.com/apache/shenyu/blob/v2.5.0/shenyu-dist/shenyu-bootstrap-dist/src/main/resources/bin/start.sh)

**Comment by yu199195** [comment]
You can customize the JVM info depending on your environment.

Can you provide it on docker image？
> I think this should be non-static and should be selectable via environment variables
