### ISSUE TITLE
[BUG] <db> postgres init sql has error

### ISSUE THREAD

**Issue by MiracleDx** [apache/shenyu#3919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/25627222/188534761-062ceee5-22a8-4e06-b022-fba7be1213c3.png)

the ` should be "

### Expected Behavior

![image](https://user-images.githubusercontent.com/25627222/188534840-0689f0ed-8d49-4953-a023-9bf91b736d7f.png)

### Environment

```markdown
ShenYu version(s): 2.5.0
```

**Comment by yu199195** [comment]
good idea
