### ISSUE TITLE
[BUG] <mysql init sql has error>

### ISSUE THREAD

**Issue by myownsword** [apache/shenyu#3921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
ShenYu version(s):
```

**Comment by yu199195** [comment]
whats error？

**Comment by misaya295** [comment]
> whats error？

![image](https://user-images.githubusercontent.com/45778734/188541036-92731d20-2533-4370-8b21-344d08b51271.png)

I think,The id of plugin_handle has a primary key conflict.

Can I fix it?

**Comment by yu199195** [comment]
ok， you can fix it
