### ISSUE TITLE
[BUG] <title> org.apache.shenyu.plugin.base.cache.MetaDataCache#CACHE not thread-safe

### ISSUE THREAD

**Issue by Shashengzhe** [apache/shenyu#3929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

CACHE存储的entry链中存在环，导致CACHE.get()无限循环

### Environment

```markdown
ShenYu version(s): 2.5.0
```

**Comment by dragon-zhang** [comment]
I see, because used `org.apache.commons.collections4.map.LRUMap`, could you please fix it? @Shashengzhe .If not, I will try to fix it after 3 days.

**Comment by Shashengzhe** [comment]
@dragon-zhang wait for you

**Comment by 898349230** [comment]
whether use `ReentrantLock` or `synchronized` can fix this?

**Comment by dragon-zhang** [comment]
> @dragon-zhang wait for you

see https://github.com/dragon-zhang/shenyu/tree/dev_issue_3929 , can you try it ? The bottom layer directly uses `ConcurrentHashMap`, which should be no problem.

**Comment by dragon-zhang** [comment]
> whether use `ReentrantLock` or `synchronized` can fix this? @dragon-zhang

Sorry for the late response, The bottom layer directly uses `ConcurrentHashMap` can get a better performance.

**Comment by Shashengzhe** [comment]
@dragon-zhang  I tried, no problem
