### ISSUE TITLE
[Task] refactor provider client sdks

### ISSUE THREAD

**Issue by dragon-zhang** [apache/shenyu#3932]
### Description

Now there are some duplicate codes in the client SDK. This issue aim to solve the problem.

There are some useful information in https://github.com/apache/shenyu/pull/3935 and https://github.com/apache/shenyu/pull/3931 .

### Task List

1. - [x] refactor shenyu-client-alibaba-dubbo; @847850277
2. - [x] refactor shenyu-client-grpc; @totalo
3. - [x] refactor shenyu-client-springcloud; @Albertsirius
4. - [x] refactor shenyu-client-motan; @misaya295
5. - [x] refactor shenyu-client-sofa; @zjcscut
6. - [x] refactor shenyu-client-tars; @yunlongn
7. - [x] refactor shenyu-client-websocket; @lahmXu

**Comment by 847850277** [comment]
pls asign task 1 to me. thanks

**Comment by totalo** [comment]
pls asign task 2 to me. thanks

**Comment by Albertsirius** [comment]
pls assign task 3 to me. Thx

**Comment by lahmXu** [comment]
Please assign task 7 to me, thanks!

**Comment by zjcscut** [comment]
pls asign task 5 to me. Thx

**Comment by yunlongn** [comment]
Please assign task 6 to me, thanks!

**Comment by Albertsirius** [comment]
@dragon-zhang Hi, I found the `appName` assigned different value when refactoring  `shenyu-client-springcloud`:
In the original constructor of `SpringCloudClientEventListener`:
<img width="591" alt="Screen Shot 2022-09-25 at 21 36 54" src="https://user-images.githubusercontent.com/1999408/192146429-0a498201-5a8b-4858-8637-4157aa4fd9aa.png">

But in the constructor of `AbstractContextRefreshedEventListener`:
<img width="944" alt="Screen Shot 2022-09-25 at 21 38 25" src="https://user-images.githubusercontent.com/1999408/192146463-21ac9a78-d090-4d4c-ad2b-bff95d797cf6.png">

Should I keep the original or use the superclass assignment?

**Comment by dragon-zhang** [comment]
> @dragon-zhang Hi, I found the `appName` assigned different value when refactoring `shenyu-client-springcloud`: In the original constructor of `SpringCloudClientEventListener`: <img alt="Screen Shot 2022-09-25 at 21 36 54" width="591" src="https://user-images.githubusercontent.com/1999408/192146429-0a498201-5a8b-4858-8637-4157aa4fd9aa.png">
> 
> But in the constructor of `AbstractContextRefreshedEventListener`: <img alt="Screen Shot 2022-09-25 at 21 38 25" width="944" src="https://user-images.githubusercontent.com/1999408/192146463-21ac9a78-d090-4d4c-ad2b-bff95d797cf6.png">
> 
> Should I keep the original or use the superclass assignment?

keep the original, and you need to override `getAppName`.

**Comment by dragon-zhang** [comment]
Good job, guys !
