### ISSUE TITLE
add a springcloud rule data ,and then delete it,call server will report 500 exception

### ISSUE THREAD

**Issue by hlcen66** [apache/shenyu#3939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/81564338/190077921-ae6a4de3-2d88-493f-8d33-1628fc733ff5.png)

![image](https://user-images.githubusercontent.com/81564338/190077983-7b4d94c8-e13c-43fc-a9eb-c9da40368581.png)

### Expected Behavior

1

### Steps To Reproduce

1

### Environment

```markdown
ShenYu version(s):2.5.0
```

### Debug logs

java.lang.NullPointerException: null
	at org.apache.shenyu.plugin.springcloud.SpringCloudPlugin.doExecute(SpringCloudPlugin.java:76)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ org.apache.shenyu.web.configuration.ErrorHandlerConfiguration$1 [DefaultWebFilterChain]
	*__checkpoint ⇢ org.apache.shenyu.web.filter.FileSizeFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.apache.shenyu.web.filter.CrossFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/order-base/order/list" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.apache.shenyu.plugin.springcloud.SpringCloudPlugin.doExecute(SpringCloudPlugin.java:76)
		at org.apache.shenyu.plugin.base.AbstractShenyuPlugin.execute(AbstractShenyuPlugin.java:117)
		at org.apache.shenyu.web.handler.ShenyuWebHandler$DefaultShenyuPluginChain.lambda$execute$0(ShenyuWebHandler.java:221)

### Anything else?

11

**Comment by yu199195** [comment]
whats mean?

>and then delete it？

**Comment by hlcen66** [comment]
> whats mean?
> 
> > and then delete it？

step 1：add a rule.

![image](https://user-images.githubusercontent.com/81564338/190096956-e0477683-f380-400d-8135-78fd45a32dbe.png)

step2：delete the rule we just added
![image](https://user-images.githubusercontent.com/81564338/190097316-ad255c44-c191-492d-a479-1e4a599b63a3.png)

step3：ask server
![image](https://user-images.githubusercontent.com/81564338/190097408-18eb319a-115f-4e6b-bfec-a20b696fa9bb.png)

**Comment by yunlongn** [comment]
I tested it, because the exception caused by the same Rule Name

**Comment by yunlongn** [comment]
![image](https://user-images.githubusercontent.com/38271111/190128564-abea6b7e-c449-4414-8a05-2cdb5bef0f9a.png)
It is caused by the code here, and the changes here are more involved. It is recommended to avoid duplicate rule names when using them.

**Comment by hlcen66** [comment]
I will submit another issue for another problem,this issue will be closed.

**Comment by hlcen66** [comment]
see this issue pls,thk. #3945
