### ISSUE TITLE
some problems about shenyu-admin manage ui

### ISSUE THREAD

**Issue by hlcen66** [apache/shenyu#3945]
### Question

version:2.5.0

if code like this：
@RestController
@RequestMapping("/order")
@ShenyuSpringCloudClient(path = "/order/**")
public class OrderController {

    @GetMapping("/list")
    public String list(){
        return "order-list...";
    }
}

Automatically generated management rules：
![image](https://user-images.githubusercontent.com/81564338/190290982-aed7a887-c997-4173-b70e-9214d008733f.png)

When I manually add a rule：
![image](https://user-images.githubusercontent.com/81564338/190291026-93f25eea-2fcf-41e0-9624-84778f107e74.png)

performance is inconsistent。

**Comment by hlcen66** [comment]
@yu199195 @yunlongn

**Comment by yunlongn** [comment]
Please modify it to English issue.
this is the rule configuration for divide.
![image](https://user-images.githubusercontent.com/38271111/190292690-de6b6b5a-7467-48ee-b56a-5430d11ec84c.png)

**Comment by yunlongn** [comment]
Please modify the title and previous comments to English. The rule editing page registered by the client is inconsistent with the new rule page. this is a problem. i will take a look

**Comment by hlcen66** [comment]
> Please modify the title and previous comments to English. The rule editing page registered by the client is inconsistent with the new rule page. this is a problem. i will take a look

ill do

**Comment by hlcen66** [comment]
It seems that the master branch has not fixed this problem。

**Comment by hlcen66** [comment]
> It seems that the master branch has not fixed this problem。

@yunlongn

**Comment by hlcen66** [comment]
![image](https://user-images.githubusercontent.com/81564338/190988607-9ebe6427-5951-4b9f-a921-5089aa0fe6f7.png)
![image](https://user-images.githubusercontent.com/81564338/190988722-b177f25d-992d-4ec2-ba9b-cd09c11facf5.png)

**Comment by yunlongn** [comment]
if you are mysql database
pls execute 
```
INSERT INTO `plugin_handle` VALUES ('1529402613204172742', '8', 'loadBalance', 'loadStrategy', 3, 2, 3, '{\"defaultValue\":\"roundRobin\",\"rule\":\"\"}', '2022-05-25 18:02:53', '2022-05-25 18:02:53');
```

**Comment by yunlongn** [comment]
@hlcen66

**Comment by yunlongn** [comment]
If you are not connecting to the `h2` database, please refer to adding `plugin_handle` data

**Comment by hlcen66** [comment]
> if you are mysql database pls execute
> 
> ```
> INSERT INTO `plugin_handle` VALUES ('1529402613204172742', '8', 'loadBalance', 'loadStrategy', 3, 2, 3, '{\"defaultValue\":\"roundRobin\",\"rule\":\"\"}', '2022-05-25 18:02:53', '2022-05-25 18:02:53');
> ```

ok
