### ISSUE TITLE
[Question] AK/SK of the Sign plugin be made public?

### ISSUE THREAD

**Issue by meta-ease** [apache/shenyu#3961]
### Question

![image](https://user-images.githubusercontent.com/12610839/190974908-6b58c45a-6cd5-4456-84b0-3dafe2dd9efb.png)
 
**I hope the appKey and appSecret can be implemented by myself** @yu199195

**Comment by yu199195** [comment]
pls in english

**Comment by yu199195** [comment]
maybe

**Comment by moremind** [comment]
you can do it by changing `SignUtils`
