### ISSUE TITLE
[BUG] Chinglish and grammar in Mind Map

### ISSUE THREAD

**Issue by xiazuojie** [apache/shenyu#3967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There are quite a few Chinglish and grammar errors in the "Mind Maps" of the [doc](https://shenyu.apache.org/docs/index), which undermines the professionalism of this project.  Please correct them (or let someone with better English skill write it).

Mind Maps -> Mind Map
Advantage -> Advantages
Support hot update -> Supports hot update
Gateway scaffolding -> Gateway framework
Characteristic -> Characteristics
responsive cross-language features -> reactive, cross-platform
Rich agreement -> Rich protocol support
Limiting -> Rate limiting
Fuse, downgrade -> circuit breaker, fallback

### Expected Behavior

No Chinglish and correct English grammar so non-Chinese audience can actually understand the Mind Map.

### Steps To Reproduce

1. read the Mind Map

### Environment

```markdown
ShenYu version(s):
```

**Comment by yu199195** [comment]
@xiazuojie  hi，Thank you very much for the suggestion, can you fix it in the readme and the website： https://github.com/apache/shenyu-website

**Comment by xiazuojie** [comment]
It's a [static image](https://github.com/apache/shenyu-website/blob/main/static/img/shenyu/activite/shenyu-xmind.png). Only someone with the original xmind file can fix it.

**Comment by yu199195** [comment]
> It's a [static image](https://github.com/apache/shenyu-website/blob/main/static/img/shenyu/activite/shenyu-xmind.png). Only someone with the original xmind file can fix it.

You can fix the doc. this xmind file，I will contact others to fix it.

**Comment by changanjennifer** [comment]
The remaining job is to modify "Chinglish and grammar error" of the mind-map: [static image] (https://github.com/apache/shenyu-website/blob/main/static/img/shenyu/activite/shenyu-xmind.png)?  
if so, please assign to me.
