### ISSUE TITLE
Shenyu admin startup error prompt

### ISSUE THREAD

**Issue by hlcen66** [apache/shenyu#3981]
### Question

When Shenyu admin is started, there will be an error message from the docs

![image](https://user-images.githubusercontent.com/81564338/191667069-65e60ff3-2416-4867-8689-19236e8fb805.png)

**Comment by hlcen66** [comment]
@yu199195 @yunlongn

**Comment by moremind** [comment]
this question about api document，but shenyu admin be free from the question
