### ISSUE TITLE
[Question] <Do you support RestFull style interfaces>

### ISSUE THREAD

**Issue by LBJWt** [apache/shenyu#3985]
### Question

Do you support RestFull style interfaces? like  /a/b/{id}

**Comment by moremind** [comment]
yes

**Comment by LBJWt** [comment]
> 
How do you accept parameters?
like
 `
 @ShenyuDubboClient(path = "/callback/result/{type}")
    @Override
    public ApiResponse callbackHandle(Map<String,Object> reqStr,String type) {


        return null;
    }
`

**Comment by LBJWt** [comment]
@moremind  this question please reply me ,thank you
