### ISSUE TITLE
[Question] There is no LoggingKafka in the PluginList->Logging menu

### ISSUE THREAD

**Issue by happyshelfan** [apache/shenyu#3997]
### Question

I downloaded the source code of version `2.5.0`, but I could not find the LoggingKafka menu. So I checked the `schema.sql`, there was no data about `loggingKafka` either in the `resource` table.

**Comment by moremind** [comment]
yes, I have checked mysql not exist

**Comment by moremind** [comment]
I will fix it right now.

**Comment by moremind** [comment]
this bug has finished, you can use the new SQL script or generate plugin resources on plugin-list page
