### ISSUE TITLE
On the secondary development of shenyu

### ISSUE THREAD

**Issue by hlcen66** [apache/shenyu#4002]
### Question

I have made some feature function modifications to Shenyu to meet my own business. Would you like to repackage the image and upload it to your own image warehouse? 

write Dockfile by myself？

@yu199195 @yunlongn @moremind

**Comment by moremind** [comment]
you can write Dockerfile by yourself

**Comment by hlcen66** [comment]
how to build a image.
![image](https://user-images.githubusercontent.com/81564338/192675698-d17972af-ae7f-490d-8f43-773b88df7701.png)

i run cmd  :  mvn clean package docker:build 

the result:

![Uploading image.png…]()



how i use the module shenyu-admin-dist to build shenyu-admin‘s  docker image.
