### ISSUE TITLE
While trying to register SpringCloud services, is it necessary to annotate @ShenyuSpringCloudClient in the Controller? 

### ISSUE THREAD

**Issue by sreeraksha** [apache/shenyu#4006]
### Question

Please confirm if its a mandate to use @ShenyuSpringCloudClient in SpringCloud services in order to register  to Shenyu API gateway? As this would require changes in multiple services.

**Comment by yu199195** [comment]
No， you can config in shenyu admin

**Comment by sreeraksha** [comment]
Could please also confirm if we can package shenyu-admin and shenyu-bootstrap into a war and deploy to weblogic?

**Comment by sreeraksha** [comment]
@yu199195 I tried configuring selector in Shenyu admin to access a client service called customer-service (which does not have @ShenyuSpringCloudClient or any shenyu dependencies) but doesn't seem to route the request. Kindly guide me. Thanks

I followed steps mentioned at https://shenyu.apache.org/docs/plugin-center/proxy/spring-cloud-plugin#252-selector-and-gray-config as below

Service is registered with Eureka 
<img width="752" alt="image" src="https://user-images.githubusercontent.com/30264507/192709517-ac450ba4-9e40-47cd-b534-f1c633fd2b71.png">
Configured selector as below
<img width="751" alt="image" src="https://user-images.githubusercontent.com/30264507/192709735-d8cc571f-3365-40a7-a033-8cbfef272a45.png">
when i try accessing it via eureka it works fine 
<img width="512" alt="image" src="https://user-images.githubusercontent.com/30264507/192710177-ec5a130b-6e08-4912-b1b0-db8ccc7acb7e.png">
But with shenyu endpoint it fails with code -106
<img width="512" alt="image" src="https://user-images.githubusercontent.com/30264507/192710399-3c676db1-fdfa-4b41-8267-8f35b09c88c1.png">

**Comment by homihq** [comment]
@sreeraksha do you mind sharing your code sample.

**Comment by uncarbon97** [comment]
you can easily configurate it in (http://localhost:9095/#/config/metadata)[http://localhost:9095/#/config/metadata] like:
![image](https://user-images.githubusercontent.com/75737767/204700525-be87bcf8-e1c6-4751-98c4-12424ffa5d60.png)
