### ISSUE TITLE
shenyu admin Configure multiple client service protocols

### ISSUE THREAD

**Issue by hlcen66** [apache/shenyu#4008]
### Question

I have two microservices, one is http service, and the other is spring cloud service. How can my shen admin register two protocol types?

1：http server && shenyu-admin config
![image](https://user-images.githubusercontent.com/81564338/192491384-33a4006f-6874-465c-ae49-36f90f730207.png)

![image](https://user-images.githubusercontent.com/81564338/192491757-a08c69a5-88dc-44f5-8e7c-508092686e53.png)

2：springCloud server && shenyu-admin config

![image](https://user-images.githubusercontent.com/81564338/192491511-22c273fa-d7a3-4827-9d9d-71f079b5d896.png)

![image](https://user-images.githubusercontent.com/81564338/192491923-0553834e-49bc-4666-9204-98ce81720420.png)

3：How to configure shenyu-admin to brace http service and springlcoud service

4：i read a doc, i test ,but it can not work 
https://shenyu.apache.org/zh/docs/user-guide/property-config/register-center-access#%E5%90%8C%E6%97%B6%E6%B3%A8%E5%86%8C%E5%A4%9A%E7%A7%8D%E6%9C%8D%E5%8A%A1%E7%B1%BB%E5%9E%8B

the doc describe is what i want ?

tell me how to do pls , thanks ,love you .

@yu199195 @yunlongn

**Comment by hlcen66** [comment]
@moremind

**Comment by moremind** [comment]
Do you use two register types? http and nacos? the register just for shenyu register, not microservices

**Comment by hlcen66** [comment]
> Do you use two register types? http and nacos? the register just for shenyu register, not microservices

for example,i have two business server ,one is http service ,another is springcloud ,
These two services are connected to shenyu admin.

shenyu-admin document example just write How to access each other.

**Comment by hlcen66** [comment]
> Do you use two register types? http and nacos? the register just for shenyu register, not microservices

for this :
![image](https://user-images.githubusercontent.com/81564338/192507024-c60f59f1-a24d-44c1-ae5e-db02ea235836.png)

its about client config registryType,support http、zookeeper、etcd、consul和nacos 。

now, my client one is http,two is cloud,shen-admin only one ,how i config the registryType of shenyu-admin to adapter (http && nacos)

**Comment by moremind** [comment]
this is for your service use shenyu-client register to shenyu-register, shenyu not support multi-protocol-client

**Comment by hlcen66** [comment]
> this is for your service use shenyu-client register to shenyu-register, shenyu not support multi-protocol-client

![image](https://user-images.githubusercontent.com/81564338/192513771-31c3c16f-15d9-4c8e-a320-3047f6a516ff.png)


the config is config in shenyu-admin or my business client server?

**Comment by hlcen66** [comment]
i want to confirm , now is like this:
![image](https://user-images.githubusercontent.com/81564338/192515544-954918fe-ec0f-44c9-a2ed-96707a51283d.png)


next ,i want to like this:
![image](https://user-images.githubusercontent.com/81564338/192515597-a44ae071-288e-4e6f-b3cc-8bc8d575ba53.png)


Is there no way to support it now?  

Do I have to build a shen-admin for order service and payment respectively??

@moremind @yunlongn

**Comment by hlcen66** [comment]
再画了一张图：
![image](https://user-images.githubusercontent.com/81564338/192519888-c635b51b-5a00-4aac-8edb-3dbb8a622a11.png)

**Comment by yunlongn** [comment]
You cannot use both registration methods at the same time.  
![image](https://user-images.githubusercontent.com/38271111/192530819-d66fe0b6-8df4-44cb-be6c-cf6f924c0e71.png)
You can have both services use http to register the service.

**Comment by hlcen66** [comment]
> You cannot use both registration methods at the same time. ![image](https://user-images.githubusercontent.com/38271111/192530819-d66fe0b6-8df4-44cb-be6c-cf6f924c0e71.png) You can have both services use http to register the service.

It means that all my http services and all my spring cloud services can only be mapped with two shenyu admins？

**Comment by yunlongn** [comment]
I don't think you understand what `shenyu-admin` does.
shenyu-bootstrap can call both nacos services and http services.

**Comment by yunlongn** [comment]
I think you can use `@ShenyuSpringCloudClient` way to add nacos service

**Comment by hlcen66** [comment]
> I don't think you understand what `shenyu-admin` does. shenyu-bootstrap can call both nacos services and http services.

ok,i will think it .

**Comment by yunlongn** [comment]
`registryType http, nacos` These two methods are just to notify the admin of the uri address of your application
