### ISSUE TITLE
[BUG] <mysql schema.sql>  

### ISSUE THREAD

**Issue by thuliumkyg** [apache/shenyu#4021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

init mysql

### Environment

```markdown
ShenYu version(master):
```

### Debug logs

1062 - Duplicate entry '1572620652359245824' for key 'plugin_handle.PRIMARY'

**Comment by moremind** [comment]
this bug has fixed

**Comment by moremind** [comment]
@thuliumkyg
