### ISSUE TITLE
Shenyu as a traffic gateway

### ISSUE THREAD

**Issue by hlcen66** [apache/shenyu#4025]
### Question

Hello, if I take Shenyu as a company level traffic gateway to forward requests to spring cloud gateway gateways of multiple downstream systems, can Shenyu support it?

like this:

![image](https://user-images.githubusercontent.com/81564338/193217429-11912b72-c1ac-408a-8d42-307ab8805a8b.png)

**Comment by hlcen66** [comment]
@yu199195 @yunlongn @moremind

**Comment by yunlongn** [comment]
`admin` add forwarding routes

**Comment by hlcen66** [comment]
> `admin` add forwarding routes

How to configure forwarding routes? the forwarding routes mean selector and rule ? it base on plugin ,but the spring cloud gateway can not resigtry to the shenyu。

Which proxy should I go to to configure the selector and rule？

i dont understand ,  Can you show me a screenshot ？

**Comment by yunlongn** [comment]
> > `admin` add forwarding routes
> 
> How to configure forwarding routes? the forwarding routes mean selector and rule ? it base on plugin ,but the spring cloud gateway can not resigtry to the shenyu。
> 
> Which proxy should I go to to configure the selector and rule？
> 
> i dont understand , Can you show me a screenshot ？

https://shenyu.apache.org/zh/docs/next/user-guide/admin-usage/selector-and-rule

**Comment by moremind** [comment]
first, why do you design? and if you can read shenyu document on https://shenyu.apache.org/docs/index/, you can use divide plugin.

**Comment by yunlongn** [comment]
If your `spring cloud gateway` is registered with `eureka`, then you can use `Proxy/springCloud` to connect to it

**Comment by hlcen66** [comment]
> If your `spring cloud gateway` is registered with `eureka`, then you can use `Proxy/springCloud` to connect to it , `new Selector`

i had try, the spring cloud gateway as a spring cloud service can registry into the shenyu ,but a new problem produce..
![image](https://user-images.githubusercontent.com/81564338/193436585-96c24669-8737-44df-970c-46244d21938c.png)


cloud gateway config :
![image](https://user-images.githubusercontent.com/81564338/193436516-2c0fc65b-754a-4144-b971-18dbaf8f8302.png)

so , the url by shenyu proxy is ：
http://localhost:9195/springcloud/order-server/order/list
 
but the gateway route url can not be a metadata .

when i ask url :
http://localhost:9195/springcloud/order-server/order/list

the debug result:
![image](https://user-images.githubusercontent.com/81564338/193436540-04b9cf81-2784-4210-99eb-47385d3b66f9.png)

![image](https://user-images.githubusercontent.com/81564338/193436564-7eac2b95-54fe-4514-bc73-6655791a067c.png)

so,how to forward the request to the gateway through shenyu, can you give me a demo? pls ,thanks

**Comment by hlcen66** [comment]
@moremind @yunlongn @yu199195

**Comment by yunlongn** [comment]
> @moremind @yunlongn @yu199195

you can add my wechat: liyunlongn

**Comment by yunlongn** [comment]
Please enable the `spring cloud` plugin and use the `spring cloud` proxy method

**Comment by hlcen66** [comment]
> Please enable the `spring cloud` plugin and use the `spring cloud` proxy method
1：spring cloud plugin had enable
2：the gateway can not use @ShenyuSpringCloudClient, how i use the proxy

you can write a cloud gateway registry into shenyu ,and user spring cloud proxy method to ask gateway's route url ,it can not work.
