### ISSUE TITLE
[Question] ShenyuDubboService, but `IllegalArgumentException: Annotation must not be null`

### ISSUE THREAD

**Issue by gMan1990** [apache/shenyu#4031]
### Question

https://github.com/apache/shenyu/blob/8c4c530206e36be531fed7a323025c5cc592af2b/shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/annotation/impl/DubboClassMultiParamServiceImpl.java#L35

```text
java.lang.IllegalArgumentException: Annotation must not be null
	at org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationPostProcessor.processScannedBeanDefinition(ServiceAnnotationPostProcessor.java:334) ~[dubbo-3.0.8.jar:3.0.8]
```

```text
org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationPostProcessor#processScannedBeanDefinition

Annotation service = findServiceAnnotation(beanClass);

    private final static List<Class<? extends Annotation>> serviceAnnotationTypes = asList(
            // @since 2.7.7 Add the @DubboService , the issue : https://github.com/apache/dubbo/issues/6007
            DubboService.class,
            // @since 2.7.0 the substitute @com.alibaba.dubbo.config.annotation.Service
            Service.class,
            // @since 2.7.3 Add the compatibility for legacy Dubbo's @Service , the issue : https://github.com/apache/dubbo/issues/4330
            com.alibaba.dubbo.config.annotation.Service.class
    );
```

`findServiceAnnotation` return `null` because `serviceAnnotationTypes`

**Comment by leopardrota** [comment]
https://github.com/apache/shenyu/pull/3838#discussion_r985434758

**Comment by AlbumenJ** [comment]
Dubbo use `org.apache.dubbo.common.utils.AnnotationUtils#findAnnotation(java.lang.reflect.AnnotatedElement, java.lang.Class<A>)` for spring 3.2.x compatible purpose.

**Comment by dragon-zhang** [comment]
> Dubbo use `org.apache.dubbo.common.utils.AnnotationUtils#findAnnotation(java.lang.reflect.AnnotatedElement, java.lang.Class<A>)` for spring 3.2.x compatible purpose.

The `@AlisFor` is from spring 4.2+

**Comment by AlbumenJ** [comment]
> The `@AlisFor` is from spring 4.2+, maybe `dubbo` needs to be more compatible with this?

https://github.com/apache/dubbo/pull/10737
