### ISSUE TITLE
[Question] Using shenyu-plugin-ratelimiter can't obtain client real ip

### ISSUE THREAD

**Issue by winneryong** [apache/shenyu#4046]
### Question

ENV: nginx + shenyu-bootstrap

1.Nginx Reverse Proxy, Conf segement :
location /http {
        proxy_pass http://127.0.0.1:9195/http;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header REMOTE-HOST $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

Nginx access log:
111.204.176.185 - - [08/Oct/2022:14:55:48 +0800] "GET /http/api/mock/search/v1/myip HTTP/1.1" 200 372 "https://example.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
111.204.176.185 - - [08/Oct/2022:15:13:28 +0800] "GET /http/api/mock/search/v1/s?t=domain&q=123213123213 HTTP/1.1" 429 74 "https://example.com/content?index=1&value=123213" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"

2. ShenYu Rule config:
![image](https://user-images.githubusercontent.com/665637/194698274-032adc2f-c5c6-4ba4-8a56-144563cfbb66.png)

3. request log:
![image](https://user-images.githubusercontent.com/665637/194698409-c727f967-b1fc-463b-abe1-2fbba6f63105.png)

4. Redis keys:
![image](https://user-images.githubusercontent.com/665637/194698293-c8635118-a321-4b2c-a1d2-4a7f136dbb6a.png)

In redis key , ip part is **127.0.0.1**

**Comment by yu199195** [comment]
see this : https://shenyu.apache.org/zh/docs/developer/custom-parsing-ip-and-host

**Comment by winneryong** [comment]
> see this : https://shenyu.apache.org/zh/docs/developer/custom-parsing-ip-and-host
> 
> this keyName Isn't it up to you to fill out your own？

OK, thanks!
I thought RemoteAddrKeyResolver could also get the client IP of X-Forwarded-For
