### ISSUE TITLE
[BUG] Found a problem when using Sign plugin

### ISSUE THREAD

**Issue by Once2012** [apache/shenyu#4049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1）When I add an App with 2 interfaces in BasicConfig > Authentication > Add，It's OK（Add 2 interface in one step）
![image](https://user-images.githubusercontent.com/19165279/194741071-e71b9282-8446-408f-82ef-10eff4a28ec7.png)

2）But when I want to add new interface in an exisiting App with one interface，then it report error（Add one interface then append another interface use edit operation）
![image](https://user-images.githubusercontent.com/19165279/194741318-7ae04406-1dda-45e4-a177-1f6b82de2950.png)
![image](https://user-images.githubusercontent.com/19165279/194741399-3385e4a2-4864-41b0-8037-b47cc00694f5.png)

I need help，Thanks

### Expected Behavior

How to append interfaces in an exsiting HMAC App record

### Environment

```markdown
ShenYu version(s):2.5.0
```

### Debug logs

Http request F12 info：
![image](https://user-images.githubusercontent.com/19165279/194741439-34abdd13-f890-4554-b924-2c76ebfbce4f.png)

**Comment by li-keguo** [comment]
Can you fix it?

**Comment by tian-pengfei** [comment]
![image](https://user-images.githubusercontent.com/42602026/201810275-9746fc12-46d5-4b4c-adeb-d06c22c28f42.png)

![image](https://user-images.githubusercontent.com/42602026/201810311-a8d5496b-3f5a-449a-8a17-11261252ee74.png)

Missing enabled field
