### ISSUE TITLE
[Task] refinement ShenYu Admin

### ISSUE THREAD

**Issue by zhc00** [apache/shenyu#4055]
### Description

I propose to refine the API and API document of ShenYu Admin. the key is that let it follow the OpenAPI 3.0 specification completely. 

### Task List

1. API document, there are many meaningless descriptions.
1. unify the message of Response to `success` or `query success` when querying successfully. I see we unified most queries to `query success.
1. Missing mode detail in Response. For example, `ShenyuAdminResult` missed the details of the data.
1. refactor the structure of `/selector/list/search` and `/rule/list/search`.  Let it be like `/selector` or `/rule`
2. fix `/selector` and `/rule` missing `required` symbol in `pluginId` and `selectorId`.
1. return **`200 ok`** when the resource is not found in `GET /selector/{id}` or `GET /rule/{id}`.

**Comment by zhc00** [comment]
This proposal is important. It will make the UI broken.
So welcome to discuss this topic with me.

**Comment by homihq** [comment]
I can volunteer on this one.

**Comment by mahaitao617** [comment]
please assign 4 、5 to me,ths
