### ISSUE TITLE
[Question] When the proxy service is offline or times out, the shenyugateway reports exception 500

### ISSUE THREAD

**Issue by yzy2015** [apache/shenyu#4059]
### Question

shenyu version: 2.5.0

shenyu-examples-http
Request:
POST http://localhost:9195/http/shenyu/client/timeout
Accept: application/json
Content-Type: application/json

Response:
{
  "code": 500,
  "message": "Internal Server Error"
}
![image](https://user-images.githubusercontent.com/15868072/194752192-18601743-1e95-45b8-868d-74b40aa0bfb8.png)

**when random Strategy is  current or failover then Response code 500
Should a more friendly prompt be returned**

**Comment by moremind** [comment]
what happens?

**Comment by yzy2015** [comment]
1.when random Strategy is current 
The actual exception is "reactor.core.Exceptions$RetryExhaustedException".
and I think RetryBackoffSpec need to add onRetryExhaustedThrow

2.when random Strategy is failover 
The actual exception is "org.apache.shenyu.common.exception.ShenyuException: Can not find healthy upstream url after failover".
This exception is not handled.GlobalErrorHandler handles 500 by default

**Comment by moremind** [comment]
> 

yes, I think you are right, you can fix it? if you can't, I will do it.

**Comment by moremind** [comment]
> 1.when random Strategy is current The actual exception is "reactor.core.Exceptions$RetryExhaustedException". and I think RetryBackoffSpec need to add onRetryExhaustedThrow
> 
> 2.when random Strategy is failover The actual exception is "org.apache.shenyu.common.exception.ShenyuException: Can not find healthy upstream url after failover". This exception is not handled.GlobalErrorHandler handles 500 by default

yes, I think you are right, you can fix it? if you can't, I will do it.

**Comment by moremind** [comment]
the result maybe: 
```
{
  "code": 408,
  "message": "Request Timeout"
}
```

**Comment by moremind** [comment]
second question: 
```
{
  "code": 503,
  "message": "Can not find healthy upstream url after failover!"
}
```

**Comment by yzy2015** [comment]
> > 1.when random Strategy is current The actual exception is "reactor.core.Exceptions$RetryExhaustedException". and I think RetryBackoffSpec need to add onRetryExhaustedThrow
> > 2.when random Strategy is failover The actual exception is "org.apache.shenyu.common.exception.ShenyuException: Can not find healthy upstream url after failover". This exception is not handled.GlobalErrorHandler handles 500 by default
> 
> yes, I think you are right, can you fix it? if you can't, I will do it.

Wait for you, and thanks
