### ISSUE TITLE
[BUG] Shenyu-Admin > BasicConfig > Plugin list page 2 cannot display

### ISSUE THREAD

**Issue by Once2012** [apache/shenyu#4072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I do not know when to start, the second page of  BasicConfig > Plugin cannot be displayed（empty white page），but the first and third page is OK（Page size is 12）

F12 of Chrome show this:
![1665555847736](https://user-images.githubusercontent.com/19165279/195266985-98990f57-d14a-4be6-93de-cb855529f4f9.png)

### Environment

```markdown
ShenYu version(s):2.5.0
```

**Comment by Once2012** [comment]
And when I open Request plugin，all page of Shenyu-Admin can not display，so I have to close the Request plugin by modifing Database table (plugin.enable => 0）.
The Request plugin is in Plug in list Page 2，maybe it cause the problem?

The stacktrace of Shenyu-Admin is below:
![image](https://user-images.githubusercontent.com/19165279/195269103-ea1e1af1-e0df-44fe-ace5-3bcc2edeed13.png)

**Comment by yu199195** [comment]
can you execute  right SQL ？ about some plugin~
