### ISSUE TITLE
[BUG] <title>log output for each request：[tcp] resources will use a new LoopResources: DefaultLoopResources {prefix=shenyu, daemon=true, selectCount=1, workerCount=16},the previous LoopResources will be disposed

### ISSUE THREAD

**Issue by gongzhibo** [apache/shenyu#4082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

log output for each request：
[tcp] resources will use a new LoopResources: DefaultLoopResources {prefix=shenyu, daemon=true, selectCount=1, workerCount=16},the previous LoopResources will be disposed

### Expected Behavior

do not output

### Environment

```markdown
ShenYu version(s):2.4.3
```

### Debug logs

[tcp] resources will use a new LoopResources: DefaultLoopResources {prefix=shenyu, daemon=true, selectCount=1, workerCount=16},the previous LoopResources will be disposed

**Comment by dragon-zhang** [comment]
It had been fixed by https://github.com/apache/shenyu/pull/3314 . as for `2.4.3`, can you solve the problem by modifying the source code?

**Comment by dragon-zhang** [comment]
If there is still a problem, please reopen this issue. @gongzhibo
