### ISSUE TITLE
[BUG] <shenyu use etcd sync data report io.vertx.core.VertxException: Thread blocked>

### ISSUE THREAD

**Issue by misaya295** [apache/shenyu#4088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

shenyu use etcd sync data report io.vertx.core.VertxException: Thread blocked
![image](https://user-images.githubusercontent.com/45778734/195970546-68336cce-35d6-446b-9456-9ebbc74e52ca.png)

this is a bug in jectd, while using getkey in watch will report io.vertx.core.VertxException: Thread blocked.
https://github.com/etcd-io/jetcd/issues/1089

### Expected Behavior

sync data success

### Steps To Reproduce

1.  use ectd
2. sync data in web

### Environment

```markdown
ShenYu version(s):master
```

### Anything else?

assgin to me,pls. I will fix it.

**Comment by yu199195** [comment]
hi， this problem solved?

**Comment by misaya295** [comment]
> hi， this problem solved?

 Not yet,I am resolving.
