### ISSUE TITLE
[Question] Can't find the config entrance for mock plugin.

### ISSUE THREAD

**Issue by vnvn** [apache/shenyu#4092]
### Question

When using the newest 2.5.0 version and after enabled mock plugin in Basic Config --> Plugin, logout shenyu-admin and re-login, I could not find the config entrance under PluginList menu, which supposed to be displayed. Can somebody to check this, thanks.

I'm using a docker image for docker-admin, and below is the inspect info:
docker inspect 462009138b69
[
    {
        "Id": "sha256:462009138b69e86075773b405ecb553e8e40be0ac95fd6f5605197de437b8071",
        "RepoTags": [
            "apache/shenyu-admin:2.5.0"
        ],
        "RepoDigests": [
            "apache/shenyu-admin@sha256:4f178ea8ae35d45d82c4aaf7dbcdd21bac3ec6eaa3ed4a9deefacf699b2763eb"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2022-09-02T15:53:20.296019355Z",
        .......
}]

![image](https://user-images.githubusercontent.com/5524580/196028923-f9ba7839-f227-4fcb-b5b1-ed0bb8d967e6.png)

**Comment by yu199195** [comment]
What do you use to database in shenyu-admin？

**Comment by vnvn** [comment]
> What do you use to database in shenyu-admin？

MySql 5.7

**Comment by yu199195** [comment]
This may be caused by the lack of menu privileges, you can configure it yourself.

**Comment by skyding228** [comment]
you have to add it manually. click here.
![image](https://user-images.githubusercontent.com/3915919/219259087-d422ac7e-722a-4dda-9a01-14c3723576ba.png)
