### ISSUE TITLE
Sentinel熔断配置参数错误

### ISSUE THREAD

**Issue by malinGH** [apache/shenyu#4099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![4441665997271_ pic](https://user-images.githubusercontent.com/40853744/196156922-c324304a-38f0-4488-9861-091ec6fd674c.jpg)
数据库初始化参数错误，导致Sentinel设置熔断统计时长无法生效，一直默认1000ms，源码中序列化字段不对应所致

### Expected Behavior

<img width="1117" alt="WeChat133e1e438687a8d4cd5b8fa630e12ea6" src="https://user-images.githubusercontent.com/40853744/196157283-b5ded477-f4c1-4b7f-82df-331d3de4c65b.png">
修改初始化数据此字段可修正

### Environment

```markdown
ShenYu version(s):
```

**Comment by malinGH** [comment]
version 2.4.1，2.5.0版本文档依旧错误

**Comment by moremind** [comment]
thanks, the documentation will rewrite,but the data is right, the parameter is 1000ms, you can config 1 in shenyu-admin, as follows:
![image](https://user-images.githubusercontent.com/20184263/196205326-5d5ffd5d-5f54-4af9-b9f9-9e9028ba5f14.png)
