### ISSUE TITLE
[Task] 版本升级用户密码加密方式更新，导致升级后登录失败

### ISSUE THREAD

**Issue by liukun321** [apache/shenyu#4109]
### Description

网关数据库使用方私有化部署，加密后的密码存在数据库中，升级后用户身份校验时，密码加密算法变更，导致无法登录；

### Task List

1 前后端用户登录密码传输做加密处理；
2 解密后，再次加密与数据库中密文密码做对比；
3 保持用户密码检验前的加密方式不变；

**Comment by yu199195** [comment]
pls in english
