### ISSUE TITLE
[BUG] <title>Read the garbled routing information in Zookeeper

### ISSUE THREAD

**Issue by gongzhibo** [apache/shenyu#4124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Uploading f4207569-87e3-4d91-9143-b9b7ca8a6329.jpeg…]()

### Environment

```markdown
ShenYu version(s):2.5.0
```

### Anything else?

org.apache.shenyu.common.utils.GsonUtils#fromJson(java.lang.String, java.lang.Class<T>)

**Comment by gongzhibo** [comment]
![f4207569-87e3-4d91-9143-b9b7ca8a6329](https://user-images.githubusercontent.com/19222385/197137727-6d15e61b-daf8-4e09-9e2f-9a00066cf3ed.jpeg)

**Comment by gongzhibo** [comment]
The data of Zookeeper is written in garbled code, but it can be read correctly when using version 2.4.3

**Comment by yu199195** [comment]
What do you think is the cause of the problem and can you fix it?
