### ISSUE TITLE
[BUG] <title>The matching priority of routing rules according to the number of conditions is not accurate, and they should be sorted first

### ISSUE THREAD

**Issue by gongzhibo** [apache/shenyu#4131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The routing is wrong. The least sorted one is not selected

### Expected Behavior

The routing is wrong. The least sorted one is not selected

### Environment

```markdown
ShenYu version(s):
```

### Anything else?

![jePizQzeqV](https://user-images.githubusercontent.com/19222385/197674660-4a060d8c-6692-4e5f-a3fc-c8b6148e3147.jpg)
org.apache.shenyu.plugin.base.AbstractShenyuPlugin#manyMatchSelector

**Comment by yu199195** [comment]
can you modify this issue title？  and try fix it ？

**Comment by gongzhibo** [comment]
> can you modify this issue title？ and try fix it ？

OK

**Comment by leopardrota** [comment]
Is this a bug?  The param `filterCollectors` size 3 is converted to `collect` size 2. It indicates 2 elements in `filterCollectors` have the same `sort` and are put into one Map.Entry.
Are there any mistakes in my understanding?

**Comment by yu199195** [comment]
@leopardrota Should first take the most matching conditions, if the same, then sort according to sort.

**Comment by gongzhibo** [comment]
For example, a single addrFor example, a single address has the highest priority, but it only matches one condition of the url.ess has the highest priority, but it only matches one condition of the url.

**Comment by gongzhibo** [comment]
For example, a single address has the highest priority, but it only matches one condition of the url.

**Comment by yu199195** [comment]
> For example, a single address has the highest priority, but it only matches one condition of the url.

the alreay sort in  List

**Comment by prFor** [comment]
What needs to be dealt with here is the and condition. If the number of and conditions is the same and is matched at the same time,it will be sorted by the sort field.

**Comment by prFor** [comment]
There are three cases: `All Or`, `All And`, `Or And with`. 
`All Or`: The value of sort is 0. 
`All And`: The value of sort is determined by the number of conditions. The more conditions there are, the more sort equals the number of conditions.
`Or And with`: is the common property of the above two cases. The and condition is matched first.
The last `groupBy` will merge the ones with the same sort.  Finally, sorting is done according to the `sort` field of `selectData`.

**Comment by gongzhibo** [comment]
> > For example, a single address has the highest priority, but it only matches one condition of the url.
> 
> the alreay sort in List

request URL ： /test/abc/1

1、sort 1  /test/abc/1  two condition 
2、sort 2 /test/**    one condition 
3、sort 3 /test/abc/** two condition 

The result of this match is/test/* *, but the result I want is/test/abc/1

**Comment by pandaapo** [comment]
> The last `groupingBy` will merge the ones with the same sort. Finally, sorting is done according to the `sort` field of `SelectorData`.

@prFor I want to know the meaning of the `sort` field of `SelectorData`. How or where is this field value assigned? Thanks.

**Comment by pandaapo** [comment]
> Should first take the most matching conditions, if the same, then sort according to sort.

@yu199195 Are you describing the current logic in source code? https://github.com/apache/shenyu/blob/04f650db6c070979ba98f395c641dad4ca4a4079/shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java#L192-L202, Here is taking the most matching conditions firstly.
https://github.com/apache/shenyu/blob/04f650db6c070979ba98f395c641dad4ca4a4079/shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java#L203, then here is sorted by the `sort` field of `SelectorData`.

**Comment by pandaapo** [comment]
> request URL ： /test/abc/1
> 
> 1、sort 1 /test/abc/1 two condition 
> 2、sort 2 /test/** one condition 
> 3、sort 3 /test/abc/** two condition
> The result of this match is/test/* *, but the result I want is/test/abc/1

@gongzhibo I don't know how to produce the result you said. According to the logic of current source code, https://github.com/apache/shenyu/blob/04f650db6c070979ba98f395c641dad4ca4a4079/shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java#L192-L201, this logic will split 3 url into 2 groups. Group 1 contains url that matches two conditions, so it contains `/test/abc/1` and `/test/abc/**`. Group 2 contains url that matches one condition, so it contains `/test/**`.
https://github.com/apache/shenyu/blob/04f650db6c070979ba98f395c641dad4ca4a4079/shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java#L202, here will get the Group 1.
https://github.com/apache/shenyu/blob/04f650db6c070979ba98f395c641dad4ca4a4079/shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java#L203, here will get the min sort in Group 1, so the result will be `/test/abc/1` whose sort is 1(<3) as you want.

So, Do I misunderstand something anywhere?

**Comment by gongzhibo** [comment]
> > request URL ： /test/abc/1
> > 1、sort 1 /test/abc/1 two condition
> > 2、sort 2 /test/** one condition
> > 3、sort 3 /test/abc/** two condition
> > The result of this match is/test/* *, but the result I want is/test/abc/1
> 
> @gongzhibo I don't know how to produce the result you said. According to the logic of current source code,
> 
> https://github.com/apache/shenyu/blob/04f650db6c070979ba98f395c641dad4ca4a4079/shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java#L192-L201
> 
> , this logic will split 3 url into 2 groups. Group 1 contains url that matches two conditions, so it contains `/test/abc/1` and `/test/abc/**`. Group 2 contains url that matches one condition, so it contains `/test/**`.
> https://github.com/apache/shenyu/blob/04f650db6c070979ba98f395c641dad4ca4a4079/shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java#L202
> 
> , here will get the Group 1.
> https://github.com/apache/shenyu/blob/04f650db6c070979ba98f395c641dad4ca4a4079/shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java#L203
> 
> , here will get the min sort in Group 1, so the result will be `/test/abc/1` whose sort is 1(<3) as you want.
> So, Do I misunderstand something anywhere?
My example has some problems. However, it is wrong to add the number parameter of the upper condition for some cases. I don't think the rule of increasing the number of conditions is necessary for routing

**Comment by pandaapo** [comment]
> My example has some problems. However, it is wrong to add the number parameter of the upper condition for some cases. I don't think the rule of increasing the number of conditions is necessary for routing

@gongzhibo You'd better give a correct example. It can help others including me understand your problems and what is wrong with this logic.

**Comment by pandaapo** [comment]
> > My example has some problems. However, it is wrong to add the number parameter of the upper condition for some cases. I don't think the rule of increasing the number of conditions is necessary for routing
> 
> @gongzhibo You'd better give a correct example. It will help others including me understand your problem and what is wrong with the logic of code.

**Comment by gongzhibo** [comment]
> > My example has some problems. However, it is wrong to add the number parameter of the upper condition for some cases. I don't think the rule of increasing the number of conditions is necessary for routing
> 
> @gongzhibo You'd better give a correct example. It will help others including me understand your problem and what is wrong with the logic of source code.

request URL ： /test/abc/1
1、sort 1 /test/abc/1 one condition
2、sort 2 /test/** two condition
3、sort 3 /test/abc/** two condition
The result of this match is/test/* *, but the result I want is/test/abc/1

**Comment by pandaapo** [comment]
> request URL ： /test/abc/1 1、sort 1 /test/abc/1 one condition 2、sort 2 /test/** two condition 3、sort 3 /test/abc/** two condition The result of this match is/test/* *, but the result I want is/test/abc/1

Thank you for your example. So, now there are some new questions to me. When and where is the `conditionList` field of `SelectorData` assigned? What is the meaning of this field? Similarly, what is the meaning of the `sort` field of `SelectorData`?
I think making these problems clear will help to decide how to solve the issue finally.
