### ISSUE TITLE
[Question] The client requests the gateway

### ISSUE THREAD

**Issue by zhuang0928** [apache/shenyu#4134]
### Question

Does the client request gateway only support http? Support for other protocols？ such as grpc

![image](https://user-images.githubusercontent.com/16079256/197982170-0c31df7f-b175-4c85-8630-c9bba3c2f235.png)

**Comment by KevinClair** [comment]
Gateway support `grpc`, see [gRPC](https://shenyu.apache.org/docs/user-guide/grpc-proxy/)

**Comment by zhuang0928** [comment]
您好，你发的邮件已收到，谢谢！庄健明

**Comment by zhuang0928** [comment]
How do I extend requests from other protocols? Such as directly using dubbo requests

**Comment by KevinClair** [comment]
I don't understand you.`Shenyu` also support dubbo.
