### ISSUE TITLE
[BUG] <shenyu-examples-grpc> resources/proto file Missing code submission

### ISSUE THREAD

**Issue by zhuang0928** [apache/shenyu#4135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/16079256/197983848-5cd4502d-e215-4380-a2c0-18c9e9243492.png)

### Expected Behavior

[complete documents](javascript:;)

### Environment

```markdown
ShenYu version(s):V2.5.1-SNAPSHOT
```

### Debug logs

no

### Anything else?

not

**Comment by KevinClair** [comment]
Build your project.

**Comment by wulangcode** [comment]
```
mvn clean install -Dmaven.javadoc.skip=true -B -Drat.skip=true -Djacoco.skip=true -DskipITs -DskipTests
```

**Comment by moremind** [comment]
use maven plugin to build your project.
![image](https://user-images.githubusercontent.com/20184263/199729915-5c508742-5d58-4402-a104-85d94fbcf9fe.png)
