### ISSUE TITLE
[BUG] <shenyu-admin-front>unable to remove the jwt rule handle

### ISSUE THREAD

**Issue by tian-pengfei** [apache/shenyu#4142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I set it before，I cant remove jwt rule handle

![image](https://user-images.githubusercontent.com/42602026/198252718-8a224d9f-9ecd-4d71-835c-e51cc47e1bd9.png)

I  cant remove  jwt rule handle
![image](https://user-images.githubusercontent.com/42602026/198253620-8458ba37-a468-4cde-9dbe-8a8593ea1036.png)

### Expected Behavior

It can be removed

### Environment

```markdown
ShenYu version(shenyu-master):
```

**Comment by QinZiWeiS** [comment]
Hello，Do you mean that no error will be reported when handler is removed?

**Comment by tian-pengfei** [comment]
yes ,but I am not sure that is reasonable

> Hello，Do you mean that no error will be reported when handler is removed?

**Comment by QinZiWeiS** [comment]
> yes ,but I am not sure that is reasonable
> 
> > Hello，Do you mean that no error will be reported when handler is removed?

Yes, because this is a required field, it will be treated as an incorrect data type after its input is deleted

**Comment by tian-pengfei** [comment]
> > yes ,but I am not sure that is reasonable
> > > Hello，Do you mean that no error will be reported when handler is removed?
> 
> Yes, because this is a required field, it will be treated as an incorrect data type after its input is deleted

But the initial state is empty.  I mean if you didnt set it ,it is empty.  I think it is a  bit of a contradiction

**Comment by QinZiWeiS** [comment]
> > Yes, because this is a required field, it will be treated as an incorrect data type after its input is deleted
> 
> But the initial state is empty. I mean if you didnt set it ,it is empty. I think it is a bit of a contradiction

OK，Thank for your suggest

**Comment by QinZiWeiS** [comment]
> > Yes, because this is a required field, it will be treated as an incorrect data type after its input is deleted
> 
> But the initial state is empty. I mean if you didnt set it ,it is empty. I think it is a bit of a contradiction

OK，Thank for your suggest

> > > Yes, because this is a required field, it will be treated as an incorrect data type after its input is deleted
> > 
> > 
> > But the initial state is empty. I mean if you didnt set it ,it is empty. I think it is a bit of a contradiction
> 
> OK，Thanks for your suggest

I'm going to optimize it.

**Comment by tian-pengfei** [comment]
In addition, this filed is a required ,is it  reasonable?
