### ISSUE TITLE
[BUG] <bootstrap-A request to bootstarp-B will return 404 not found> 

### ISSUE THREAD

**Issue by misaya295** [apache/shenyu#4154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1.Two sets of shenyu,shenyu-A and shenyu-B.
2.Configure divide in Shenyu-A and shenyu-B.
3.Request bootstrap-B through boostrap-A.
4.return 404 page not found in bootstrap-A.

### Expected Behavior

response right

### Environment

```markdown
ShenYu version(s):2.5.0+
```

**Comment by moremind** [comment]
do you descript your config, plugin...

**Comment by misaya295** [comment]
> do you descript your config, plugin...

use divide like these

**Comment by misaya295** [comment]
> do you descript your config, plugin...

use divide like

1.shenyu-Bootstrap A

![image](https://user-images.githubusercontent.com/45778734/199732010-10242559-5a02-42c6-b398-e7388e5f6ec6.png)



2.shenyu-Bootstrap B
![image](https://user-images.githubusercontent.com/45778734/199731418-94b5951a-2dfd-4358-b4c6-e5ce67601990.png)

3. resquet shenyu-bootstrap:9195/test

4.return 404 page not found

**Comment by moremind** [comment]
config ip:port

**Comment by misaya295** [comment]
> config ip:port

I use ip:port in fact,but it did not word.
