### ISSUE TITLE
[BUG]  Dubbo example not work in most "SNAPSHOT version",caused by wrong verion number.  be carefule to set the verison number.

### ISSUE THREAD

**Issue by zhouyao1994** [apache/shenyu#4158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

shenyu-examples-dubbo can not be invoke, shenyu-examples-dubbo can not be register in shenyu admin

you can fllow the step to repeat it.
1. check out github tag v2.5.0
2. start shenyu admin
3. start shenyu bootstrap
4. start shenyu-examples-dubbo

and postman not work

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/5468589/200101767-bd654329-33cb-4d55-9d43-18b7b278b738.png">

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/5468589/200101975-504ca547-d250-4ac6-bf7a-fec90d578b6e.png">

### Expected Behavior

1. shenyu-examples-dubbo ca be invoke
2. shenyu-examples-dubbo be registered in shenyu admin
3. postman to proxy dubbo is ok,like the 2nd graph.
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/5468589/200102364-dc92d966-3b8d-45e2-8181-27bda0eab8c1.png">

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/5468589/200102372-6da6dbed-550c-4b4a-9879-6bbecb56ce32.png">

### Steps To Reproduce

mac os ,java 8, v2.5.0

1. check out github tag v2.5.0
2. start shenyu admin
3. start shenyu bootstrap
4. start shenyu-examples-dubbo

i have debug in ApacheDubboServiceBeanListener.jave find "onApplicationEvent" not be runed
so the solution is set the correct version number will be ok: 2.5.0-SNAPSHOT--->  2.5.0  

so be carefule to set the verison number.

### Environment

```markdown
ShenYu version(s):mac os ,java 8, v2.5.0
```

### Anything else?

be carefule to set the packege verison number.

make sure all pacekge can be find in maven

**Comment by KevinClair** [comment]
Thanks for your report, can you try it again with branch 'master'.I think this problem maybe had been fixed in branch 'master'.

**Comment by zhouyao1994** [comment]
> Thanks for your report, can you try it again with branch 'master'.I think this problem maybe had been fixed in branch 'master'.

i tryed the master branch. but the default setting not work yet.
the request is always pending,
mybe the dubbo plugin version(3.1.1)  not the the dubbo client version used by example is (2.7.15)

not work
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/5468589/200216466-43ca72a3-46f3-483e-b9a8-987bae0d0cf2.png">

dubbo plugin version is  :
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/5468589/200216550-87558b05-5b4e-4baf-be11-3981824ad938.png">

client version:
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/5468589/200216596-29744530-35aa-4084-acb6-f13e6d01af10.png">

error message:
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/5468589/200216681-66d8f495-ddd6-4f4d-be34-89f98b607dbf.png">

**Comment by dengliming** [comment]
This is probably because we forgot to change the version number of example when we released it. If you want to use v2.5.0. just set the example version to 2.5.0.

**Comment by zhouyao1994** [comment]
check out the version of 2.5.0 will solve this problem
