### ISSUE TITLE
[BUG] The location of text and input  are reversed

### ISSUE THREAD

**Issue by tian-pengfei** [apache/shenyu#4177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/42602026/201449827-b6fcac9f-6ef8-4bc1-9410-b2592d894cdc.png)

The location of text and input are reversed
### Expected Behavior

![image](https://user-images.githubusercontent.com/42602026/201449882-5457f2f8-3621-4394-8b1a-dddcdf0cb98d.png)

The picture from  [shenyu-doc](https://shenyu.apache.org/zh/docs/plugin-center/proxy/spring-cloud-plugin)

### Environment

```markdown
ShenYu version(s): master
```

**Comment by KevinClair** [comment]
Is this a `dashboard` problem?

**Comment by tian-pengfei** [comment]
> Is this a `dashboard` problem?

I guess so

**Comment by tian-pengfei** [comment]
@gentlehao ,Can you check it? please
