### ISSUE TITLE
[BUG] The code of global plugin is set incorrectly

### ISSUE THREAD

**Issue by liukun321** [apache/shenyu#4182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The code of global plugin equals 5

### Expected Behavior

The code of global plugin equals 0

### Steps To Reproduce

The code of global plugin need to make sure that the sort comes before other the plug-ins

### Environment

```markdown
ShenYu version(s):2.5.0
```

### Debug logs

org.apache.shenyu.plugin.divide.DividePlugin#doExecute

` ShenyuContext shenyuContext = exchange.getAttribute(Constants.CONTEXT);
        assert shenyuContext != null;`
        
if the code of global plugin equals 5,the code of divide may be small than 5

### Anything else?

null

**Comment by yu199195** [comment]
now , the divide plugin  Isn't it bigger than 5？
>if the code of global plugin equals 5,the code of divide may be small than 5

**Comment by liukun321** [comment]
> now , the divide plugin Isn't it bigger than 5？
> 
> > if the code of global plugin equals 5,the code of divide may be small than 5

no, Plug-in sorting depends on two attributes，code of PluginEnum and sorted of Plugin, The sorted value can be changed on the admin platform,To prevent other plug-ins from being executed before global, ensure that the global plug-in order is minimal

**Comment by yu199195** [comment]
can you fix it？  mybe global plugin is  -1 or  0 ？
