### ISSUE TITLE
[BUG] update logging plugin name error

### ISSUE THREAD

**Issue by liukun321** [apache/shenyu#4183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

UPDATE plugin SET name = 'LoggingConsole' WHERE name = 'logging';

### Expected Behavior

UPDATE plugin SET name = 'loggingConsole' WHERE name = 'logging';

UPDATE resource SET title = 'loggingConsole', name = 'loggingConsole', component = 'loggingConsole', url = REPLACE(url, 'logging', 'loggingConsole') WHERE title = 'logging';

UPDATE resource SET perms = REPLACE(perms, 'logging', 'loggingConsole') WHERE perms LIKE 'plugin:logging%';

### Steps To Reproduce

In the class of PluginEnum, name of LOGGING_CONSOLE is loggingConsole,but in upgrade sql, name is LoggingConsole,so loggingConsole plugin will never effect

### Environment

```markdown
ShenYu version(s):2.5.0
```

### Debug logs

null

### Anything else?

null

**Comment by yu199195** [comment]
maybe is  UPDATE plugin SET name = 'loggingConsole' WHERE name = 'logging';

if 2.4.3-upgrade-2.5.0
