### ISSUE TITLE
[Question] The database connection has been closed, but still exists in the connection pool

### ISSUE THREAD

**Issue by liukun321** [apache/shenyu#4184]
### Question

The database connection has been closed, but still exists in the connection pool；

log of this question:
`HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@57825052 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.`

**Comment by iwangjie** [comment]
You can try to shorten the maxLifetime time as prompted, or you can set keepLive to detect a connection timeout. In some complex networks, there are often components such as firewalls to limit the connection time of long connections, hoping to help you
