### ISSUE TITLE
[Question]Data synchronization fails on the client

### ISSUE THREAD

**Issue by liukun321** [apache/shenyu#4185]
### Question

The contextPath plugin's selector and rule create success，but the divideplugin's selector and rule create failure;

`public String register(final MetaDataRegisterDTO dto) {
        //handler plugin selector
        String selectorHandler = selectorHandler(dto);
        String selectorId = selectorService.registerDefault(dto, PluginNameAdapter.rpcTypeAdapter(rpcType()), selectorHandler);
        //handler selector rule
        String ruleHandler = ruleHandler();
        RuleDTO ruleDTO = buildRpcDefaultRuleDTO(selectorId, dto, ruleHandler);
        ruleService.registerDefault(ruleDTO);
        //handler register metadata
        registerMetadata(dto);
        //handler context path
        String contextPath = dto.getContextPath();
        if (StringUtils.isNotEmpty(contextPath)) {
            registerContextPath(dto);
        }
        return ShenyuResultMessage.SUCCESS;
    }`

view above code,two plugin should be all success

**Comment by KevinClair** [comment]
Show me the error log.
