### ISSUE TITLE
[Task] Add field appKey to ShenyuRequestLog

### ISSUE THREAD

**Issue by liukun321** [apache/shenyu#4186]
### Description

Log statistics need to be analyzed from the application dimension，but in ShenyuRequestLog have not application info

### Task List

1 Add field appKey to ShenyuRequestLog
2 Add appKey info in LoggingConsle plugin ( Print Request Info:)

**Comment by moremind** [comment]
it may not be necessary for shenyu request log..., Shenyu has reserved the implementation of `ShenyuRequestLog`,Parameters are passed in as generics
