### ISSUE TITLE
[Question] In the "org.apache.shenyu.admin.model.query.TagRelationQuery#equals"  why use the "o instanceof TagQuery"?

### ISSUE THREAD

**Issue by hnxiaoyuan** [apache/shenyu#4198]
### Question

I think it should be " `if (!(o instanceof TagRelationQuery))` "

![image](https://user-images.githubusercontent.com/20148163/202644023-6b8e3b5e-4154-4000-b9ff-2e0a7ce1c3e8.png)

**Comment by li-keguo** [comment]
Can you fix it？

**Comment by hnxiaoyuan** [comment]
I have created a PR to fix it, please help to check, Thanks!
