### ISSUE TITLE
[BUG] admin directory update failed and plugin configuration may change plugin name

### ISSUE THREAD

**Issue by Shashengzhe** [apache/shenyu#4211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when update directory
![image](https://user-images.githubusercontent.com/34408166/203892895-3fcfedbf-40b7-4134-8030-4fc1439d9e13.png)

if configuration has a field which named name, when change it, plugin's name will change
![image](https://user-images.githubusercontent.com/34408166/203893311-7a294dc7-ec54-45bb-ba55-cf8a2cf145b3.png)

### Environment

```markdown
ShenYu version(s): 2.5.0
```

**Comment by dengliming** [comment]
@Shashengzhe Can you fix it?

**Comment by Shashengzhe** [comment]
> 

can't
