### ISSUE TITLE
websocket connection server[ws://localhost:9095/websocket] is error

### ISSUE THREAD

**Issue by xiah217** [apache/shenyu#4220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Bootstrap：websocket connection server[ws://localhost:9095/websocket] is error

admin：originHeaderValue is forbidden: null

### Environment

```markdown
ShenYu version(s):
```

**Comment by yu199195** [comment]
whats version？ admin and boostrap？

**Comment by xiah217** [comment]
version 2.5

**Comment by xiah217** [comment]
> whats version？ admin and boostrap？

2.5版本  ，我启动了admin和boostrap   ，Bootstrap报：websocket connection server[ws://localhost:9095/websocket] is error，
admin报错：originHeaderValue is forbidden: null

**Comment by xiah217** [comment]
> websocket connection server[ws://localhost:9095/websocket] is error     这个是9195报的错误
originHeaderValue is forbidden: null    这个是9095报的错误

**Comment by xiah217** [comment]
> whats version？ admin and boostrap？

大佬  帮看一下

**Comment by yu199195** [comment]
can you show error log？

**Comment by alansun2** [comment]
我也出现了
bootstrap
![1672018761261](https://user-images.githubusercontent.com/27952746/209488759-9e70e538-0b60-47bb-b1cf-dc36016783c4.png)

shenyu-admin
![1672018813247](https://user-images.githubusercontent.com/27952746/209488813-ca38f67c-9231-466a-bfdf-31cd7caaaf31.png)

**Comment by LJngtan** [comment]
don't set sync.websocket.allowOrigins of shenyu-admin can resolve it, but just a way to avoid it, not a solution.😶

**Comment by LJngtan** [comment]
the other way is keep sync.websocket.allowOrigin of your custom shenyu-bootstrap consistent to sync.websocket.allowOrigins of  shenyu-admin. The logic is in [WebsocketSyncDataService](https://github.com/apache/shenyu/blob/f7f0d49d55a74005789827eeef75914283f93bb6/shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/WebsocketSyncDataService.java#L63).
A digression is that i dont konw whats mean of this design. Its a little different from my understanding of CORS. 🤔 Do you explain it? @yu199195

**Comment by yu199195** [comment]
@LJngtan For more safety~
