### ISSUE TITLE
Filename too long

### ISSUE THREAD

**Issue by willdomybest** [apache/shenyu#4225]
### Question

I clone the source code in windows os, it give me the error like these:
Error:cannot create directory at 'shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-dubbo/shenyu-spring-boot-starter-plugin-apache-dubbo/src/main/java/org/apache/shenyu/springboot/starter/plugin/apache': Filename too long

Its seams like the file path was too long,so i have try to changed my regedit, but it is not work.
Who can give me some help?  and if will we be freindly to our window user?

**Comment by yu199195** [comment]
see this ： https://shenyu.apache.org/zh/community/faq
