### ISSUE TITLE
[BUG] <The dictionary management apidoc cannot be saved>

### ISSUE THREAD

**Issue by zxl8899** [apache/shenyu#4227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

shenyu admin dictionary management failed to save, "Request error! invalid argument [enabled: cannot be null]"

return 

{
  "code": 500,
  "message": "Request error! invalid argument [enabled: 不能为null]",
  "data": null
}

### Environment

```markdown
ShenYu version(s): 2.5.0
```

### Anything else?

nothing

**Comment by dengliming** [comment]
Can you try the master version in dashboard? [https://github.com/apache/shenyu-dashboard](https://github.com/apache/shenyu-dashboard)
