### ISSUE TITLE
[BUG] Authentication edit

### ISSUE THREAD

**Issue by jiangdeen** [apache/shenyu#4241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

version 2.5.0

![image](https://user-images.githubusercontent.com/34539202/205871988-43f8a8f5-cf96-4a45-b6a8-433a12a8f779.png)

### Environment

```markdown
ShenYu version(s):
```

**Comment by dengliming** [comment]
Can you please give us more details?
