### ISSUE TITLE
[BUG] After the HTTP request passes through the shenyu proxy, the cookie is repeated

### ISSUE THREAD

**Issue by wls981** [apache/shenyu#4276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/15735480/208342780-813cd52f-8413-4c5a-bdb2-41a8b55f1a52.png)
![image](https://user-images.githubusercontent.com/15735480/208342814-413f690b-1521-495a-98c6-315ccd589986.png)
![image](https://user-images.githubusercontent.com/15735480/208343471-cb8a9dde-1702-444e-ba68-d32fe8fa96b9.png)

As shown in the picture above, after being proxied by the divide plug-in, the cookie in the returned HTTP response header is repeated.  

shenyu 2.4.3 and 2.5.0 can be reproduced.

### Expected Behavior

The cookie should not be repeated, because I find that after an http url passes through the gateway, 
the <Transfer-Encoding: chunked> header in the response header is also repeated, which causes the nginx in front of the gateway to report an error.

### Steps To Reproduce

Download shenyu-2.5.0-bootstrap-bin.tar.gz and shenyu-2.5.0-admin-bin.tar.gz directly from the official website, and simply configure the divide plug-in code to reproduce.

### Environment

```markdown
ShenYu version(s):2.4.3  、 2.5.0
```

### Debug logs

none

**Comment by yu199195** [comment]
The response header is duplicated, is it only the cookie and the rest will be duplicated?
