### ISSUE TITLE
[BUG] <Bugs when editing authentication data resource paths>

### ISSUE THREAD

**Issue by chengminglei77** [apache/shenyu#4277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The first time it can be operated normally, when editing and changing the data, the resource path cannot be edited and added, and when you click the delete button. All is deleted.
![ea699b714e93bccd8fb889cb8817827](https://user-images.githubusercontent.com/43779416/208371347-22c7e5fe-95fc-4fb3-83a1-26c09a1cc4e9.png)

### Environment

```markdown
ShenYu version(s):
```

**Comment by dengliming** [comment]
Can you provide the version you use? @chengminglei77
