### ISSUE TITLE
[Question] which version can support dubbo3 triple protocol

### ISSUE THREAD

**Issue by fantiq** [apache/shenyu#4284]
### Question

the question below is because the dubbo3 new protocol `triple`,when i switch to `dubbo` protocol in dubbo3, the shenyu-bootstrap works well.so the new question becomes **which version support proxy dubbo3 triple protocol?**

> 
> the server use dubbo v3.1.3 and shenyu use version 3.5.0. the dubbo service startup is ok and shenyu-bootstrap startup is ok, open the dubbo plugin on shenyu-admin (version is 3.5.0 too). when i request to the shenyu-bootstrap, i got the error
> 
> ```
> org.apache.dubbo.rpc.RpcException: Failed to invoke the method $invoke in the service org.apache.dubbo.rpc.service.GenericService. No provider available for the service org.xxx.xxxService from registry nacos-server:8848 on the consumer xxx.xx.x.x using the dubbo version 2.7.15. Please check if the providers have been started and registered.
> ```
> 
> when i look up the pom dependence version on 2.5.0 , i got this
> 
> ```
> <apache.dubbo.version>2.7.15</apache.dubbo.version>
> ```
> 
> it is not dubbo3, which version can support dubbo3?
>

**Comment by JooKS-me** [comment]
Triple is not currently supported.

**Comment by JooKS-me** [comment]
If you only use triple protocol instead of dubbo protocol, you can change "dubbo" to "tri" here,
https://github.com/apache/shenyu/blob/8c4c530206e36be531fed7a323025c5cc592af2b/shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApacheDubboConfigCache.java#L166
 this may be a temporary solution. I will try to make this more reasonable and convenient to use later.

**Comment by fantiq** [comment]
> If you only use triple protocol instead of dubbo protocol, you can change "dubbo" to "tri" here,
> 
> https://github.com/apache/shenyu/blob/8c4c530206e36be531fed7a323025c5cc592af2b/shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApacheDubboConfigCache.java#L166
> 
> 
> this may be a temporary solution. I will try to make this more reasonable and convenient to use later.

i have submit a pr #4286 
add the dubbo protocol in rpcExt, when call reference use the rpcExt.protocol to create, can u merge it?

**Comment by fantiq** [comment]
have already been solved on #4286
