### ISSUE TITLE
[BUG] k8s 部署报错

### ISSUE THREAD

**Issue by jiangdeen** [apache/shenyu#4288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我按照部署文档上的 yaml 进行部署,在k8s集群上启动报错

### Environment

```markdown
ShenYu version(s):
```

**Comment by jiangdeen** [comment]
![image](https://user-images.githubusercontent.com/34539202/209543178-3cbf6ce1-e8fd-4e9b-afaf-e3e2bd498fe5.png)

**Comment by yu199195** [comment]
pls in english

**Comment by jiangdeen** [comment]
Re question in English
