### ISSUE TITLE
[Question] </shenyu/plugin/selectorAndRules the configuration of this request cannot be synchronized to the console>

### ISSUE THREAD

**Issue by isfangmk** [apache/shenyu#4313]
### Question

![image](https://user-images.githubusercontent.com/50295485/212020207-6815967b-e404-4e2d-b716-c9f0df626a99.png)
![image](https://user-images.githubusercontent.com/50295485/212021115-6f06ac81-45fb-4aff-af7d-c719dad43b71.png)

After executing this request, the selector and rule in the divide plugin are empty, can't this configuration be synchronized to the console?

**Comment by moremind** [comment]
which version?

**Comment by isfangmk** [comment]
> which version?

The latest master branch

**Comment by xuyicheng1995** [comment]
from souce code, this request only send to shenyu-bootstrap, update local cache, and wont sync to shenyu-admin

org.apache.shenyu.web.controller.LocalPluginController#selectorAndRule

**Comment by moremind** [comment]
do you restart shenyu bootstrap?
