### ISSUE TITLE
[BUG] QuickStart problem

### ISSUE THREAD

**Issue by aswarcewicz** [apache/shenyu#4322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error on step with cURL when follow QuickStart guide

### Steps To Reproduce

1. Follow this instruction: https://shenyu.apache.org/docs/index#run-apache-shenyu-admin
2. Create dockers
3. Try to execute cURL
4. cURL returns 
```
{"code":-106,"message":"Can not find url, please check your configuration!"}
```

### Environment

```markdown
ShenYu version(s):tested with latest and 2.5.0
```

**Comment by yu199195** [comment]
Hi，

 maybe run docker with this ：

```
docker run -d -p 9195:9195 --net shenyu apache/shenyu-bootstrap 

-e  "SEHNYU_LOCAL_ENABLE = true"
```

**Comment by aswarcewicz** [comment]
```
docker run -d -p 9095:9095 --net shenyu apache/shenyu-admin

docker run -d -p 9195:9195 --net shenyu apache/shenyu-bootstrap -e  "SEHNYU_LOCAL_ENABLE=true"
```

and still that same error 

```
{"code":-106,"message":"Can not find url, please check your configuration!"}
```
