### ISSUE TITLE
DataSync Strategy select nacos

### ISSUE THREAD

**Issue by JemyXiao** [apache/shenyu#4324]
### Question

hi, if shenyu Admin select nacos dataSyncStrategy.

when my application has use nacos config and nacos register，my application subscribe shenyu Admin nacos dataSync ok？

haven't tried yet.

thanks for answer my question

**Comment by yu199195** [comment]
What does it have to do with your application?

**Comment by JemyXiao** [comment]
because I want to use this data synchronization module in my own application project, 
so I would like to ask in advance whether there is any conflict effect。
The nacos configuration center used by my application

**Comment by iwangjie** [comment]
From your point of view, there are no conflicts, and Shenyu only uses nacos for internal collaboration and does not affect your application.

**Comment by JemyXiao** [comment]
ok, i will try it

**Comment by JemyXiao** [comment]
thanks
