### ISSUE TITLE
[Task] <The proxy (divide) plug-in is expected to support: use the rewritten uri when routing.>

### ISSUE THREAD

**Issue by lianjunwei** [apache/shenyu#4341]
### Description

I have some urls with the same path prefix (that is, contxpath). Now I need to route part of the uri to service A and the other part of the url to service B.

**Comment by lianjunwei** [comment]
I am willing to support this feature.

**Comment by yu199195** [comment]
Now， not support？

**Comment by lianjunwei** [comment]
> Now， not support？

Yes, not now.

**Comment by lianjunwei** [comment]
<img width="2288" alt="通过重写路径决定转发哪个集群" src="https://user-images.githubusercontent.com/13819823/216100623-6aceb36d-f590-4f72-b736-806f25eb736c.png">
