### ISSUE TITLE
[Question] <How do I support the swagger of springcloud themselves?>

### ISSUE THREAD

**Issue by MrCoderStack** [apache/shenyu#4344]
### Question

[Question] <How do I support the swagger of springcloud themselves?>

I want direct access to each microservice swagger via shenyu.

I deployed shenyu in the K8s +docker cluster,
Multiple springcloud services are registered with shenyu, but cannot pass through directly
http://127.0.0.1:9195/testserver/swagger-ui.html
The way to access swagger addresses,
Adding rules manually in the springcloud plug-in is also not accessible.
I've tried using the divide plug-in to configure ip:host for access, which works, but obviously not for production because the cluster's service ip is not fixed.

**Comment by iwangjie** [comment]
https://github.com/apache/shenyu/issues/4353
