### ISSUE TITLE
[Task] Exposed interface access within the adaptation framework

### ISSUE THREAD

**Issue by iwangjie** [apache/shenyu#4353]
### Description

As mentioned in #4344 , Swagger's  `/swagger-ui.html` and  `/v2/api-docs` will become difficult to access after the gateway proxies the entire application service. I would like to try to think about and solve this problem.

If true, please assign the task to me.

Sincere greetings to all contributors to the community. 🐝

**Comment by KevinClair** [comment]
Good, looking forward to your pr.

**Comment by iwangjie** [comment]
I want to add an external direct forwarding option, and then the direct connection option will be added to the Divide plug-in, matching these paths through or, direct forwarding. What do you think?

For example, add a routing condition: 
/http/swagger-ui/**
/http/v2/api-docs
/http/swagger-resources/**
