### ISSUE TITLE
[Question] <Proxy https interface, get wrong response>

### ISSUE THREAD

**Issue by isfangmk** [apache/shenyu#4370]
### Question

On the latest master branch，proxy https://echo.hoppscotch.io/test/1 , get the wrong response. The configuration related to ssl is not enabled in shenyu-bootstrap.
![image](https://user-images.githubusercontent.com/50295485/217764370-4188c2ea-6ac6-4bd8-9b47-deeb4ed8bdf9.png)
![image](https://user-images.githubusercontent.com/50295485/217764455-61136299-dd1e-403a-b486-0aa99968022e.png)

**Comment by iwangjie** [comment]
Can you try enabling configuration and retry?

**Comment by isfangmk** [comment]
> Can you try enabling configuration and retry?

how to set to ignore ssl authentication
