### ISSUE TITLE
[Question] Roadmap

### ISSUE THREAD

**Issue by caojiajun** [apache/shenyu#4371]
### Question

Where can I view roadmap of `Apache Shenyu`？
The next version is `2.6.0`, what are the new features or enhancement in the plan?
I can only see some bug fix here:  `https://github.com/apache/shenyu/milestone/9` .

**Comment by moremind** [comment]
pls join ShenYu Meeting

**Comment by iwangjie** [comment]
pls join biweekly meetings
https://meeting.tencent.com/dm/DwBy1dgr3g7F

**Comment by caojiajun** [comment]
thank you~

**Comment by iwangjie** [comment]
If it has been solved, pls close
