### ISSUE TITLE
[Question] Can shenyu be used as an egress gateway?

### ISSUE THREAD

**Issue by qiankangjian** [apache/shenyu#4373]
### Question

To manage various third party APIs, we need a reverse-proxy gateway to take the role as egress gateway, the request traffic path will be: micro services->egress gateway->third APIs. So can shenyu be used as an egress gateway?

**Comment by iwangjie** [comment]
As a gateway, shenyu does not distinguish between forward proxy and reverse proxy. You can use reverse proxy to proxy your service or even tripartite service (we do this internally).

**Comment by KevinClair** [comment]
of course.

**Comment by qiankangjian** [comment]
> As a gateway, shenyu does not distinguish between forward proxy and reverse proxy. You can use reverse proxy to proxy your service or even tripartite service (we do this internally).
------------------------
3rd API: GET http://www.weather.com.cn/m2/i/icon/faviconie9.ico
<img width="587" alt="image" src="https://user-images.githubusercontent.com/33289104/218022180-34ce2d05-03d1-4003-a1a1-83128132ea53.png">
config on the admin ui manually:
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/33289104/218021048-14bb3f18-1c41-4cea-a588-1aaa82309616.png">
<img width="821" alt="image" src="https://user-images.githubusercontent.com/33289104/218021302-9ed876e7-1e1e-4042-beab-751eece3108e.png">

Call GET http://localhost:9195/m2/i/icon/faviconie9.ico, the result is :
<img width="581" alt="image" src="https://user-images.githubusercontent.com/33289104/218021814-6c38a06e-35f0-4e05-8677-43943aea1bd8.png">

so why I got a 403 Forbidden response? any configuration wrong?

**Comment by iwangjie** [comment]
It seems that the other website has made source restrictions

**Comment by qiankangjian** [comment]
Thanks.
