### ISSUE TITLE
[BUG] Plugin rule update did not take effect in time.

### ISSUE THREAD

**Issue by iwangjie** [apache/shenyu#4378]
### Bug Description

After the plug-in matching rule is updated, the new rule of the request gateway does not take effect.

synchronous invalid.

#### Context

After I modified the rule in shenyu admin, the synchronization gateway was triggered, and the gateway did not seem to handle it correctly 
 
The gateway uses prefix tree to store rules, and the processing logic of updating action is putNode, so the historical rules are not cleaned up, which leads to the request interface still using the old rules after updating rules

Divide plugin, the source address can still be accessed after the Condition changes, which is fatal:
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/23075587/218469638-15d83510-6fcf-4a35-8e44-0f7b2d044ffa.png">

Similarly, WAF plugin
After the firewall rule switch changes, it does not take effect, which is also fatal:

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/23075587/218358337-2e804106-329b-4f6d-b79c-af0a27a9f461.png">

<img width="580" alt="image" src="https://user-images.githubusercontent.com/23075587/218358530-4cf15ba5-9c51-41af-8a11-ba7e9df0fa59.png">

**Comment by KevinClair** [comment]
Please click `Synchronous waf` and try it again.

**Comment by iwangjie** [comment]
> Please click `Synchronous waf` and try it again.

Can you add WeChat to talk about it? My name is 'iwangjie' in the wechat group.

**Comment by iwangjie** [comment]
<img width="1530" alt="image" src="https://user-images.githubusercontent.com/23075587/218379831-64e45683-253a-46a7-8ce8-b824d7bb40b6.png">

Direct request after configuration--> Success 
 
Synchronize and request again after configuration--> Success 
 
Every time a rule is saved, there is an additional rule cache, and the historical enable=true rule is also in it. The result is that the match is not matched according to the new rule. 
 
This could be a BUG, I used the jmeter test and inserted 240,000 rule caches, which could lead to OOM?

**Comment by iwangjie** [comment]
I think it is a bug, please assign it to me and I will solve it.  Also, do I need to reopen a bug issue? @KevinClair

**Comment by KevinClair** [comment]
No need.

**Comment by KevinClair** [comment]
Please associate this issue when creating PR

**Comment by iwangjie** [comment]
> Please associate this issue when creating PR

ok

**Comment by iwangjie** [comment]
@KevinClair pls check this issue and pr.
