### ISSUE TITLE
[BUG] The Host field is set incorrectly when the upstream is reverse proxy.

### ISSUE THREAD

**Issue by iwangjie** [apache/shenyu#4381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the reverse proxy upstream is NGINX's service, all request headers will be sent upstream as they are, while the Host request header is special, which will lead to 403 if it is incorrect. 
 
For example, the proxy http://www.weather.com.cn/, if the Host field is passed as the request Host of the gateway, the server returns 403, and the value of Host that should be passed is www.weather.com.cn. 
 
If this is a bug, please assign it to me and I'll fix it. 

### Expected Behavior

Host field is `www.weather.com.cn`

### Steps To Reproduce

1. Reverse proxy www.weather.com.cn
2. Access
3. result 403

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/23075587/218417969-c01dac3a-a882-4ec4-8116-ade3736056bb.png">

<img width="989" alt="image" src="https://user-images.githubusercontent.com/23075587/218418017-9be79736-2f6f-45ac-b4df-f69636f98681.png">

### Environment

```markdown
ShenYu version(s): Latest
```

**Comment by skyding228** [comment]
I got the same problem. But fixed it with " httpProcess->request " plugin, add correct "host" header.

**Comment by iwangjie** [comment]
> I got the same problem. But fixed it with " httpProcess->request " plugin, add correct "host" header.

Yes. It can be solved by doing so, but it should be a defect.

**Comment by iwangjie** [comment]
![image](https://user-images.githubusercontent.com/23075587/222643371-c30babd0-57db-4123-9545-fb3dfe3bc22f.png)

I found this commit.

**Comment by iwangjie** [comment]
@yu199195 Hi. Please confirm, Will this change bring about this problem?

**Comment by yu199195** [comment]
@iwangjie  maybe should fix it

**Comment by iwangjie** [comment]
> @iwangjie maybe should fix it

ok. I'll submit a PR later.
