### ISSUE TITLE
[Question] Whether nginx must use ip_ hash mode during cluster deployment

### ISSUE THREAD

**Issue by cl0924** [apache/shenyu#4384]
### Question

Nginx uses ip_ hash mode in the cluster deployment of the official document, ip_hash configuration necessary? If this method is used, it seems that the IP access of the same network segment will be allocated to a machine. Will it have a great impact to change the polling method?
![image](https://user-images.githubusercontent.com/84334635/218694995-0b96e304-5a50-491b-8f21-46bdeee20a95.png)

**Comment by iwangjie** [comment]
You can choose the load mode according to the actual situation, and ip_hash is not necessary.

**Comment by cl0924** [comment]
Ok, thank you very much for your answer
