### ISSUE TITLE
[BUG] The custom handler information of the custom plugin still take effect when modified

### ISSUE THREAD

**Issue by LiKaiping415** [apache/shenyu#4388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I customized a plugin called ACL
![image](https://user-images.githubusercontent.com/111277655/219253165-5ac328be-98dc-4650-99df-476948f7f825.png)
and then I customized a hander in the selector called "AppCode" like that:
![image](https://user-images.githubusercontent.com/111277655/219253365-db57df17-ff58-4691-b9e3-cf0e74e10852.png)
after that, I customized a hander in the rule called "权限码" like that:
![image](https://user-images.githubusercontent.com/111277655/219253577-b8a39c0d-460d-4d8d-a397-412c3261c527.png)
When I modified the “权限码”, the old “权限码” still takes effect.

I probably looked up the source code and found that my previous handlers were still in the cache, and I thought the old handlers should disappear：
![image](https://user-images.githubusercontent.com/111277655/219254175-7e7ecde9-fcc0-42fc-9d33-b245fec1da45.png)
Actually in the page, I only have one rule, and the other is an old record

### Expected Behavior

When I change the value of a field in the handler, it should take effect immediately, and there should be no old records in the cache

### Steps To Reproduce

1. custom a plugin 
2. custom a handler field in selector
3. custom a handler field in rule
4. modify the handler field in rule

### Environment

```markdown
ShenYu version(s):2.5.1
```

**Comment by iwangjie** [comment]
It will be fixed at #4380

**Comment by moremind** [comment]
hi, it have fixed in master branch, please use master branch include shenyu-admin and shenyu-bootstrap.

**Comment by LiKaiping415** [comment]
> 

ok,thank you

**Comment by LiKaiping415** [comment]
> hi, it have fixed in master branch, please use master branch include shenyu-admin and shenyu-bootstrap.

ok, thank you

**Comment by LiKaiping415** [comment]
> hi, it have fixed in master branch, please use master branch include shenyu-admin and shenyu-bootstrap.

@moremind @iwangjie hello，I found that the update did take effect when there was only one rule. However, when there are multiple rules, the update does not take effect

**Comment by moremind** [comment]
multiple rules? please give me your rule configurations.

**Comment by moremind** [comment]
@LiKaiping415 you can add my wechat to discuss this question, yijia1949

**Comment by iwangjie** [comment]
Hi I reproduced it according to my understanding, but it didn't succeed. Please provide more information.

First, I created a rule that contains two conditions, and now I can access both rules normally in the browser
![image](https://user-images.githubusercontent.com/23075587/220233047-497e618c-2f66-4c40-b546-7047e3282b3b.png)

<img width="530" alt="image" src="https://user-images.githubusercontent.com/23075587/220233262-7b5eab02-0e42-4467-a746-03dd102b86cb.png">

<img width="735" alt="image" src="https://user-images.githubusercontent.com/23075587/220233285-435ee9ee-a52c-438c-87b9-16682b6dde3c.png">



Then I changed the rule, changed or to and, and again, failed to find the rule as expected:

<img width="982" alt="image" src="https://user-images.githubusercontent.com/23075587/220233336-13c86b7b-302c-4e93-acc4-c307599fff72.png">

<img width="634" alt="image" src="https://user-images.githubusercontent.com/23075587/220233366-78fee22b-44f2-4ba5-b342-e0dc4161bb8c.png">

Finally I restored the rule back, and to change it, I changed the route of /hello100 to /hello99:

<img width="783" alt="image" src="https://user-images.githubusercontent.com/23075587/220233495-c3a491d6-7d57-46f8-b382-a7e55d75bf6b.png">

I went ahead and modified the timeout for use-case integrity, and it still works:

![image](https://user-images.githubusercontent.com/23075587/220233671-ce68fc09-5ba0-4e2b-863e-5b1cc2fc0941.png)

<img width="901" alt="image" src="https://user-images.githubusercontent.com/23075587/220233687-9f87c084-27fb-4c6b-9e11-955d62d6e225.png">

**Comment by iwangjie** [comment]
@LiKaiping415 pls check that my use case meets your expectations.
