### ISSUE TITLE
[Question] why timeout returns 500, not 504?

### ISSUE THREAD

**Issue by islaiyp** [apache/shenyu#4389]
### Question

Using SpringCloud, modified the rule, change timeout from 3000 to 1.
After send my request again, it returned 500, not 504 gateway timeout.

`shenyu 2.5.0`

**Comment by iwangjie** [comment]
Please provide more context.

**Comment by islaiyp** [comment]
> Please provide more context.

Using springCloud plugin, after my server registered, I go into `PluginList=>Proxy=>SpringCloud=>SelectorList=>RulesList`, modified one of my rules, changed timeout from 3000 to 1, then send request.
of course the request result is timeout, but I confused, why the reponse body's code is `500`, and msg is `Internal Server Error`, I think the code should be 504.

**Comment by islaiyp** [comment]
i just saw this problem has been solved in `2.5.1`.

**Comment by lixianli1987** [comment]
> i just saw this problem has been solved in `2.5.1`.

I am also facing this problem now!
I hope to return the timeout error message to the requesting system after timeout, instead of returning 500！
But I don't know how to solve this problem
