### ISSUE TITLE
[Question]  Do I need to manually modify the uri after registering restful http requests

### ISSUE THREAD

**Issue by cl0924** [apache/shenyu#4391]
### Question

Can shenyu handle the restful style request? I read the official document and couldn't find it

The original request is as follows
`http://localhost:8080/test/5`
The http code is as follows
 ```
   @DeleteMapping("{id}")
    @ShenyuSpringMvcClient(path = "{id}")
    public String delete(@PathVariable long id) {
 ...
}
```
The rule after successful registration is `/http/test/{id}`
An error will be reported when the request in shenyu is as follows
`http://localhost:9195/http/test/5`
The error is reported as follows
```
{
    "code": -102,
    "message": "divide:Rule not found!"
}
```
It seems that when the rule condition is registered, the matching rules of default uri is`=`，When it is changed to `match` or `pathPattern`, the request can be successful
![image](https://user-images.githubusercontent.com/84334635/219286098-17a41db0-7302-424f-864d-d41b207f1d5e.png)
Do I need to manually modify the uri matching criteria under normal circumstances？

**Comment by yu199195** [comment]
uri  match  type
