### ISSUE TITLE
[BUG] cryptorRequest plugin replaces originalBody with field data when it is DECRYPT way

### ISSUE THREAD

**Issue by skyding228** [apache/shenyu#4395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The whole HttpRequestBody was replaced by The decrypt data of The field configured in “fieldNames”;
`{"phone":"MUoxWVRwZD10cmgyMG1yN3pFOHVnZz09","prov":"371"}` -> `19837107777`
### Expected Behavior

Only The encrypt field data was replaced by The decrypt field  data instead of the whole HttpRequestBody ;
`{"phone":"MUoxWVRwZD10cmgyMG1yN3pFOHVnZz09","prov":"371"}` -> `{"phone":"19837107777","prov":"371"}`
### Steps To Reproduce

1.  config rules as below:
![image](https://user-images.githubusercontent.com/3915919/219586495-0a6e9ab6-90df-42d7-b425-1682aa9dd215.png)
2. send request body to gateway:
```json
{
"phone":"MUoxWVRwZD10cmgyMG1yN3pFOHVnZz09",
"prov":"371"
}
```
3. the backend server received:
expect `{"phone":"19837107777","prov":"371"}` but `19837107777`.
![image](https://user-images.githubusercontent.com/3915919/219591708-0650d676-bb2e-4139-a8e8-e221b3b0f7cd.png)

`"19837107777"` is the text of `"MUoxWVRwZD10cmgyMG1yN3pFOHVnZz09"`,It's correct, but the `prov` missed;

### Environment

```markdown
ShenYu version(s):2.5.1
```

### Debug logs

![image](https://user-images.githubusercontent.com/3915919/219589277-d0c3756c-8793-4274-8158-436e9660b7c3.png)
Both parseBody(step 1) and modifiedBody(step 2) are correct. But the return(step 3) is wrong, some bad things happend in `CryptorUtil.replace` method when `ruleHandler.getWay()` is `DECRYPT`, the source code is:
![image](https://user-images.githubusercontent.com/3915919/219591173-777eb70b-6bf3-44fb-bad3-11df6b191e84.png)

**Comment by damonxue** [comment]
At present, decryption only supports solving the encrypted value and returning it, and encryption will modify the field value and return the entire body:
```
 If it is decrypt mode, replace the original requestBody,
 if it is encrypt mode, it will replace the content of the fieldName configuration.
```
Please describe your scene, discuss whether it is necessary to be necessary to extend these encryption and decryption ruler-handler options.

**Comment by skyding228** [comment]
The request flow as below:
`{"phone":"MUoxWVRwZD10cmgyMG1yN3pFOHVnZz09","prov":"371"}`(user client)
 -> 
`{"phone":"MUoxWVRwZD10cmgyMG1yN3pFOHVnZz09","prov":"371"}`(shenyu gateway)
 -> 
`{"phone":"19837107777","prov":"371"}`(backend server)

I should config it in ENCRYPT mode. But when `"MUoxWVRwZD10cmgyMG1yN3pFOHVnZz09" -> 19837107777 (in shenyu gateway)`  the `encrypt` method was called. It means the `encrypt` method is doing `decrypt` function.

![image](https://user-images.githubusercontent.com/3915919/219611314-522ff02b-7751-4ee7-aaac-b913478954e7.png)

**Comment by damonxue** [comment]
It seems that the scene is that the backend service needs to obtain the decrypted entire body. If this is the only reason, it only needs to remove the decrypt judgment of replace, but it needs to be considered whether it is used by other scenarios.

**Comment by damonxue** [comment]
Maybe the decrypt way is vague. @dragon-zhang. Maybe need to expand other ways.

**Comment by damonxue** [comment]
@tian-pengfei  
Pls decide it.

**Comment by tian-pengfei** [comment]
> what should I text in `filedNames` which means `entire body` ? ![image](https://user-images.githubusercontent.com/3915919/219830883-fd522125-4e15-4796-bc8b-3bccd48ca409.png)

For now I think there is no way to do that for cryptorRequest.   The beaviour of cryptorRequest plugin is worth discussing.

**Comment by dragon-zhang** [comment]
> Maybe the decrypt way is vague. @dragon-zhang. Maybe need to expand other ways.

In `org.apache.shenyu.plugin.cryptor.handler.CryptorRuleHandler`, maybe we can add a `replaceType` and use `all` as default to ensure compatibility, then add `field` to describe just replace the field with the given name.

The changes should be made in `org.apache.shenyu.plugin.cryptor.request.CryptorRequestPlugin#convert`.

After the `CryptorResponsePlugin` also supports `replaceType`, we can refactor the code.

Are there any volunteers?

**Comment by damonxue** [comment]
> > Maybe the decrypt way is vague. @dragon-zhang. Maybe need to expand other ways.
> 
> 
> 
> In `org.apache.shenyu.plugin.cryptor.handler.CryptorRuleHandler`, maybe we can add a `replaceType` and use `all` as default to ensure compatibility, then add `field` to describe just replace the field with the given name.
> 
> 
> 
> The changes should be made in `org.apache.shenyu.plugin.cryptor.request.CryptorRequestPlugin#convert`.
> 
> 
> 
> After the `CryptorResponsePlugin` also supports `replaceType`, we can refactor the code.
> 
> 
> 
> Are there any volunteers?

That's what I mean.pls assign 2 me.

**Comment by damonxue** [comment]
> > > > Maybe the decrypt way is vague. @dragon-zhang. Maybe need to expand other ways.
> 
> > > 
> 
> > > 
> 
> > > In `org.apache.shenyu.plugin.cryptor.handler.CryptorRuleHandler`, maybe we can add a `replaceType` and use `all` as default to ensure compatibility, then add `field` to describe just replace the field with the given name.
> 
> > > The changes should be made in `org.apache.shenyu.plugin.cryptor.request.CryptorRequestPlugin#convert`.
> 
> > > After the `CryptorResponsePlugin` also supports `replaceType`, we can refactor the code.
> 
> > > Are there any volunteers?
> 
> > 
> 
> > That's what I mean.pls assign 2 me.
> 
> 
> 
> hi，I am interested in the project and this issue. Can I participate in it together？

pls add my wechat(id: Fibonacci_stack).

**Comment by damonxue** [comment]
I will submit another pr later to increase the feature that `fieldNames` supports multiple fields. So there is a need to determine whether `mapType` should add the 'fields' option;

* `field` map to value of a single field (Compatible with older versions)
* `all` map to another JSON with whole fields;
* `field` map to another JSON with the specified fields;

**Comment by damonxue** [comment]
It's done, pls close as complete.
