### ISSUE TITLE
[Question] <Ask if the auto-register rule list can be customized?>

### ISSUE THREAD

**Issue by Sc-seven** [apache/shenyu#4401]
### Question

![image](https://user-images.githubusercontent.com/118173267/220116924-c2e9b657-c1c0-4e5b-bfbe-d55a26b44b0c.png)
How can the value under handle, which is automatically registered in a springboot project, be customized externally via a configuration file?

**Comment by Sc-seven** [comment]
> ### Question
> ![image](https://user-images.githubusercontent.com/118173267/220116924-c2e9b657-c1c0-4e5b-bfbe-d55a26b44b0c.png) springboot项目中自动注册handle下的值该如何通过配置文件自定义呢？

**Comment by iwangjie** [comment]
At present, you can only modify it in shenyu-admin

**Comment by Sc-seven** [comment]
thank you!
