### ISSUE TITLE
[Question] <title> /META-INF/script/custom_rate_limiter.lua can’t find error

### ISSUE THREAD

**Issue by Mingsicogi** [apache/shenyu#4406]
### Question

I did RateLimiterAlgorithm interface class implement also lua script. But I added under /META-INF/script, I got an error that ‘custom_rate_limiter.lua’ file not open because not exists…

Do you happen to know how can I fix it? I think that can use custom lua script for new implement RateLimiterAlgorithm class!!

Please some tips….

**Comment by yu199195** [comment]
getScriptName  return  custom_rate_limiter

public interface RateLimiterAlgorithm<T> {

    /**
     * Gets script name.
     *
     * @return the script name
     */
    String getScriptName();

**Comment by Mingsicogi** [comment]
I got that error like that [org.apache.shenyu.plugin.ratelimiter.handler.ShenyuReactiveScriptExecutor - Redis execute exception: Error reading script text; nested exception is java.io.FileNotFoundException: class path resource [META-INF/scripts/costum_rate_limiter.lua] cannot be opened because it does not exist]

Because of initialize through constructor, script name value was set.. 

Can you check my code and lua script file location?

`
@Join
public class CustomRateLimiterAlgorithm extends AbstractRateLimiterAlgorithm {

	private static final String KEY_NAME = "custom_rate_limiter";
	private static final String SCRIPT_NAME = KEY_NAME + ".lua";

	public GameServerGWRateLimiterAlgorithm() {
		super(SCRIPT_NAME);
	}

	@Override
	protected String getKeyName() {
		return KEY_NAME;
	}
}
`

- resources
-- META-INF
--- script
---- custom_rate_limiter.lua

**Comment by Mingsicogi** [comment]
@yu199195 

I solved this issue through setting on sub-class constructor like that

`
public GameServerGWRateLimiterAlgorithm() throws IOException {
		super(SCRIPT_NAME); // not working...

		// need to setting that was set on super class
		DefaultRedisScript redisScript = new DefaultRedisScript();
		redisScript.setScriptSource(new ResourceScriptSource(new ClassPathResource("/META-INF/script/" + SCRIPT_NAME)));
		redisScript.setResultType(List.class);
		this.script = redisScript;
}
`
