### ISSUE TITLE
how build a cluster,which use nacos-data-sync.

### ISSUE THREAD

**Issue by Layfolk-zcy** [apache/shenyu#4421]
### Question

i want to build a cluster but the data sync by nacos-data-sync. whether need to deploy multi-shenyu-boostrap and multi-shenyu-admin. i can't find things in the official website.

**Comment by yu199195** [comment]
Depends on your own deployment~

**Comment by Layfolk-zcy** [comment]
> Depends on your own deployment~

i konw, i run a shenyu-bootstrap、a shenyu-admin and my application in my idea,register them in the nacos which the result is ok. but how configurate gateway’s cluster mode, whether multi-gateway and a shenyu-admin register in a same nacos. In the nacos-data-sync, how define the ip:port in the gateway configuration.

**Comment by Layfolk-zcy** [comment]
> Depends on your own deployment~

![image](https://user-images.githubusercontent.com/59356890/222385988-7c22770d-2108-4080-b7ff-709a412b5235.png)

**Comment by yu199195** [comment]
Run more shenyu-bootstrap
>how configurate gateway’s cluster mode
