### ISSUE TITLE
[Question] something about WebFluxResultUtils and plugin execute process

### ISSUE THREAD

**Issue by seetbw** [apache/shenyu#4423]
### Question

i find every plugin have order,could i change it?
when plugin chain execute need stop,am i must throw exception to stop chain?
there are a lot of WebFluxResultUtils.result useage,this programe allow many use in one request?should i check it is committed? because if mutiple time use there will be a lot exception，already committed.

**Comment by iwangjie** [comment]
hi @seetbw 

1. The order of the built-in plug-ins is not recommended and can lead to unexpected behavior
2. You can use it `return WebFluxResultUtils.result(exchange, error);`  to stop the chain
3. You do not need to check whether the call has been made because the request will be terminated

**Comment by iwangjie** [comment]
@seetbw hi. you maybe that's what you're looking for?

![image](https://user-images.githubusercontent.com/23075587/222879828-3194d7bb-ca31-4ddf-83a9-8491df1a3eff.png)


<img width="789" alt="image" src="https://user-images.githubusercontent.com/23075587/222879837-f96b3f81-f0fb-4127-990d-e7a22ee204f5.png">
