### ISSUE TITLE
[BUG] <shenyu.shenyu.upstreamCheck config config no effect>

### ISSUE THREAD

**Issue by myxyz** [apache/shenyu#4436]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

1. in shenyu gateway bootstrap  upstreamCheck  no effect
2. in shenyu admin module check effect but delete  checked  error upstream in db ,when the upstream  after sucess is can't not add in db

### Environment

```markdown
ShenYu version(s):all version
```

### Debug logs

no

### Anything else?

no

**Comment by iwangjie** [comment]
Looks just like #4298
