### ISSUE TITLE
[Volunteer] XSS Cross-site attack Plugin.

### ISSUE THREAD

**Issue by iwangjie** [apache/shenyu#4437]
### Description

🗣️Hi, members of the community. 

The topic of this discussion is to avoid XSS cross-site scripting attacks in Shenyu by providing a general plugin. Please allow me to introduce the background of XSS cross-site scripting attacks.

XSS (Cross-Site Scripting) is a common Web application security vulnerability where an attacker injects malicious code into a Web application to make it execute in the victim's browser, to steal sensitive user information or perform malicious operations on the victim's account.

Usually, both internal and external access should be considered untrusted, and the same goes for XSS cross-site scripting attacks. We often write something like an XSSFilter in our code to achieve this effect, but it is repetitive, reusable, and may need to be updated as attack techniques evolve, and is not set in stone.

☕️I want to write and provide an XSS plugin that offers configurable XSS attack interception behavior support.

The ultimate goal of the plugin is to eliminate XSS attack operations by leveraging Shenyu's plugin capabilities and simple configuration, including but not limited to the following:

- Input validation and filtering: For all data input to the web application, validation and filtering should be performed to prevent injection of malicious code. For example, regular expressions or filters can be used to restrict input character sets and content.
- Output encoding: All data output from the web application to the browser should be HTML or JavaScript encoded to ensure that the browser correctly interprets them and does not execute them as code. For example, HTML encoding can be used to convert special characters to entity characters, or JavaScript encoding can be used to output data as strings.
- HttpOnly cookie: Marking cookies as HttpOnly can prevent browsers from accessing them through JavaScript, thus preventing XSS attackers from stealing cookies and performing operations.
- And some future enhanced XSS protection.

Of course, the strength of its protection should be configurable, like a browser ad-blocker plug-in, supporting a trade-off between performance and security.

### Task List

1. The new XssPlugin

**Comment by jilliss** [comment]
As far as I know, current browsers have handled XSS attacks very well, for some outdated browsers, the common practice is to add `X-XSS-Protection:1; mode=block` response header 
`Spring Security` That's how it's done
If you need this plug-in to add a response header
Then I'd be happy to help

**Comment by iwangjie** [comment]
> That's how it's done
> If you need this plug-in to add a response header
> Then I'd be happy to help

Hi. Simple xss attacks may be well defended, but if we need some custom defenses, it will not be easy to implement. This plug-in will support some custom defense policies.

I noticed that you said the X-XSS-Protection request head, this is the information I found,

I understand that it is not reliable

Maybe we can continue this discussion!

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

**Comment by jilliss** [comment]
> > That's how it's done
> > If you need this plug-in to add a response header
> > Then I'd be happy to help
> 
> Hi. Simple xss attacks may be well defended, but if we need some custom defenses, it will not be easy to implement. This plug-in will support some custom defense policies.
> 
> I noticed that you said the X-XSS-Protection request head, this is the information I found,
> 
> I understand that it is not reliable
> 
> Maybe we can continue this discussion!
> 
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

Yes, I refer to this link  
If a high degree of customization is required, consider the `Content-Security-Policy` response header
also need to add html escape logic to your code
There's not much the server can handle

**Comment by iwangjie** [comment]
> 



> > > That's how it's done
> > > If you need this plug-in to add a response header
> > > Then I'd be happy to help
> > 
> > 
> > Hi. Simple xss attacks may be well defended, but if we need some custom defenses, it will not be easy to implement. This plug-in will support some custom defense policies.
> > I noticed that you said the X-XSS-Protection request head, this is the information I found,
> > I understand that it is not reliable
> > Maybe we can continue this discussion!
> > https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection
> 
> Yes, I refer to this link If a high degree of customization is required, consider the `Content-Security-Policy` response header also need to add html escape logic to your code There's not much the server can handle

Thank you for your discussion and suggestions, and I will seriously consider them.
