### ISSUE TITLE
[Task] Design and implement shenyu ingress-controller in k8s

### ISSUE THREAD

**Issue by yu199195** [apache/shenyu#4438]
### Background

Apache ShenYu is a Java native API Gateway for service proxy, protocol conversion and API governance. Currently, ShenYu has good usability and performance in microservice scenarios. However, ShenYu's support for Kubernetes is still relatively weak.

### Tasks

1. Discuss with mentors, and complete the requirements design and technical design of shenyu-ingress-controller.
2. Complete the initial version of shenyu-ingress-controller, implement the reconcile of k8s ingress api, and make ShenYu as the ingress gateway of k8s.
3. Complete the ci test of shenyu-ingress-controller, verify the correctness of the code.

### Relevant Skills

1. Know the use of Apache ShenYu
2. Familiar with Java and Golang
3. Familiar with Kubernetes and can use java or golang to develop Kubernetes Controller

**Comment by hanbings** [comment]
Hello, I am a student from China and I like to deal with Java or other programming languages. 
Recently, I am learning about microservices, and I hope to exercise myself through the open source community.
I am very interested in this task and GSOC activity and hope to complete this task with you! Where should I start? Or how can I contact you?

**Comment by xiaozhuo1010** [comment]
may i join？

**Comment by parthpandya99** [comment]
I am interested in contributing to this

**Comment by parthpandya99** [comment]
@yu199195 
I am interested in contributing to this

**Comment by Hello-gzk-World** [comment]
@yu199195
Can I get more information about this issue? I ‘m new to open source and noticed the shenyu community on GSOC2023.  I am familiar with Java and Golang. And I'm interested in k8s and shenyu so that I feel that I am able to have this project done. So what should I do next? Could you please suggest me some issues on which I can work to gain some experience for this particular project. Thanks

**Comment by JooKS-me** [comment]
I'm very interested in this topic. I will apply as a student. I'm currently writing a proposal, which will be published and discussed on the mailing list.
