### ISSUE TITLE
[Question] reference Dubbo documentation not found

### ISSUE THREAD

**Issue by comeCU** [apache/shenyu#4440]
### Question

The link in the reference Dubbo documentation not found.(https://shenyu.apache.org/zh/docs/design/spi-design)

[SPI扩展实现](https://dubbo.apache.org/zh/docs/v2.7/dev/impls/)
<img width="574" alt="image" src="https://user-images.githubusercontent.com/30254171/223029598-f9053dfa-2778-43a6-9abe-5ff50021920f.png">

**Comment by iwangjie** [comment]
hi. this problem will be fixed, please manually switch to quick start.
