### ISSUE TITLE
[Question] SpringCloud serviceId does not exist or is configured incorrectly![Shenyu proxy]

### ISSUE THREAD

**Issue by comeCU** [apache/shenyu#4447]
### Question

Hi, when i follow the document [Doc](https://shenyu.apache.org/zh/docs/quick-start/quick-start-springcloud)，run into
SpringCloud serviceId does not exist or is configured incorrectly!

<img width="952" alt="image" src="https://user-images.githubusercontent.com/30254171/223314235-bfb3b533-ce7c-4048-a206-f4cf085c5258.png">

ShenyuSpringCloudServiceChooser#getServiceInstance
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/30254171/223313992-7b54f114-9d40-483e-8e72-115d65947083.png">

**Comment by moremind** [comment]
do you register service to registry? pls read doc in https://shenyu.apache.org/zh/docs/plugin-center/proxy/spring-cloud-plugin

**Comment by moremind** [comment]
shenyu-bootstrap not register to registry.

**Comment by comeCU** [comment]
I got it，thank you.
