### ISSUE TITLE
shenyu转发dubbo请求进行压测时报错

### ISSUE THREAD

**Issue by wangpf09** [apache/shenyu#4464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

使用shenyu转发dubbo请求，压测时10个线程下，shenyu-bootstrap报错，并且性能很差

The invoker of ReferenceConfig(null) has already destroyed!

![562f75649002836bbfcd480b95875ab7_](https://user-images.githubusercontent.com/39894166/224026538-887ef980-8ac7-48fa-9d64-9e0856d9128c.png)

### Environment

```markdown
ShenYu version(s): v2.5.1
```

**Comment by iwangjie** [comment]
hi. pls see https://github.com/apache/shenyu/issues/4432
