### ISSUE TITLE
[Question] <Sofa must have body param, please enter the JSON format in the body!>

### ISSUE THREAD

**Issue by lai53050960** [apache/shenyu#4471]
### Question

curl -H "Content-Type: application/json" -X POST -d '{"id": "123"}' "http://localhost:9195/sofa/findById"

{"code":432,"message":"Sofa must have body param, please enter the JSON format in the body!"}

problem：
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18829432/225004598-3af709f6-e939-4552-bbe6-f8ef1f4b29e2.png">

param is null

**Comment by lai53050960** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18829432/225004770-7daf7d46-29cd-4fb7-81a2-b05218c6ee49.png">

**Comment by lai53050960** [comment]
What should I do

**Comment by yu199195** [comment]
Mybe set  http  header

**Comment by smil123** [comment]
Set dubbo plugin sort 400 (or larger).  (Path: Shenyu Admin -> Basic plugin -> plugin)
This set ApacheDubboPlugin is after RpcParamTransformPlugin.  
Then ApacheDubboPlugin could get value  when excuting the code : 
`exchange.getAttribute(Constants.PARAM_TRANSFORM)`
