### ISSUE TITLE
[Task] <Design license scanning function>

### ISSUE THREAD

**Issue by impactCn** [apache/shenyu#4494]
### Description

**Background**

At present, shenyu needs to manually check whether the license is correct one by one when releasing the version.

**Tasks**
1. Discuss with the tutor to complete the requirement design and technical design of the scanning license.
2. Finished scanning the initial version of the license.
3. Complete the corresponding test.

**Relevant Skills**

1. Familiar with Java.

**Comment by erdengk** [comment]
I'm very interested in this topic. I will apply as a student. I'm currently writing a proposal, which will be published and discussed on the mailing list.

**Comment by Halcastle** [comment]
Hi, I also want to participate in this task, I am familiar with the common skills of Java, but I am just beginning to participate in open source.

**Comment by shanthiOC** [comment]
Is there anything I can contribute with this task?
