### ISSUE TITLE
[BUG]  The session field in the cookie  will be deleted

### ISSUE THREAD

**Issue by yuzhaopeng** [apache/shenyu#4495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In http requests, if a cookie contains a field named session, the sessoin is forcibly set to null in the response , then The http login status is lost

![image](https://user-images.githubusercontent.com/16642861/226530886-ff8bda8d-e5e0-4a24-ae15-603cf03e0d5d.png)

### Expected Behavior

session is not deleted

### Environment

```markdown
ShenYu version(s):2.5.1-SNAPSHOT
```

**Comment by yu199195** [comment]
response header have this filed？

**Comment by yuzhaopeng** [comment]
> 

 the original response header does't have this filed, appended after passing through the shenyu gateway

**Comment by yu199195** [comment]
how it is？

> the original response header does't have this filed, appended after passing through the shenyu gateway

**Comment by yuzhaopeng** [comment]
1. 我们的系统逻辑是这样，首先用户登录，登录成功后，会将session字段写入到cookie中
2. 然后用户每次请求时候将这个session字段通过cookie带到后端，后端用于身份验证
3. 但是经过shenyu网关代理之后，发现当用户的请求头中如果有session字段，那么经过shenyu的http响应就会把这个session字段置空
4. 目前观察到的现象就是只有cookie中的字段名为session时会这样，cookie中的其他字段不受影响

**Comment by yuzhaopeng** [comment]
I guess we found the problem ，After the  spring 5.0 ，add a  `WebSessionManager` ,
The `WebSessionManager`  looks for the session field in the cookie to determine if the session has expired ，
and our backend service also uses the same session field in the cookie. 

![image](https://user-images.githubusercontent.com/16642861/227136001-8289d0f3-a3f8-4a41-b4b7-e8721206c728.png)

**Comment by guoliang3** [comment]
我也遇到了同样的问题 请问如何处理的
@yuzhaopeng
