### ISSUE TITLE
[BUG] After an http request passes through the  shenyu,  the response header “set-cookie”  will  be repeated

### ISSUE THREAD

**Issue by yuzhaopeng** [apache/shenyu#4497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1.  Only the divide plug-in is enabled
2. When a request passes through the gateway proxy, duplicate "set-cookies" appear in the response header returned.

![image](https://user-images.githubusercontent.com/16642861/227154590-9295418b-51bb-4c54-96e2-0583ac7886a6.png)

### Expected Behavior

The response header has only one set-cookie

### Environment

```markdown
ShenYu version(s): 2.5.1
```

**Comment by yu199195** [comment]
duplicate header ？

**Comment by yuzhaopeng** [comment]
right

**Comment by yuzhaopeng** [comment]
only “set-cookie” response header

**Comment by moremind** [comment]
this has been fixed in #5190
