### ISSUE TITLE
[BUG] <Query failed because there are too many rules>

### ISSUE THREAD

**Issue by zongmingzhi** [apache/shenyu#4498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

rule_condition There are more than 30000 data in the table，
<img width="1512" alt="image" [](src="https://user-images.githubusercontent.com/95121549/227154317-160fb9af-b99c-454f-9ce4-28ccd3df504d.png">),
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/95121549/227155160-844be28b-0658-4753-84b1-afefa9cde950.png">

,Errors will be reported here

### Environment

```markdown
ShenYu version(s):2.5.1
```

### Debug logs

[shenyu-admin-error.log](https://github.com/apache/shenyu/files/11049123/shenyu-admin-error.log)

**Comment by yu199195** [comment]
why have  more than 30000 data in the table？

**Comment by zongmingzhi** [comment]
> why have more than 30000 data in the table？

Because there are a lot of services proxied with gateways

**Comment by zongmingzhi** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/95121549/227401143-f0011e06-ebfd-402a-a80a-7becf816087d.png">
