### ISSUE TITLE
[Question] Consider compatibility adjacent slashes.

### ISSUE THREAD

**Issue by iwangjie** [apache/shenyu#4508]
### Question

RFC 3986 said:

If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character. If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//"). In addition, a URI reference (Section 4.1) may be a relative-path reference, in which case the first path segment cannot contain a colon (":") character. The ABNF requires five separate rules to disambiguate these cases, only one of which will match the path substring within a given URI reference. We use the generic term "path component" to describe the URI substring matched by the parser to one of these rules.

---
But Tomcat and Nginx, as a high-occupancy web container, violates the constraint

![image](https://user-images.githubusercontent.com/23075587/228404174-d7f693df-450e-47da-9f45-a6faf83de7ed.png)

**Whether or not Shenyu as a gateway needs to tolerate this has improved compatibility and less surprise, helping the corporate infrastructure group to keep the“Non-canonical” writing of business systems unchanged, i think this is necessary because violating this specification is less costly for a company with many existing services than complying with it, and we should be lenient, right?**

**If this is necessary, please assign it to me🙋🏻‍♀️ and I will support it.**

**Comment by yu199195** [comment]
@iwangjie hi，looks to you pr~
