### ISSUE TITLE
[BUG] Rules Config Enable not active

### ISSUE THREAD

**Issue by justin-wick** [apache/shenyu#4511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i update Enable option to on or off, i have to restart shenyu bootstrap to make it effective

### Expected Behavior

tun off the selector or rules, let it take effect immediately

### Steps To Reproduce

1. login in admin dashboard
2. PluginList --> Mock --> Mock --> Modify
3. Turn off or turn on "Disable" Button

### Environment

```markdown
ShenYu version(s):2.5.1
```

### Debug logs

none

### Anything else?

besides:
Modify Rules, when Conditions select "request_method" ,the ui shows is different , added a "/" textbox

**Comment by moremind** [comment]
yes, I will focus on it.

**Comment by moremind** [comment]
@justin-wick this question is related to #4513，I have fixed it in https://github.com/apache/shenyu/pull/4515, you can use master branch after #4515 be merge or you can change it as follow:

```java
if (ruleData.getEnabled()) {
                if (CollectionUtils.isEmpty(ruleData.getBeforeConditionDataList())) {
                    eventPublisher.publishEvent(new RuleTrieEvent(RuleTrieEventEnum.INSERT, ruleData));
                } else {
                    // if rule data has before condition, update trie
                    eventPublisher.publishEvent(new RuleTrieEvent(RuleTrieEventEnum.UPDATE, ruleData));
                }
            } else {
                eventPublisher.publishEvent(new RuleTrieEvent(RuleTrieEventEnum.REMOVE, ruleData));
            }
````

**Comment by moremind** [comment]
It have fixed in #4515, please use shenyu 2.6.0 version, thanks for your response!

**Comment by moremind** [comment]
@justin-wick Hi, the bug has been fixed, I will close this comment, please use shenyu 2.6.0, if you have any questions, please reopen this issue.

**Comment by MaiSR9527** [comment]
> @justin-wick Hi, the bug has been fixed, I will close this comment, please use shenyu 2.6.0, if you have any questions, please reopen this issue.

When will version 2.6 be released

**Comment by moremind** [comment]
> > @justin-wick Hi, the bug has been fixed, I will close this comment, please use shenyu 2.6.0, if you have any questions, please reopen this issue.
> 
> When will version 2.6 be released

at least two months, shenyu-2.6.0 will be released from the master branch. currently, you can use master branch.
