### ISSUE TITLE
[Question] <isFull set true, "code": -119>

### ISSUE THREAD

**Issue by echojun186** [apache/shenyu#4514]
### Question

When isFull is set to true, Shenyu Gateway will report an error.

![image](https://user-images.githubusercontent.com/58423690/228558604-955e5f9b-eadc-453b-82fb-9b3daee72585.png)

![image](https://user-images.githubusercontent.com/58423690/228558761-d2b997a9-10ed-45b7-a6f2-3ffd403941f2.png)

![image](https://user-images.githubusercontent.com/58423690/228558672-1fea76a3-47c7-4c95-9d5f-2f427a6e3fcd.png)

Excuse me, what is wrong?

**Comment by moremind** [comment]
pls check divide rule.

**Comment by echojun186** [comment]
![image](https://user-images.githubusercontent.com/58423690/228714254-c17895c7-f923-4968-848e-2297712d0e6a.png)
The configuration during automatic registration has not been modified. Excuse me, is there any adjustment needed?

**Comment by yu199195** [comment]
checked divide selector

**Comment by echojun186** [comment]
![image](https://user-images.githubusercontent.com/58423690/228740814-7e52c71f-b8ce-4321-b103-354c7750e70e.png)
When isFull is set to true, it seems that some information about the service, such as IP address and port, is not automatically registered in the selector. Was this originally designed like this? Or where does it need to be configured? The current situation is that there are many services and environments, and each service has many controllers. It is unlikely to manually add ShenyuSpringMvcClient. The expectation is to fully proxy the service interface by setting isFull to true.

**Comment by echojun186** [comment]
![image](https://user-images.githubusercontent.com/58423690/228766128-13bd6c68-9fe9-4d29-a92e-dfae60dfa490.png)
After adding this line of code, the problem is resolved.
There is a suggestion as to whether a function can be added in the future; Exclude specified uris
THX

**Comment by peijxx** [comment]
have a repair plan？ we encountering the same problem

**Comment by moremind** [comment]
Hi, it will fix in #4681
