### ISSUE TITLE
[Task] shenyu rule cache test case

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#4517]
### Description

shenyu rule cache needs test cases including unit test and integration test

### Task List

* shenyu L1 cache test case
* shenyu L2(trie cache) test case

**Comment by lan-dian** [comment]
Hello, I really want to participate in shenyu's contribution. Could you please let me complete the corresponding task? I will be happy to do it. 😃

**Comment by moremind** [comment]
yes, I'm glad you're contributing to this issue, I will assign this task for you!

**Comment by moremind** [comment]
LGTM, thanks for your contributions!
