### ISSUE TITLE
[Question] <contextPath is changed>

### ISSUE THREAD

**Issue by echojun186** [apache/shenyu#4518]
### Question

When the contextPath is changed, such as changing from my-hen to shen-api, and restarting the service, the original contextPath my-shen can still access the service. Generally, my-hen no longer has a corresponding node and should not be accessible. It should be accessed through the new contextPath shen-api. Is this normal? How do I stop accessing the old contextPath? Where should I focus on the source code for registering an IP port to admin?

**Comment by moremind** [comment]
currently, if you change context-path, shenyu can't remove the selector and rule, if you want to remove it, you can focus on `shenyu-admin`, try to remove? about shenyu reigster client, maybe you can see `org.apache.shenyu.client.springmvc.init.SpringMvcClientEventListener`

**Comment by moremind** [comment]
can you fix it?

**Comment by moremind** [comment]
I know that shenyu register client cannot add a selector handle to the shenyu-admin, if you can wait a minute, I will fix it.

**Comment by echojun186** [comment]
thanks
