### ISSUE TITLE
[Task] refactor plugin-oauth2 plugin

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#4519]
### Description

shenyu support oauth2 plugin, but currently, most users can't use the oauth2 plugin rightly. we need add document in https://github.com/apache/shenyu-website and add oauth2 example.

### Task List

1. [ ] add document
2. [ ] add example and refactor code for example

**Comment by eskandaridanial** [comment]
Hi, I've made some changes to the Oauth documentation at[ shanyu-website]( https://github.com/apache/shenyu-website ) and created a pull request on it. It has more details on how to use the plugin now. Would you mind checking that out?

**Comment by moremind** [comment]
pls add my wechat:yijia1949

**Comment by moremind** [comment]
yes, I have checked the document, but can you check plugin-oauth2 code?

**Comment by eskandaridanial** [comment]
Ok, I may get this issue wrong so It's LGTY. Would you mind considering some more information? please.

**Comment by moremind** [comment]
> Ok, I may get this issue wrong so It's LGTY. Would you mind considering some more information? please.

I think the document of oauth2-plugin is right, but have you tested it for oauth2-plugin? if you have tested, I will close this issue.

**Comment by moremind** [comment]
> > Ok, I may get this issue wrong so It's LGTY. Would you mind considering some more information? please.
> 
> I think the document of oauth2-plugin is right, but have you tested it for oauth2-plugin? if you have tested, I will close this issue.

shenyu lack of oauth2-plugin test cases in `shenyu-integrated-test-http`, would you like add test case for oauth2?

**Comment by eskandaridanial** [comment]
> > > Ok, I may get this issue wrong so It's LGTY. Would you mind considering some more information? please.
> > 
> > 
> > I think the document of oauth2-plugin is right, but have you tested it for oauth2-plugin? if you have tested, I will close this issue.
> 
> shenyu lack of oauth2-plugin test cases in `shenyu-integrated-test-http`, would you like add test case for oauth2?

Yeah, I'll work on that and be back if faced any problems. Also If there are any points, please let me know.

**Comment by moremind** [comment]
> > > > Ok, I may get this issue wrong so It's LGTY. Would you mind considering some more information? please.
> > > 
> > > 
> > > I think the document of oauth2-plugin is right, but have you tested it for oauth2-plugin? if you have tested, I will close this issue.
> > 
> > 
> > shenyu lack of oauth2-plugin test cases in `shenyu-integrated-test-http`, would you like add test case for oauth2?
> 
> Yeah, I'll work on that and be back if faced any problems. Also If there are any points, please let me know.

I think the OAuth-plugin's code is error, do you want to rewrite the code?

**Comment by eskandaridanial** [comment]
I'd be happy. would you mind giving some details? what is the error? any info to reproduce?

**Comment by eskandaridanial** [comment]
> > > > > Ok, I may get this issue wrong so It's LGTY. Would you mind considering some more information? please.
> > > > 
> > > > 
> > > > I think the document of oauth2-plugin is right, but have you tested it for oauth2-plugin? if you have tested, I will close this issue.
> > > 
> > > 
> > > shenyu lack of oauth2-plugin test cases in `shenyu-integrated-test-http`, would you like add test case for oauth2?
> > 
> > 
> > Yeah, I'll work on that and be back if faced any problems. Also If there are any points, please let me know.
> 
> I think the OAuth-plugin's code is error, do you want to rewrite the code?

I'd be happy. would you mind giving some details? what is the error? any info to reproduce?
