### ISSUE TITLE
[Task] shenyu-client-spring-websocket test case 

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#4547]
### Description

Add test case for `shenyu-client-spring-websocket`

### Task List

1. [x] Add test case for `ShenyuServerEndpointerExporter` @pepsiss 
2. [x] Add test case for `SpringWebSocketClientEventListener` @pepsiss

**Comment by pepsiss** [comment]
Please assign it to me

**Comment by YxYL6125** [comment]
Can I help the tests with these two class 😄
