### ISSUE TITLE
[Question] <http(s)转发的对于同一域名挂在多个应用无法正常请求的问题>

### ISSUE THREAD

**Issue by wangpf09** [apache/shenyu#4554]
### Question

使用`http(s)`进行接口转发时，如现有一个`https://demo.com`的根域名，该域名下挂在多个应用，通过`nginx`进行服务转发，如应用 `aaa`，则访问应用路径为`https://demo.com/aaa`，应用`bbb`，则访问应用路径为`https://demo.com/bbb`，针对这种情况使用`shenyu`配置代理，通过代理地址进行访问时，则会出现`404 not found`的问题。请问这种情况有什么解决办法吗？

**Comment by yu199195** [comment]
pls in english
