### ISSUE TITLE
[Question] <The problem that http(s) forwarding cannot make normal requests for the same domain name linked to multiple applications>

### ISSUE THREAD

**Issue by wangpf09** [apache/shenyu#4555]
### Question

When using http(s) for interface forwarding, if there is a root domain name of https://demo.com, multiple applications are linked under this domain name, and the service forwarding is performed through nginx. For example, the application aaa, the access application path is https ://demo.com/aaa, apply bbb, then access the application path to https://demo.com/bbb, use shenyu to configure the proxy in this case, when accessing through the proxy address, 404 not found will appear question. Is there any solution to this situation?

**Comment by yu199195** [comment]
can config  multiple divide selector,

**Comment by wangpf09** [comment]
> can config multiple divide selector,

The configuration will not take effect, and the request returns 404
