### ISSUE TITLE
[BUG] <title> shenyu.file.maxSize config 

### ISSUE THREAD

**Issue by yuejq** [apache/shenyu#4558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

shenyu.file.maxSize Larger than 2047 
example 2048

### Expected Behavior

file upload succcess 

### Steps To Reproduce

1.shenyu.file.maxSize Larger than 2047 
2.test file upload
3.response body :{code: 403,message: "Pavload too large!' data: null}

### Environment

```markdown
ShenYu version(s):2.4.3
```

### Debug logs

{code: 403,message: "Pavload too large!' data: null}

### Anything else?

Filter Configuration#
shenyu.file config
File filter properties.
Name	Type	Default	Required	Description
enabled	Boolean	false	No	enable file size filtering
maxSize	Integer	10	No	upload file maxSize （MB）

**Comment by comeCU** [comment]
This is my first time debugging webflux, here should return error msg but return null.
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/30254171/232237856-d869d18f-c6de-49c2-b475-b3a207b05821.png">

**Comment by peng-heng** [comment]
maybe you can change this config.
shenyu:
  file:
    max-size: 2048

**Comment by yuejq** [comment]
This issue is caused by the field type Integer, where the maximum value of Integer is 2147483647, which is equivalent to 2047.999999 Mb. If the configuration is set as 2048 Mb, the system will automatically change it to a negative number.

**Comment by yuejq** [comment]
`public class FileSizeFilter implements WebFilter {
 
    private static final int BYTES_PER_MB = 1024 * 1024;
    private final int fileMaxSize;

 

    @Override
    @NonNull
    public Mono<Void> filter(@NonNull final ServerWebExchange exchange, @NonNull final WebFilterChain chain) {
        MediaType mediaType = exchange.getRequest().getHeaders().getContentType();
        if (MediaType.MULTIPART_FORM_DATA.isCompatibleWith(mediaType)) {
            ServerRequest serverRequest = ServerRequest.create(exchange,  messageReaders);
            return serverRequest.bodyToMono(DataBuffer.class)
                    .flatMap(dataBuffer -> {
                        **_if (dataBuffer.capacity() > BYTES_PER_MB * fileMaxSize) {_**    
                            ServerHttpResponse response = exchange.getResponse();
                            response.setStatusCode(HttpStatus.BAD_REQUEST);
                            Object error = ShenyuResultWrap.error(exchange, ShenyuResultEnum.PAYLOAD_TOO_LARGE);
                            LOG.info("The file size exceeds the limit. The actual size is {}M , response:{}", dataBuffer.capacity() / BYTES_PER_MB, error);
                            return WebFluxResultUtils.result(exchange, error);
                        }
                        BodyInserter<Mono<DataBuffer>, ReactiveHttpOutputMessage> bodyInsert = BodyInserters.fromPublisher(Mono.just(dataBuffer), DataBuffer.class);
                        HttpHeaders headers = new HttpHeaders();
                        headers.putAll(exchange.getRequest().getHeaders());
                        headers.remove(HttpHeaders.CONTENT_LENGTH);
                        CachedBodyOutputMessage outputMessage = new CachedBodyOutputMessage(
                                exchange, headers);
                        return bodyInsert.insert(outputMessage, new BodyInserterContext())
                                .then(Mono.defer(() -> {
                                    ServerHttpRequest decorator = decorate(exchange, outputMessage);
                                    return chain.filter(exchange.mutate().request(decorator).build());
                                })).doFinally(signalType -> DataBufferUtils.release(dataBuffer))
                                .onErrorResume((Function<Throwable, Mono<Void>>) throwable -> ResponseUtils.release(outputMessage, throwable));
                    });
        }
        return chain.filter(exchange);

    }
}`
