### ISSUE TITLE
Apache shenyu v2.5.1 has SPEL expression injection vulnerability, allowing attackers to execute arbitrary system commands

### ISSUE THREAD

**Issue by wudijun** [apache/shenyu#4559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Apache shenyu version 2.5.1 has added SPEL expressions, which allow attackers to enter malicious SPEL to execute arbitrary system commands

### Expected Behavior

Security filtering is recommended for SPEL expressions

### Steps To Reproduce

In version 2.5.1, the Mock plugin has been added and supports SPEL expression functionality, which creates a security issue that allows attackers to execute arbitrary system commands through SEPL expressions

![image](https://user-images.githubusercontent.com/95115088/232279882-7d4a73af-6375-4c32-947f-175422b452c4.png)

1.Create a new selector at Mock

![image](https://user-images.githubusercontent.com/95115088/232280095-f12af80b-2517-46e7-a167-d484cf7cbb02.png)

2.Create a new corresponding rule and enter a malicious SPEL expression here with the content of ${expression | T (java. lang. Runtime). getRuntime(). exec ("calc. exe")}

![image](https://user-images.githubusercontent.com/95115088/232280214-e606830f-6a24-4a73-9ac0-f7173d2bc2a9.png)

3.Click to confirm and access the corresponding URL

Click the Confirm button, and after visiting the corresponding path, you can see that the calculator has successfully popped up. The same is true for Linux systems, attackers can execute arbitrary system commands in this way，It is recommended to filter here

![image](https://user-images.githubusercontent.com/95115088/232280492-8b20e675-13af-45f9-a90d-467f849173b0.png)

![image](https://user-images.githubusercontent.com/95115088/232280533-99fb2698-169b-4caf-863d-bdad696cf7ad.png)

### Environment

```markdown
ShenYu version(s):2.5.1
```

**Comment by yu199195** [comment]
I think it depends on how the user uses.

**Comment by wudijun** [comment]
> I think it depends on how the user uses

> 我认为这取决于用户如何使用。

Hello, I don't understand this. However, an attacker can manually add malicious rules after logging in to the server in web mode and obtain the permission of the server in this way. I think you can filter the parameters a little bit, for example filtering out exec

**Comment by yu199195** [comment]
why can  logging in to the server in web mode？

> Hello, I don't understand this. However, an attacker can manually add malicious rules after logging in to the server in web mode and obtain the permission of the server in this way. I think you can filter the parameters a little bit, for example filtering out exec

**Comment by wudijun** [comment]
> why can logging in to the server in web mode？ filtering out exec？ Isn't there anything else?
> 
> > Hello, I don't understand this. However, an attacker can manually add malicious rules after logging in to the server in web mode and obtain the permission of the server in this way. I think you can filter the parameters a little bit, for example filtering out exec


What I mean is that after the attacker logs in to shenyu through the web, this operation is used to execute system commands to obtain server permissions for deploying shenyu. Exec is filtered because the exec function in the Runtime class can execute system commands

**Comment by wudijun** [comment]
> why can logging in to the server in web mode？ filtering out exec？ Isn't there anything else?
> 
> > Hello, I don't understand this. However, an attacker can manually add malicious rules after logging in to the server in web mode and obtain the permission of the server in this way. I think you can filter the parameters a little bit, for example filtering out exec

Or replace the default StandardEvaluationContext with SimpleEvaluationContext

**Comment by wudijun** [comment]
> why can logging in to the server in web mode？ filtering out exec？ Isn't there anything else?
> 
> > Hello, I don't understand this. However, an attacker can manually add malicious rules after logging in to the server in web mode and obtain the permission of the server in this way. I think you can filter the parameters a little bit, for example filtering out exec

What I mean is that if an attacker logs in to shenyu through the web, he can execute system commands in this way and obtain the authority of the server where shenyu is deployed. For specific filtering, I just gave an example, you can go to see similar cases

**Comment by yu199195** [comment]
I can see your point, I'm a bit curious if SPEL can't be used for any project? What else needs to be excluded besides .execc?

> What I mean is that if an attacker logs in to shenyu through the web, he can execute system commands in this way and obtain the authority of the server where shenyu is deployed. For specific filtering, I just gave an example, you can go to see similar cases
