### ISSUE TITLE
actuator健康检查

### ISSUE THREAD

**Issue by lixianli1987** [apache/shenyu#4563]
### Question

http://localhost:9195/actuator
通过如上接口，如何返回健康检查的所有端点
希望返回如下信息
`
{
	"_links": {
		"self": {
			"href": "http://localhost:9195/actuator",
			"templated": false
		},
		"beans": {
			"href": "http://localhost:9195/actuator/beans",
			"templated": false
		},
		"caches-cache": {
			"href": "http://localhost:9195/actuator/caches/{cache}",
			"templated": true
		},
		"caches": {
			"href": "http://localhost:9195/actuator/caches",
			"templated": false
		},
		"health-path": {
			"href": "http://localhost:9195/actuator/health/{*path}",
			"templated": true
		},
		"health": {
			"href": "http://localhost:9195/actuator/health",
			"templated": false
		},
		"info": {
			"href": "http://localhost:9195/actuator/info",
			"templated": false
		},
		"conditions": {
			"href": "http://localhost:9195/actuator/conditions",
			"templated": false
		},
		"shutdown": {
			"href": "http://localhost:9195/actuator/shutdown",
			"templated": false
		},
		"configprops": {
			"href": "http://localhost:9195/actuator/configprops",
			"templated": false
		},
		"configprops-prefix": {
			"href": "http://localhost:9195/actuator/configprops/{prefix}",
			"templated": true
		},
		"env": {
			"href": "http://localhost:9195/actuator/env",
			"templated": false
		},
		"env-toMatch": {
			"href": "http://localhost:9195/actuator/env/{toMatch}",
			"templated": true
		},
		"logfile": {
			"href": "http://localhost:9195/actuator/logfile",
			"templated": false
		},
		"loggers-name": {
			"href": "http://localhost:9195/actuator/loggers/{name}",
			"templated": true
		},
		"loggers": {
			"href": "http://localhost:9195/actuator/loggers",
			"templated": false
		},
		"heapdump": {
			"href": "http://localhost:9195/actuator/heapdump",
			"templated": false
		},
		"threaddump": {
			"href": "http://localhost:9195/actuator/threaddump",
			"templated": false
		},
		"metrics": {
			"href": "http://localhost:9195/actuator/metrics",
			"templated": false
		},
		"metrics-requiredMetricName": {
			"href": "http://localhost:9195/actuator/metrics/{requiredMetricName}",
			"templated": true
		},
		"scheduledtasks": {
			"href": "http://localhost:9195/actuator/scheduledtasks",
			"templated": false
		},
		"mappings": {
			"href": "http://localhost:9195/actuator/mappings",
			"templated": false
		}
	}
}
`

**Comment by yu199195** [comment]
pls in english.
