### ISSUE TITLE
插件加载优先级和描述不一致

### ISSUE THREAD

**Issue by zhongyongpei** [apache/shenyu#4571]
### Question

官方文档描述:
优先级 ：-Dplugin-ext=xxxx > shenyu.extPlugin.path > ext-lib(default)
来源:https://shenyu.apache.org/zh/docs/developer/custom-plugin

实际代码处理
public static String getPluginPath(final String path) {
        if (StringUtils.isNotEmpty(path)) {
            return path;
        }
        String pluginPath = System.getProperty(PLUGIN_PATH);
        if (StringUtils.isNotEmpty(pluginPath)) {
            return pluginPath;
        }
        URL resource = ShenyuPluginPathBuilder.class.getResource(DEFAULT_EXT_PLUGIN_PATH);
        return Optional.ofNullable(resource).map(URL::getPath).orElse(DEFAULT_EXT_PLUGIN_PATH);
    }

变成了 shenyu.extPlugin.path 优先了

**Comment by yu199195** [comment]
pls  in  english
