### ISSUE TITLE
[BUG] <Using the Divide plugin to proxy WMS service status code 400>

### ISSUE THREAD

**Issue by zongmingzhi** [apache/shenyu#4573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the Divide plugin to proxy WMS service status code 400, the original address is in normal use
originalUrl：http://115.236.184.59:26160/igs/rest/ogc/doc/%E9%87%91%E5%8D%8E%E5%B9%85/WMSServer

### Environment

```markdown
ShenYu version(s):
```

**Comment by yu199195** [comment]
whats version?  can you show log?

**Comment by zongmingzhi** [comment]
> whats version? can you show log?

2.5.1  No logs
