### ISSUE TITLE
[BUG] <missing primary key for table `alert_template` in schema.sql>

### ISSUE THREAD

**Issue by strawberry-crisis** [apache/shenyu#4574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The primary key definition for `alert_template` is missing.  When executing the script in MySQL@5.7, an error occurs with the message: "1075 - Incorrect table definition; there can be only one auto column and it must be defined as a key"

### Expected Behavior

the script can be executed without errors.

### Steps To Reproduce

1. local env
2. config spring profile to MySQL
3. execute schema.sql in MySQL@5.7
4. error occurs

### Environment

```markdown
ShenYu version(s):2.5.1
```

### Debug logs

-- ----------------------------
-- Table structure for alert_template
-- ----------------------------
CREATE TABLE IF NOT EXISTS `alert_template`
(
    `id`            bigint          NOT NULL AUTO_INCREMENT COMMENT 'primary key id',
    `name`          varchar(255)    NOT NULL COMMENT 'alert template name',
    `strategy_name` varchar(255)    NOT NULL COMMENT 'alert template strategy name',
    `content`       varchar(1000)   NOT NULL COMMENT 'alert template content',
    `date_created`  timestamp       NOT NULL DEFAULT now() COMMENT 'create time',
    `date_updated`  timestamp       NOT NULL DEFAULT now() COMMENT 'update time'
)

1075 - Incorrect table definition; there can be only one auto column and it must be defined as a key

**Comment by peng-heng** [comment]
tag: 2.5.1 
 it has defined the primary key
![image](https://github.com/apache/shenyu/assets/11962364/91cb7394-19a1-4c21-8e28-277128efdd6f)
