### ISSUE TITLE
[BUG] UpstreamCheckService#updateHandler endless loop

### ISSUE THREAD

**Issue by liukun321** [apache/shenyu#4609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

UpstreamCheckService#PENDING_SYNC is able to insert hashcode not in array of 'CommonUpstream',so that method of updateHandler will endless loop

### Expected Behavior

The hashcode that in PENDING_SYNC are in array of 'CommonUpstream'

### Environment

```markdown
ShenYu version(s):2.5.0
```

**Comment by yu199195** [comment]
in master , have this bug ?
