### ISSUE TITLE
[Volunteer]  Support for Kubernetes Service Discovery

### ISSUE THREAD

**Issue by yu199195** [apache/shenyu#4611]
### Volunteer help

Background

Apache ShenYu is a Java native API Gateway for service proxy, protocol conversion and API governance. Currently, ShenYu has good usability and performance in microservice scenarios. However, ShenYu's support for Kubernetes is still relatively weak.

Tasks

1. Support the registration of microservices deployed in K8s Pod to shenyu-admin and use K8s as the register center.
2. Discuss with mentors, and complete the requirements design and technical design of Shenyu K8s Register Center.
3. Complete the initial version of Shenyu K8s Register Center.
4. Complete the CI test of Shenyu K8s Register Center, verify the correctness of the code.
5. Write the necessary documentation, deployment guides, and instructions for users to connect microservices running inside the K8s Pod to ShenYu

Relevant Skills

1. Know the use of Apache ShenYu, especially the register center
2. Familiar with Java and Golang
3. Familiar with Kubernetes and can use Java or Golang to develop

Potential mentors:
Yonglun Zhang, mail: zhangyonglun (at) apache.org
Project Devs, mail: dev (at) shenyu.apache.org

**Comment by aFlyBird0** [comment]
Hello, I'm very interested in this idea! I have extensive experience with Shenyu's Helm chart and I'm more than happy to contribute to the cloud-native transformation of ShenYu! Thank you!

**Comment by yu199195** [comment]
already done～
