### ISSUE TITLE
[Volunteer] Add WasmPlugin

### ISSUE THREAD

**Issue by yu199195** [apache/shenyu#4612]
## Background

Apache ShenYu is a Java native API Gateway for service proxy, protocol conversion and API governance. Currently, ShenYu has good scalability in the Java language. However, ShenYu's support for multiple languages is still relatively weak.

The wasm bytecode is designed to be encoded in a size- and load-time-efficient binary format. WebAssembly aims to execute at native speed by taking advantage of common hardware capabilities available on a wide range of platforms.

The goal of WasmPlugin is to be able to run wasm bytecode([wasmer-java](https://github.com/wasmerio/wasmer-java) is a good choice, if you find a better choice, please discuss with me), and other languages can write ShenYu plugins based on this language(such as Rust/golang/C++) as long as they can be compiled into wasm bytecode.

More documents on wasm and WASI are as follows:
https://github.com/WebAssembly/design
https://github.com/WebAssembly/WASI

## Relevant Skills
Know the use of Apache ShenYu, especially the plugin
Familiar with Java and another language which can be compiled into wasm bytecode

## Task List
1.develop shenyu-wasm-plugin.
2.write integrated test for shenyu-wasm-plugin.
3.write wasm plugin documentation in shenyu-website.

Links:

website： https://shenyu.apache.org/

Difficulty: Major
Potential mentors:
ZiCheng Zhang, mail: zhangzicheng@apache.org
Project Devs, mail: dev@shenyu.apache.org

**Comment by runqi-zhao** [comment]
Hello, I'm very interested in this idea!  and I'm more than happy to contribute to ShenYu! Thank you!
