### ISSUE TITLE
[Question] The document of ‘code-suggestions’ is confusing

### ISSUE THREAD

**Issue by TulanCN** [apache/shenyu#4622]
### Question

When I read the document of ‘code-suggestions’ , I found that some examples are confusing.
Such as:
current : `return null == a.getB() ? null : a.getB().getC();`
recommendation : `return Optional.ofNullable(a.getB()).map(C::getD).orElse(null);`
current : `return null == a ? new B() : C.newD(a);`
recommendation : `return Optional.ofNullable(a).map(B::newC).orElse(new D());`

The code marked with the current and the code marked with the recommendation do not seem to match exactly.

**Comment by yu199195** [comment]
Hi, If you have found that you can fix it, follow the code-suggestions .
> The code marked with the current and the code marked with the recommendation do not seem to match exactly.

**Comment by TulanCN** [comment]
Sorry, I thought the document was also in this code repository (just like Spring Cloud Gateway), so I created an issue here, but now I realize that the document is in another code repository

And I have try to fix it.
current : `return null == a.getB() ? null : a.getB().getC();`
recommendation :`Optional.ofNullable(a.getB()).map(B::getC).orElse(null);`
current：`return null == a ? new B() : C.newD(a);`
recommendation : `return Optional.ofNullable(a).map(B::new).orElse(C.newD(a));`

I found these issues after a brief glance, maybe we need to recheck the [document](https://shenyu.apache.org/community/code-suggestions/#several-methods-to-judge-and-handle-null)？
And I am willing to make some contributions to this project.

**Comment by yu199195** [comment]
Hi,  Do you think there is something wrong with the documentation?   If so, you can fix it here ： https://github.com/apache/shenyu-website


>current : return null == a.getB() ? null : a.getB().getC();
recommendation :Optional.ofNullable(a.getB()).map(B::getC).orElse(null);
current：return null == a ? new B() : C.newD(a);
recommendation : return Optional.ofNullable(a).map(B::new).orElse(C.newD(a));
