### ISSUE TITLE
[Question] PluginList当中jwt/sgin/springcloud的Enable关闭无法实时生效

### ISSUE THREAD

**Issue by longhu735** [apache/shenyu#4626]
### Question

系统版本：2.5.1
涉及模块：PluginList> Authentication || Proxy >RulesList
测试场景：网关启动时，插件当中的RulesList均开启
问题描述：RulesList的Enable设置为关闭，插件功能依旧可以正常使用，既是点击Sycnhronous也无效，唯一解决办法就是重启网关。
以上是我这边涉及到的插件，其他插件并未去做详细测试，不过感觉所有插件应该都有问题。
所以对于该字段的机制，还请帮忙解答一下，是否是故意为之？

**Comment by yu199195** [comment]
pls  in  english~

**Comment by mxyyyy** [comment]
+1, to many bug in v2.5.1
