### ISSUE TITLE
[BUG] Authentication  The edit operation cannot add a new resource path

### ISSUE THREAD

**Issue by peng-heng** [apache/shenyu#4628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/apache/shenyu/assets/11962364/d0ac498a-9ed5-4088-a3f2-9a51c357d506)

### Environment

```markdown
ShenYu version(s): 2.4.3
```

### Debug logs

![image](https://github.com/apache/shenyu/assets/11962364/46ebf401-e89b-45c4-89c8-086c059c5453)

**Comment by yu199195** [comment]
maybe need upgrade to 2.5.x
