### ISSUE TITLE
[BUG] when use HttpLongPollingDataChangedListener ,ConfigController perhaps not loaded.

### ISSUE THREAD

**Issue by peng-heng** [apache/shenyu#4629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when use HttpLongPolling sync configs from shenyu-admin。
the bean of ConfigController perhaps not loaded.
the bean of HttpLongPollingDataChangedListener is loaded after the bean of  ConfigController
![img_v2_22d07d5e-af8d-4247-91e0-f99a29d156cg](https://github.com/apache/shenyu/assets/11962364/c8c9f93b-93e4-4cfb-b7bc-b3577c3f649e)

### Expected Behavior

Ensure that the loading order of classes remains HttpLongPollingDataChangedListener  before ConfigController

### Environment

```markdown
ShenYu version(s): 2.4.3
```

**Comment by yu199195** [comment]
can you fix it？

**Comment by peng-heng** [comment]
i will make a pr to fix it.
