### ISSUE TITLE
I I didn't understand this synchronized custom divide. Please explain its purpose or usage scenarios. Thank you

### ISSUE THREAD

**Issue by Summary-wcj** [apache/shenyu#4656]
### Question

I didn't understand this synchronized custom divide. Please explain its purpose or usage scenarios. Thank you
![image](https://github.com/apache/shenyu/assets/34983781/4b8f1359-801c-4089-989f-73ebd6e0656d)

My current understanding is to refresh the list below, but I feel that something is wrong

**Comment by moremind** [comment]
just sync your data when losing data

**Comment by Summary-wcj** [comment]
> 丢失数据时只需同步数据

When I used Zookeeper to synchronize data, the control printed this error message. Is this normal?
<img width="1100" alt="a5606cfd90f529080bd8036f63b2118" src="https://github.com/apache/shenyu/assets/34983781/9a2e57df-9a9f-4c09-b218-a997cbb8af4f">
<img width="782" alt="0174f82cb267c5d52e55a04247b3e1b" src="https://github.com/apache/shenyu/assets/34983781/05c4e24d-7636-4633-93f2-2230694ce7c0">

**Comment by moremind** [comment]
> > 丢失数据时只需同步数据
> 
> When I used Zookeeper to synchronize data, the control printed this error message. Is this normal? <img alt="a5606cfd90f529080bd8036f63b2118" width="1100" src="https://user-images.githubusercontent.com/34983781/240211173-9a2e57df-9a9f-4c09-b218-a997cbb8af4f.png"> <img alt="0174f82cb267c5d52e55a04247b3e1b" width="782" src="https://user-images.githubusercontent.com/34983781/240211194-05c4e24d-7636-4633-93f2-2230694ce7c0.png">

which version?

**Comment by Summary-wcj** [comment]
> 

2.6.0
When this issue occurred, the testing on the master branch was initiated

**Comment by moremind** [comment]
> > 
> 
> 2.6.0 When this issue occurred, the testing on the master branch was initiated

thanks for your feedback, it may be a bug, can you fix it?
