### ISSUE TITLE
[BUG] Have a  bug  in AbstractDubboPluginDataHandler.

### ISSUE THREAD

**Issue by luochenyu1996** [apache/shenyu#4665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Start two instances of TestApacheDubboApplication ;
Open gray button in selector
  

### Expected Behavior

Close  gray Button in selector

### Environment

```markdown
ShenYu version(s):master
```

### Debug logs

 As blew picture and code , when close  gray button ,  the cache  can't clear.
<img width="1257" alt="image" src="https://github.com/apache/shenyu/assets/87219757/6df2ce31-2667-4906-8229-84e75108400f">

**Comment by moremind** [comment]
can you fix it?
