### ISSUE TITLE
Questions about the JWT plugin 

### ISSUE THREAD

**Issue by mxyyyy** [apache/shenyu#4666]
### Question

If we wanna integrate our user center and acl system into Shenyu, like intercepting requests and using rpc for authentication and authorization, do we need new plugins or can we use the existing ones? Not sure if the jwt plugin works for that. Docs don't have much info. Like, if I decode the jwt token, how do I pass the user context to downstream services? And where do I get the credentials for issuing the jwt token? If there are clearer diagrams or docs, please send 'em. Thanks!

**Comment by peng-heng** [comment]
I think the jwt plugin can meet your requirements. You can take a look at this test case.
org.apache.shenyu.plugin.jwt.handle.JwtPluginDataHandlerTest#testHandlerRule

it Will be added to the header based on the handle.
![image](https://github.com/apache/shenyu/assets/11962364/852e83da-a1bc-4d5d-854c-ca94c31455b3)

**Comment by moremind** [comment]
yes, jwt plugin can do this, jwt plugin has a convert field, so you can config this field, and the field can transfer jwt body to exchange header. jwt plugin converter coonfig like this:
```json
{"convert": [{"jwtVal": "userId", "headerVal": "currentUserId"}]}
```

if you want to implement this converter, pls see: https://shenyu.apache.org/zh/docs/developer/custom-jwt-covert-algorithm

**Comment by moremind** [comment]
> yes, jwt plugin can do this, jwt plugin has a convert field, so you can config this field, and the field can transfer jwt body to exchange header. jwt plugin converter coonfig like this:
> 
> ```json
> {"convert": [{"jwtVal": "userId", "headerVal": "currentUserId"}]}
> ```
> 
> if you want to implement this converter, pls see: https://shenyu.apache.org/zh/docs/developer/custom-jwt-covert-algorithm

@mxyyyy I think you can run admin and bootstrap and example-http with jwt plugin

**Comment by shnuwl007** [comment]
> > yes, jwt plugin can do this, jwt plugin has a convert field, so you can config this field, and the field can transfer jwt body to exchange header. jwt plugin converter coonfig like this:
> > ```json
> > {"convert": [{"jwtVal": "userId", "headerVal": "currentUserId"}]}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > if you want to implement this converter, pls see: https://shenyu.apache.org/zh/docs/developer/custom-jwt-covert-algorithm
> 
> @mxyyyy I think you can run admin and bootstrap and example-http with jwt plugin

I think the config should like this: {"converter": [{"jwtVal": "sub", "headerVal": "user-id"}]}, because JwtRuleHandleTest.java in the project are written like this

**Comment by shnuwl007** [comment]
I used jwt and divide plugin, my http request was successfully validated by the jwt plug, and the jwt body has the sub field, but when the divide plugin forwarded the request to my other service, it couldn't find the user-id in the header, does anyone know what caused it? thanks.
