### ISSUE TITLE
[Task] SpringCloudLocalCache task

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#4680]
### Description

currently, eureka and nacos has a local cache for service instance,but zookeeper and consul must get node from registry. when can build a local cache for springcloud plugin.

### Task List

1. listener heartbeat and get instances from the registry.
2. when selector initializing, get instances from the registry.
3. add unit test for the local cache

**Comment by damonxue** [comment]
pls assign 2 me.

**Comment by eurecalulu** [comment]
Please assign consul to me
