### ISSUE TITLE
example-grpc is wrong in website

### ISSUE THREAD

**Issue by Layfolk-zcy** [apache/shenyu#4708]
### Question

websit： https://shenyu.apache.org/zh/docs/quick-start/quick-start-grpc

![image](https://github.com/apache/shenyu/assets/59356890/1323e8b5-5be0-4748-99a8-4faf9fb8a606)
![image](https://github.com/apache/shenyu/assets/59356890/d0547fc9-0512-467f-898c-5a9130c4b754)
![image](https://github.com/apache/shenyu/assets/59356890/76517808-eafd-4182-9329-47ef1ac92bcd)
![image](https://github.com/apache/shenyu/assets/59356890/d1be0b50-3e62-46a3-93df-bda5f6804465)

**Comment by yu199195** [comment]
Run grpc demo ，have register metadata in shenyu admin？

**Comment by Layfolk-zcy** [comment]
> Run grpc demo ，have register metadata in shenyu admin？

![image](https://github.com/apache/shenyu/assets/59356890/4c797120-78e5-47a2-86a6-878b407c440b)

 grpc meta data is empty in the meta_data table
![image](https://github.com/apache/shenyu/assets/59356890/fdbf6470-a954-46b9-94b6-dd3501d75377)

**Comment by Layfolk-zcy** [comment]
2.5.1-shenyu is ok. my version is 2.5.0 in the problem

**Comment by Layfolk-zcy** [comment]
postman call wrong
![image](https://github.com/apache/shenyu/assets/59356890/9391db75-8892-4cac-bc21-38676a85e24e)
![image](https://github.com/apache/shenyu/assets/59356890/c6b5eb25-ae47-4abc-89ef-00df43c0d912)
![image](https://github.com/apache/shenyu/assets/59356890/3cc1a823-16c8-45cc-a6a5-42752f804dbc)
