### ISSUE TITLE
[BUG] shenyuAdmin can't update Authentication's UserId

### ISSUE THREAD

**Issue by BrdgYin** [apache/shenyu#4711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

1. open shenyuAdmin
2. generate an appKey and appSecret
3. update UserId

### Environment

```markdown
ShenYu version(s):2.5.0
```

### Debug logs

    <update id="update" parameterType="org.apache.shenyu.admin.model.entity.AppAuthDO">
        UPDATE app_auth
           SET
               app_secret = #{appSecret, jdbcType=VARCHAR},
               phone = #{phone, jdbcType=VARCHAR},
               ext_info = #{extInfo, jdbcType=VARCHAR},
               open = #{open, jdbcType=TINYINT},
               enabled = #{enabled, jdbcType=TINYINT}
         WHERE id = #{id, jdbcType=VARCHAR}
    </update>

not write user_id

**Comment by whenelse** [comment]
I found this bug has been fixed, can it be closed?
