### ISSUE TITLE
[Question] <title>shenyu2.4.3版本 Report a jsonObject exception when an object contains a variable of type List

### ISSUE THREAD

**Issue by wanghe88** [apache/shenyu#4746]
### Question

post===>http://localhost:9195/dubbo/saveComplexBeanTest
params==>{
  "dubboTest": [{
    "id": "123",
    "name": "test"
  }],
  "idLists": [
    "456",
    "124"
  ],
  "idMaps": {
    "abc": "abc",
    "cbd": "cbd"
  }
}  会抛出UnsupportedOperationException异常

GsonUtils方法jsonArrayToListInConvertToMap是有问题的

修改成：
private List<Object> jsonArrayToListInConvertToMap(final JsonArray jsonArray) {
        List<Object> list = new ArrayList<>(jsonArray.size());
        for (JsonElement jsonElement : jsonArray) {
            if (jsonElement.isJsonNull()) {
                list.add(null);
                continue;
            }
            String objStr = jsonElement.toString();
            if (objStr.startsWith(LEFT_ANGLE_BRACKETS) && objStr.endsWith(RIGHT_ANGLE_BRACKETS)) {
                list.add(convertToMap(objStr));
            } else {
                String asString = jsonElement.getAsString();
                list.add(asString);
            }
        }

        return list;
    }

**Comment by fishguanhx** [comment]
ok

**Comment by fishguanhx** [comment]
我也遇到这个问题了，这样修改很好！！！

**Comment by fishguanhx** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
