### ISSUE TITLE
how to get the request params whit post body json

### ISSUE THREAD

**Issue by lixianli1987** [apache/shenyu#4757]
### Question

https://shenyu.apache.org/zh/docs/developer/custom-plugin
public class CustomPlugin extends AbstractShenyuPlugin {
    @Override    
    protected abstract Mono<Void> doExecute(ServerWebExchange exchange, ShenyuPluginChain chain, SelectorData selector, RuleData rule) {
       // how to get the request params whit post body json
      }
}
![图片](https://github.com/apache/shenyu/assets/14136245/16a40178-35bf-449f-8f73-1270e2e32e2b)

**Comment by moremind** [comment]
pls see modifyResponsePlugin or  loggingconsole plugin
