### ISSUE TITLE
[BUG] api document does't work

### ISSUE THREAD

**Issue by phj4516** [apache/shenyu#4779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the web request get the result. But it not show in web

### Expected Behavior

![image](https://github.com/apache/shenyu/assets/43701434/8eeb5184-a9e4-4c24-8aa4-8cc22c7ae1d4)
it should show in web.

### Steps To Reproduce

1.jdk 1.8
2.simple config
3.start bootstrap admin and a springcloud project
4.
![image](https://github.com/apache/shenyu/assets/43701434/1f557b0e-1c75-4d60-8182-e987c68522d4)
![image](https://github.com/apache/shenyu/assets/43701434/3e31d52c-8616-4e3d-b1c4-775cca8ee188)

### Environment

```markdown
ShenYu version(s):2.5.1
```

### Debug logs

![image](https://github.com/apache/shenyu/assets/43701434/9828f53a-61b0-4bbd-8f9d-6319eae219ef)
it has value in cache

### Anything else?

nothing

**Comment by lianjunwei** [comment]
Version 2.5.1 is not supported. The next version to be released will be re supported.

**Comment by lianjunwei** [comment]
After waiting for the front-end pr, completely fix it.
