### ISSUE TITLE
mvn install fail

### ISSUE THREAD

**Issue by xuziyang** [apache/shenyu#4796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Environment

Problem：
Compile the project according to the documentation, and execute mvn install failed, as shown below：

![image](https://github.com/apache/shenyu/assets/8465969/0674d2c7-e432-4d15-bf8f-174c82576133)
![image](https://github.com/apache/shenyu/assets/8465969/bcec7088-464f-4795-bc80-f0ecc3e2c67d)

### Environment

```markdown
OS：win11 
Terminal： PowerShell
```

### Anything else?

The problem is actually related to how you are launching the Maven command. In Windows Powershell, [the dot . has a special meaning], so it gets interpreted.

**Comment by xuziyang** [comment]
Can you tell me how to modify the document and I can fix it

**Comment by xuziyang** [comment]
The problem is actually related to how you are launching the Maven command. In Windows Powershell, [the dot . has a special meaning], so it gets interpreted.

**Comment by xuziyang** [comment]
[INFO] shenyu-admin-dist .................................. SKIPPED
[INFO] shenyu-bootstrap-dist .............................. SKIPPED
[INFO] shenyu-docker-compose-dist ......................... SKIPPED
[INFO] shenyu-alert ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.903 s
[INFO] Finished at: 2023-07-04T20:38:13+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Unknown lifecycle phase ".javadoc.skip=true". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhaseNotFoundException

**Comment by yu199195** [comment]
run   mvn clean install  in Windows Powershell

**Comment by xuziyang** [comment]
> The problem is actually related to how you are launching the Maven command. In Windows Powershell, [the dot . has a special meaning], so it gets interpreted.

I think a better way is to change the command to:    
mvn clean install '-Dmaven.javadoc.skip=true' '-B' '-Drat.skip=true' '-Djacoco.skip=true' '-DskipITs' '-DskipTests'

I have submitted a related pr.
