### ISSUE TITLE
[Question] <shenyu-admin modify the rule sync gateway error>

### ISSUE THREAD

**Issue by LBJWt** [apache/shenyu#4798]
### Question

`org.apache.shenyu.plugin.divide.handler.DividePluginDataHandler#handlerRule`
```
public void handlerRule(final RuleData ruleData) {
        Optional.ofNullable(ruleData.getHandle()).ifPresent(s -> {
            DivideRuleHandle divideRuleHandle = GsonUtils.getInstance().fromJson(s, DivideRuleHandle.class);
            CACHED_HANDLE.get().cachedHandle(CacheKeyUtils.INST.getKey(ruleData), divideRuleHandle);
            // the update is also need to clean, but there is no way to
            // distinguish between crate and update, so it is always clean
            MetaDataCache.getInstance().clean();
        });
    }
```
The ruleData.getHandle() here is a list pushed from the shenyu-admin, which is received by a single object, and an exception will be reported here

**Comment by yu199195** [comment]
DivideRule can not config  list in  divide plugin

**Comment by LBJWt** [comment]
> DivideRule can not config list in divide plugin
but Rules  can config list

**Comment by LBJWt** [comment]
![image](https://github.com/apache/shenyu/assets/16012187/ba67846f-d72d-41c9-a912-71f295489dba)

**Comment by yu199195** [comment]
Rules not config list

**Comment by LBJWt** [comment]
![31fc6779f0c9a8a0593b7c733a111cf](https://github.com/apache/shenyu/assets/16012187/5ff8d227-6bb0-4ae6-9b21-5fb09f2a8fe1)


> Rules not config list

**Comment by moremind** [comment]
![image](https://github.com/apache/shenyu/assets/20184263/f6c7c109-e324-4f35-9b93-e1a5140257b6)
