### ISSUE TITLE
通过spring-cloud自动注册的接口，@PathVariable参数，网关提示107错误

### ISSUE THREAD

**Issue by aladingDenson** [apache/shenyu#4810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

请求地址：http://IP/system/supplier/viewCancelOrder/50
错误提示：
![2b14510dc81bbf194e70d52fb9110e3](https://github.com/apache/shenyu/assets/34641972/4a4b5a9b-936c-4360-b89f-b2c2ca10cbad)

### Expected Behavior

手动解决：登录网关，找到对应的spring-cloud rule规则，编辑修改位match匹配，然后点击同步后，回归正常。

### Steps To Reproduce

1.启动项目后自动登录网关.会自动注册新的接口到网关
2.通过网关访问@PathVariable接口，报错107
3.登录网关，找到对应的spring-cloud rule规则，编辑修改位match匹配，然后点击同步后
4.再次访问接口正常

### Environment

```markdown
ShenYu version(s):2.5.1
```

### Debug logs

建议考虑好 PathVariable 参数自动注册为match匹配

### Anything else?

建议考虑好 athVariable 参数自动注册为match匹配

**Comment by tian-pengfei** [comment]
The current version does not yet support automatic resolution of @PathVariable in RequestMapping. However, you can use the @ShenyuSpringCloudClient annotation from Shenyu to update the registration path.


![e47221a6ff04aae2b2b7905a7dd7be5](https://github.com/apache/shenyu/assets/42602026/83e90ddd-cd27-499d-ad38-631fd69e73e6)

**Comment by moremind** [comment]
currently, 2.5.1 version antMatch or path pattern maybe exist some questions that cause can't match because of shenyu-trie
