### ISSUE TITLE
[BUG]  <无法启动 shenyu-admin, 报 shiro配置读取为空的问题>

### ISSUE THREAD

**Issue by LeonGuo1** [apache/shenyu#4813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/apache/shenyu/assets/111328381/0bfe6ffb-396a-4990-be2a-b6fb3ce94af6)
![image](https://github.com/apache/shenyu/assets/111328381/11e74443-47e1-45a5-a932-42199fc639be)

环境
IntelliJ IDEA:  2023.1
Maven: 3.9.1
JVM:  1.8
Version: v2.5.1 Latest

是因为我启动 shenyu-admin 缺少一些其它配置吗？期待您的解答，多谢

### Environment

```markdown
ShenYu version(v2.5.1 Latest):
```

**Comment by 847850277** [comment]
Perhaps Maven's dependencies have not been downloaded completely. You can execute this command `./mvnw clean install -Dmaven.javadoc.skip=true` in the project root directory and try again after the command is executed

**Comment by yu199195** [comment]
pls in english

**Comment by LeonGuo1** [comment]
I have used ‘mvn clean install,’ but It doesn't work, both my colleagues and I can't run shenyu-admin. 
Thanks anyway, maybe I should try a lower version not the latest version
