### ISSUE TITLE
[BUG] NettyHttpClientPlugin call occur java.lang.NullPointerException.

### ISSUE THREAD

**Issue by wzhangNJ** [apache/shenyu#4839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

NettyHttpClientPlugin call occur 	java.lang.NullPointerException.

![image](https://github.com/apache/shenyu/assets/19465278/9f12b941-4e84-4099-a1f2-772cfebe9b27)

if acceptEncoding have  only  gzip，acceptEncoding is empty.

![image](https://github.com/apache/shenyu/assets/19465278/a57110ab-6c26-4d82-bbe8-d23dc31b4b9c)

### Expected Behavior

NO java.lang.NullPointerException.

### Environment

```markdown
ShenYu version(s):all
```

**Comment by azhsmesos** [comment]
`acceptEncoding = Stream.of(String.join(",", acceptEncoding).split(",")).collect(Collectors.toList());` 
<img width="934" alt="image" src="https://github.com/apache/shenyu/assets/65518067/b00647a0-f86d-44c2-b2c4-714cdadff806">
Is this line of code in the image above necessary?

**Comment by yu199195** [comment]
this code have problem， can you help fixed ？ @wzhangNJ @azhsmesos

**Comment by azhsmesos** [comment]
> this code have problem， can you help fixed ？ @wzhangNJ @azhsmesos

I can try to repair it, please assign it to me, thank you.

**Comment by wzhangNJ** [comment]
@azhsmesos cool
