### ISSUE TITLE
General requirements for Shenyu gateway

### ISSUE THREAD

**Issue by acticfox** [apache/shenyu#4862]
### Question

After using the Shenyu gateway, I have an urgent requirement. I would like to know if your official solution can fulfill it. I need to pass the client IP, TraceId, and JWT token obtained at the gateway side to the Dubbo service backend through the Dubbo RPCContext instead of passing them as regular parameters. Thank you.

**Comment by yunlongn** [comment]
You can use `GeneralContextPlugin` to achieve the functionality you want. 
In dubboRpc  . This data will be placed in RpcContext
