### ISSUE TITLE
i can't download dependency from maven repository 

### ISSUE THREAD

**Issue by chigend** [apache/shenyu#4871]
### Question

 in the sdk doc,  it mentions that shenyu gateway should refer this dependency, but i can not find it in maven repository, how can i reach it

<img width="864" alt="image" src="https://github.com/apache/shenyu/assets/19338606/e70984b6-3399-461b-b5a6-437698d98a84">

**Comment by daanhan** [comment]
Replace the version value with the last version  **2.5.1**
