### ISSUE TITLE
[Question] How to access the methods in LocalPluginController?

### ISSUE THREAD

**Issue by kikop** [apache/shenyu#4878]
### Question

How to access the methods in LocalPluginController?

I am based on Shenyu version v2.5.1

For example, Get method:/plugin/findByName

Public class LocalPluginController{

/**

*Find by name mono

*

*@ param name the name

*@ return the mono

*/

@GetMapping ("/plugin/findByName")

Public Mono<String>findByName (@ RequestParam ("name") final String name){

PluginData pluginData=BaseDataCache. getInstance(). obtainPluginData (name);

If (Objects. isnull (pluginData)){

Return Mono. just ("can't find this plugin:"+name);

}

Return Mono.just (JsonUtils. toJson (pluginData));

}

}

The order is as follows:

1. Start shenyu admin and shenyu bootstrap

2. Browser access

http://localhost:9195/shenyu/plugin/findByName?name=divide

3. It simply cannot enter the LocalPluginController method and was intercepted directly by AbstractShenyuPlugin, reporting the following error:

{

Code: -107,

Message ":" divide: Can't find selector, please check your configuration

}

**Comment by yu199195** [comment]
pls config this ：


```
shenyu
  local:
    enabled: true

```
