### ISSUE TITLE
[Question] need a simplest custom plugin description

### ISSUE THREAD

**Issue by daanhan** [apache/shenyu#4900]
### Question

I want to write a custom sign plugin, but failed when I follow the page [https://shenyu.apache.org/docs/developer/custom-plugin](url)
I think the menual need more optimization. The most urgent thing is to need a simplest and most complete solution.

Please help me improve this list, Thank you

1. Create a plugin project with a class impl ShenyuPlugin or extends AbstractShenyuPlugin. 
   named: mycustonplugin, order: 1, do nothing in doExcute method only print a log message.
2. put the plugin jar file into the ext-lib folder of Shenyu-Admin and Shenyu-Bootstrap
3. restart the Admin and Bootstrap app.
4. add plugin infomation in BasicConfig/Plugin at Shenyu-Admin
5. relogin the ShenYu-Admin
6. add Selector and Rule in PluginList page
7. curl http://localhost:9195/mycustomurl

When I complete those things , I can see the plugin is actived , but  I can not see any log message as I have wrote.

**Comment by ywj1352** [comment]
![image](https://github.com/apache/shenyu/assets/31105009/1bbb0dbc-9e9e-4e44-9540-2dc76b3ce5ba)
