### ISSUE TITLE
2.5.1版本，当我尝试通过源码自行打包时，发现不少的依赖冲突问题

### ISSUE THREAD

**Issue by xanaduliu** [apache/shenyu#4916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

通过2.5.1版本源码，自行打包shenyu-admin，发现包依赖冲突问题

### Expected Behavior

能否考虑处理一下这些依赖冲突

### Steps To Reproduce

如: spring-beans版本：
shenyu-admin -> reactor-spring -> spring-beans 为3.23版本
shenyu-admin -> spring-ldap-core -> spring-beans 为 4.3.27.RELEASE版本。

snakeyaml版本：
shenyu-admin -> spring-boot-starter -> snakeyaml 为1.29版本。
shenyu-admin -> nacos-client -> snakeyaml为1.23版本。

### Environment

```markdown
ShenYu version(s):2.5.1
```

**Comment by yu199195** [comment]
used english
