### ISSUE TITLE
[Volunteer] <title>shenyu-client add batch submission

### ISSUE THREAD

**Issue by wzhangNJ** [apache/shenyu#4969]
### Volunteer help

now shenyu-client register one by one，This will cause excessive pressure on the registration center and synch center. we Can design batch submission mode，reduce registration times and reduce synch times.

**Comment by xjlgod** [comment]
Hi, I would like to contribute to the community. But I noticed that the good first issue has been assigned completely. I am currently interested in this issue. Can you give me more hints or tell me where to look at the code details ?
