### ISSUE TITLE
[BUG] <SpringMvcClientEventListener#buildApiPath return error apiPath when registering method without @ShenyuSpringMvcClient>

### ISSUE THREAD

**Issue by iYaDongWang** [apache/shenyu#5004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/apache/shenyu/assets/38178396/26e264c8-17ed-4bbf-a4d1-5a207f5f6283)
![image](https://github.com/apache/shenyu/assets/38178396/49f32cce-ba8e-46bb-8084-2c01bf4f0ae5)

### Expected Behavior

The name of the rule registered to shenyu admin should be /http/oauth/authorize

### Steps To Reproduce

run module shenyu-examples-http

### Environment

```markdown
ShenYu version(s):2.6.1-SNAPSHOT
```

**Comment by moremind** [comment]
use this annotation with method

**Comment by iYaDongWang** [comment]
> use this annotation with method

I don't think it's a good idea to use `@ShenyuSpringMvcClient` everywhere. In fact, the implementation logic of the `SpringMvcClientEventListener#buildApiPath` function is that if the client annotation doesn't get the path, it will demote the requestMapping annotation to get the path. what causes the problem is that before calling this function, if the variable `methodShenyuClient `is null, it assigns the `beanShenyuClient` to the variable `methodShenyuClient`.

**Comment by moremind** [comment]
> a good idea to use `@ShenyuSpringMvcClient` everywhere. In fact, the implementation logic of the `SpringMvcClientEventListener#buildApiPath` function is that if the client

need discuss~
