### ISSUE TITLE
[BUG] <2.5.1-upgrade-2.6.0-pg.sql>

### ISSUE THREAD

**Issue by zongmingzhi** [apache/shenyu#5010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1920" alt="image" src="https://github.com/apache/shenyu/assets/95121549/fa9507d2-cd85-4057-bd85-7c19fff6ff47">
Upgrade script issues

### Expected Behavior

ALTER TABLE selector ADD COLUMN match_restful int2 NOT NULL;
COMMENT ON COLUMN "public"."rule"."match_restful" IS 'whether to match restful(0 cache, 1 not cache)';
COMMIT;

Modify to

ALTER TABLE selector ADD COLUMN match_restful int2 NOT NULL;
COMMENT ON COLUMN "public"."selector"."match_restful" IS 'whether to match restful(0 cache, 1 not cache)';
COMMIT;

### Environment

```markdown
ShenYu version(s):2.6.0
```

**Comment by yu199195** [comment]
can you fix it？

**Comment by zongmingzhi** [comment]
> can you fix it？

of course
