### ISSUE TITLE
[Question] Conditions `post`, how to get request param?

### ISSUE THREAD

**Issue by gMan1990** [apache/shenyu#5025]
### Question

> post
从请求上下文（org.apache.shenyu.plugin.api.context.ShenyuContext）中获取条件参数，需要通过反射获取字段的值，不推荐使用此方式。

```text
curl 'http://httpbin.org/get?a=1'

{
  "args": {
    "a": "1"
  }, 
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7", 
    "Accept-Encoding": "gzip, deflate", 
    "Accept-Language": "zh-CN,zh;q=0.9", 
    "Host": "httpbin.org", 
    "Upgrade-Insecure-Requests": "1", 
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36", 
    "X-Amzn-Trace-Id": "Root=1-64dca2e8-4080efb03ec4c9b66f58af98"
  }, 
  "origin": "122.231.230.59", 
  "url": "http://httpbin.org/get?a=1"
}
```

how to get param `a`'s value?

**Comment by moremind** [comment]
pls refer to document: https://shenyu.apache.org/docs/user-guide/admin-usage/selector-and-rule/

**Comment by gMan1990** [comment]
@moremind modifyresponse ，如何根据入参来自定义返回？

**Comment by moremind** [comment]
> @moremind modifyresponse ，如何根据入参来自定义返回？

just modify response key => value

**Comment by gMan1990** [comment]
@moremind 只指，当 request arg, `a=1`  response `{"b":1}`   request arg, `a=2`  response `{"c": "你好"}`

**Comment by moremind** [comment]
pls refer to: https://shenyu.apache.org/zh/docs/plugin-center/http-process/modifyresponse-plugin
