### ISSUE TITLE
[Question] ShenYu Gateway Management System user experience and some suggestions

### ISSUE THREAD

**Issue by bert82503** [apache/shenyu#5030]
### Question: ShenYu Gateway Management System user experience and some suggestions
> As a new user of ShenYu

my suggestions
1. Selector name unique conflict, it is recommended that selector use "name + pluginId" as the unique index, and the selector name of different plugins can use the application name as its name, which is convenient for querying (complete name match) and maintains consistency. The flow control uses a layered design of "plugin + selector + rule", and the impact on the framework is not clear.
2. Rule name unique conflict, it is recommended that rule use "name + selectorId" as the unique index, for the same reason as above.
3. Fast copy function of configuration that reduce duplicate configurations, but replication is easy to miss (there are gains and losses).
4. Synchronization function between multiple environments, avoid repeated configuration and replication, and avoid repeated stepping on pitfalls. (similar to NacosSync, a functional tool for data synchronization in multiple register centers)
5. the unified page of search preview of configuration, the search conditions include application name, service interface, method name, flat display of all relevant configurations, reduce the threshold of problem analysis, business R&D can participate in the solution, liberate the productivity of business R&D, and reduce our participation.
6. Provide a simplified unified configuration page, configuration items are scattered and numerous, the cost of switching pages back and forth is high, many configurations are the same, we can provide a simplified unified configuration page based on some guidelines, reduce the threshold of use, and improve ease of use. (pluginList, basicConfig: plugin, selector, rule, metadata and authentication)

ShenYu gateway management system is designed based on its domain data model perspective, and the scalability flexibility of configuration is very good.
Starting from the actual business usage scenario, users will not use all domain configurations, but generally only one or two configurations of each subdomain, and each company can simplify the configuration based on these rules.
Of course, I hope that the community will do it uniformly.

Everyone is welcome to discuss together. 👏🏻👏🏻👏🏻

### ShenYu(神禹)网关管控系统使用体验和一些建议
> 作为一名ShenYu(神禹)的新用户

个人建议
1. 选择器名称唯一冲突，建议选择器使用"名称+插件身份"作为唯一索引，不同插件的选择器名称都可以使用应用名称作为其名称，便于查询(名称完整匹配)，保持一致性。流量控制使用"插件+选择器+规则"分层设计，不清楚对框架的影响面
2. 规则名称唯一冲突，建议规则使用"名称+选择器身份"作为唯一索引，理由同上
3. 配置快速复制功能，减少重复配置，但复制容易漏改（有得有失）
4. 多环境之间的同步功能，避免重复配置和复制，避免重复踩坑（类似NacosSync，多注册中心数据同步的功能工具）
5. 配置的搜索预览统一页面，搜索条件有应用名称、服务接口、方法名称，平面化展示所有相关配置，降低问题分析门槛，业务研发可以参与解决，解放业务研发的生产力，减少我们的参与
6. 提供简化的统一配置页面，配置项分散且较多，页面来回切换成本高，很多配置是相同的，可以基于一些准则提供简化的统一配置页面，降低使用门槛，提高易用性（插件、基本配置：插件、选择器、规则、元数据和认证数据）

ShenYu(神禹)网关管理系统，是基于其领域数据模型视角设计的，配置的扩展性灵活性是很好。
从业务实际使用场景出发，用户不会使用所有领域配置，一般只会使用每个子域的一两项配置，每个公司可以基于这些规则简化配置。
当然希望社区统一做

欢迎大家一起探讨👏🏻👏🏻👏🏻

**Comment by yu199195** [comment]
1. pls used english （ or Chinese-English）
3. Your suggestion is great, can you get involved to optimize it?

**Comment by bert82503** [comment]
> 1. pls used english （ or Chinese-English）
> 2. Your suggestion is great, can you get involved to optimize it?

ok, I use Chinese-English to describe my suggestions.

**Comment by bert82503** [comment]
### 简化版的统一配置页面
入参: 应用名称、服务接口、方法名称、方法描述、插件列表(多项)、RpcType、用户身份、手机号码
InputParam: AppName, Interface, MethodName, MethodDescribe(PathDescribe), PluginList(MultiOption), RpcType, UserId, TelPhone


# 以dubbo和oauth2插件配置为例

## PluginList 插件列表
### rpc proxy -> dubbo

#### 1.SelectorList 选择器列表
入参：应用名称
Name: shenyu-demo-rpc
Conditions: /shenyu-demo/**

<img width="1261" alt="1 rpc proxy-Selector" src="https://github.com/apache/shenyu/assets/1811851/c5c31350-08d9-44d0-8bd2-1e973145b8d3">

#### 2.RulesList 规则集合列表
入参：服务接口、方法名称
Name: com.shenyu.service.DemoService.hello
Conditions: /shenyu-demo/hello

<img width="1265" alt="2 rpc proxy-Rules" src="https://github.com/apache/shenyu/assets/1811851/9be76b97-78b6-45ce-ba3c-5c37127e2b62">


## BasicConfig 基本配置
### 1.MetaData 元数据
入参：应用名称、方法名称、服务接口、RpcType、方法功能描述
AppName: shenyu-demo
MethodName: hello
PathDescribe: 神禹示例
Path: /shenyu-demo/hello，{应用名称}/{方法名称}
Interface: com.shenyu.service.DemoService
RpcType: dubbo

<img width="987" alt="3 MetaData" src="https://github.com/apache/shenyu/assets/1811851/7b7af89b-4416-4e72-892b-533b3157c12d">


## 1.Authentication 认证
### 1.Certification 证书
入参：应用名称、用户身份、手机号码
出参：AppId、AppPassword（用于换取令牌）
AppName: shenyu-demo
UserId: 1234567890
TelPhone: 13566666666
ResourcePath: 通过应用名称自动拉取所有资源路径列表

<img width="1036" alt="4 Certification" src="https://github.com/apache/shenyu/assets/1811851/24a47e60-8648-4a65-b2fb-6a5ef00595de">

### 3.oauth2 认证插件
> authentication 认证

#### 1.SelectorList 选择器列表
> 与其它插件的选择器列表配置完全一样，名称需要唯一性（unique index conflict, please enter again）
> 建议选择器使用"名称+插件身份"作为唯一索引，不同插件的选择器名称都可以使用应用名称作为其名称，便于查询，保持一致性。我觉得这样设计更合理

入参：应用名称
Name: shenyu-demo-oauth2
Conditions: /shenyu-demo/**

<img width="1261" alt="5 auth-Selector" src="https://github.com/apache/shenyu/assets/1811851/ea01099d-73e7-4b55-8191-43bb5c9e0b80">

#### 2.RulesList 规则集合列表
> 与其它插件的规则列表配置完全一样，名称需要唯一性（unique index conflict, please enter again）
> 建议规则使用"名称+选择器身份"作为唯一索引

入参：服务接口、方法名称
Name: shenyu-demo
Conditions: /shenyu-demo/**

<img width="1258" alt="6 auth-Rules" src="https://github.com/apache/shenyu/assets/1811851/f590b16f-d1a4-4538-a46f-8e026323fcf3">

**Comment by bert82503** [comment]
> 1. pls used english （ or Chinese-English）
> 2. Your suggestion is great, can you get involved to optimize it?

done for action 1

**Comment by bert82503** [comment]
> 1. pls used english （ or Chinese-English）
> 2. Your suggestion is great, can you get involved to optimize it?

thx! I would be happy to participate.  @yu199195 

For v2.6.0, the following suggestions have been completed. 👍 
1. Selector name unique conflict
2. Rule name unique conflict
3. Fast copy function of configuration that includes Selector, Rule.

<img width="1504" alt="Copy-Selector" src="https://github.com/apache/shenyu/assets/1811851/8a2e72d7-4b22-40d5-b782-b590dbdcf17d">

<img width="1496" alt="Copy-Rule" src="https://github.com/apache/shenyu/assets/1811851/e32801a2-bf61-433a-8118-6b39e0cd9dae">

**Comment by bert82503** [comment]
神禹配置数据全量同步机制：ZooKeeper注册中心同步时，“先全量删除某类所有配置数据，再全量创建某类所有配置数据”。

这个同步机制的最大缺陷时，在流量高峰期操作同步时，经常出现数据丢失情况，规则未找到(`Rule not found!`)，接口响应状态码是`-102`。

这是我们踩过的坑，血淋淋的教训。
它存在重大风险与安全隐患，谁还敢在生产环境使用。
