### ISSUE TITLE
[BUG] Netty Epoll unavailable due to dependencies conflict

### ISSUE THREAD

**Issue by TeslaCN** [apache/shenyu#5033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`
java.lang.IllegalStateException: Multiple resources found for 'META-INF/native/libnetty_transport_native_epoll_x86_64.so' with different content: [jar:file:/home/wuweijie/.m2/repository/io/netty/netty-transport-native-epoll/4.1.94.Final/netty-transport-native-epoll-4.1.94.Final-linux-x86_64.jar!/META-INF/native/libnetty_transport_native_epoll_x86_64.so, jar:file:/home/wuweijie/.m2/repository/com/baidu/cloud/spring-cloud-baidu-thirdparty-commons/2022.2.0/spring-cloud-baidu-thirdparty-commons-2022.2.0.jar!/META-INF/native/libnetty_transport_native_epoll_x86_64.so]
`

![image](https://github.com/apache/shenyu/assets/20503072/3593722d-d1b7-4deb-ac49-7107005b051b)

### Expected Behavior

Using Netty Epoll in shenyu-bootstrap

### Environment

```markdown
ShenYu version(s):
```
efd5f41e384536c5fbf90d4976632ad9b6b92c8c

**Comment by TeslaCN** [comment]
It seems that the starlight brpc protocol was not released independently.
<https://mvnrepository.com/search?q=com.baidu.cloud>

So we might solve this issue by:
1. Using maven-shade-plugin exclude files in jar
2. Or replacing starlight with other implementation.

**Comment by moremind** [comment]
yes，brpc plugin will refactor in the next version with baiducloud

**Comment by TeslaCN** [comment]
> yes，brpc plugin will refactor in the next version with baiducloud

Is there any plan or detail about the refactoring?

**Comment by moremind** [comment]
> > yes，brpc plugin will refactor in the next version with baiducloud
> 
> Is there any plan or detail about the refactoring?

waiting for startlignt remove the common module
