### ISSUE TITLE
[Question] Problems encountered when using the tcp service

### ISSUE THREAD

**Issue by Miku-kk** [apache/shenyu#5034]
### Question

When I tried to use the Tcp service, I found that my admin page was different from the tutorial on the documentation
1.BasicConfig->Plugin->tcp I have no resource button
![image](https://github.com/apache/shenyu/assets/62196387/95942804-d0d6-497e-a4c7-127da92a4853)
2.PluginList->Proxy I have no Tcp menu item
3.SystemManage->Resource I do not have tcp options
The sql file does not contain the data of resource and permission corresponding to tcp

**Comment by yu199195** [comment]
can you used shenyu 2.6.0？ and exec init sql？

**Comment by Miku-kk** [comment]
I'm using version 2.6.0 and executing init sql

**Comment by yu199195** [comment]
what database used？

**Comment by Miku-kk** [comment]
Using mysql, execute the db/init/mysql/schema.sql file with navicat

**Comment by moremind** [comment]
pls refer to: https://shenyu.apache.org/zh/docs/plugin-center/discovery/discovery-mode

**Comment by moremind** [comment]
are you login as admin?

**Comment by Miku-kk** [comment]
Sorry, I re-executed the sql file, the data seems to have, may be overwritten after adding data

**Comment by Miku-kk** [comment]
I logged in as admin

**Comment by MaoxianCk** [comment]
I seem to have found a problem, it seems to be mysql's SQL Init script lacks a configuration item.
![image](https://github.com/apache/shenyu/assets/45224101/b29ec520-a912-4bda-a337-f49b42f6201c)

**Comment by Miku-kk** [comment]
Thank you,It is true that there is no data in the database, but that is not the cause of my problem.
It's a problem with my computer's cache. I used version 2.5.1 at first, but after switching to version 2.6.0, I didn't clear the browser cache, so the page showed version 2.5.1.
After the cache is cleared, there is a resource button on the page, which can be used directly after clicking on the resource.
In version 2.6.0, the resource configuration for tcp is generated by using the resource button in the plugin
