### ISSUE TITLE
[Question] Problems starting shenyu-examples-http test project after initial login for password change

### ISSUE THREAD

**Issue by YOLOooooos** [apache/shenyu#5035]
### Question

When I followed the tutorial on the official website, I started the shenyu-examples-http test project after the initial login and password change, and found that the HttpClientRegisterRepository class was reporting an error Register admin url :http://localhost:9095 is fail, will retry. cause:accessToken is null. After troubleshooting, I found that in the org.apache.shenyu.register.client.http.HttpClientRegisterRepository#doRegister method, the following is executed HttpClientRegisterRepository#doRegister method in this.accessToken.get(server), the password carried by this.accessToken is still the initial password, not my modified password. Is there a mistake in my perception or operation here, or is it a bug? 

![image](https://github.com/apache/shenyu/assets/101615036/19815e40-31b6-4af5-9e14-b0c139cccf43)

**Comment by yu199195** [comment]
if you changed password，can you config it in  shenyu-examples-http？

**Comment by YOLOooooos** [comment]
I don‘t know this step,I will try it again,thanks~

**Comment by YOLOooooos** [comment]
> I don‘t know this step,I will try it again,thanks~
