### ISSUE TITLE
[Task] upgrade dubbo to 3.2.x

### ISSUE THREAD

**Issue by loongs-zhang** [apache/shenyu#5068]
### Description

upgrade dubbo to 3.2.x(just in shenyu-bootstrap, don't upgrade client) and add integration tests for dubbo-plugin

### Task List

1. - [x] upgrade dubbo to 3.2.x for shenyu-plugin-apache-dubbo;
2. - [ ] add apache-dubbo provider 2.7.0 integration test;
3. - [ ] add apache-dubbo provider 3.1.x integration test;

**Comment by damonxue** [comment]
pls assign 2 me.

**Comment by Ceilzcx** [comment]
pls assign 1 to me.

**Comment by yeshadoo** [comment]
pls assign 3 to me.

**Comment by yeshadoo** [comment]
@dragon-zhang Sorry i will confirm task 3 again,i found dubbo plugin integration test was done in module [shenyu-integrated-test-apache-dubbo] based on dubbo version 3.1.1,and what's the extra work?

**Comment by dragon-zhang** [comment]
> @dragon-zhang Sorry i will confirm task 3 again,i found dubbo plugin integration test was done in module [shenyu-integrated-test-apache-dubbo] based on dubbo version 3.1.1,and what's the extra work?

There is a small amount of additional work. Previously, a partner unified the Dubbo version of the entire shenyu project. After Task 1 was completed, the unified version was modified, and at this time, the `shenyu-integrated-test-apache-dubbo` needs to be separately disassembled into `shenyu-integrated-test-apache-dubbo-latest` & `shenyu-integrated-test-apache-dubbo-3.1.x` & `shenyu-integrated-test-apache-dubbo-2.7.x` modules.

**Comment by yeshadoo** [comment]
thanks，i get it～

dragon-zhang ***@***.***>于2023年9月12日 周二09:51写道：

**Comment by yeshadoo** [comment]
@dragon-zhang hi, my pr #5147 is blocked at k8s example check, the same as #5147, could you please help check it~

**Comment by yeshadoo** [comment]
@dragon-zhang hi, please help me review #5147 , i'm not sure whether need to modify dubbo-service-example version.

**Comment by dragon-zhang** [comment]
> @dragon-zhang hi, please help me review #5147 , i'm not sure whether need to modify dubbo-service-example version.

`dubbo-service-example` is needed to like `shenyu-examples-apache-dubbo-service-3.1.x`.
