### ISSUE TITLE
[Task] Refactor brpc plugin

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#5071]
### Description

Refactor shenyu brpc plugin to remove startlight common package

### Task List

1. remove the startlight common module
2. dependency startlight-api and startlight-brpc

**Comment by misaya295** [comment]
assigned to me pls

**Comment by WindSearcher** [comment]
It seems that dependency startlight api and startlight brpc are not found in the code

**Comment by misaya295** [comment]
> It seems that dependency startlight api and startlight brpc are not found in the code

brpc has been removed in the latest version of shenyu.
