### ISSUE TITLE
关于加了@ShenyuSpringMvcClient，在插件列表里Divide无法自动生成数据。

### ISSUE THREAD

**Issue by effectZz** [apache/shenyu#5080]
### Question

按照文档中Http服务接入方式，创建新项目，引入依赖，在controller加@ShenyuSpringMvcClient，但是启动项目的时候，没有反应。但是如果用了官方的shenyu-examples-http的demo启动的话，确可以在admin面板上发现自动添加的选择器。
于是这个时候我copy了shenyu-examples-http的代码与application.yml文件到我新建的项目中，但是这个时候新的项目还是不能自动添加。目前可以判断出唯一的区别就是pom.xml里的内容了，可是在官方文档中，并没有介绍到底需要怎么修改，只是说明添加shenyu-spring-boot-starter-client-springmvc依赖。

**Comment by moremind** [comment]
pls use english, pls refer to shenyu-example
