### ISSUE TITLE
[Task] Discovery affect into `divide` and `websocket`

### ISSUE THREAD

**Issue by ywj1352** [apache/shenyu#5095]
### Description

Discovery mode  affect into  `divide` and `websocket`. make  divde and websocket can't use Discovery-Mode to sync upstream list

### Task List

1. Discovery impl in Other registry-server   @eurecalulu 
    a. Discovery impl nacos 
    b. Discovery impl etcd
    c. Discovery impl eureka
2. Discovery affect into  `divide`  @xcsnx 
3. Discovery affect into `websocket` @ywj1352 
4. Discovery Front-end  @eurecalulu 

pr list
https://github.com/apache/shenyu/pull/5153   shenyu-client sync discovery-config  merged
https://github.com/apache/shenyu/pull/5170.   Register instance into discovery
https://github.com/apache/shenyu/pull/5174.   admin use discovery config init discovery-service 
https://github.com/apache/shenyu/pull/5176   admin adapter discovery local mode
https://github.com/apache/shenyu/pull/5193.   add nacos, etcd, eureka discovery service
https://github.com/apache/shenyu/pull/5261.  admin binding selector(divide Or ws Or Gprc 's selector) and discovery

**Comment by eurecalulu** [comment]
Nice! Please assign task1 and 4 to me~ thx

**Comment by xcsnx** [comment]
Please assign the divide plugin to me
