### ISSUE TITLE
[BUG] <CROSSSLOT Keys in request don't hash to the same slot> <ERR value is not an integer or out of range>

### ISSUE THREAD

**Issue by CytFree** [apache/shenyu#5100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1、in redis cluster mode，Concurrent、SlidingWindow Algorithm，
The second key does not contain '{id}'. The Redis Lua expression is executed by pre calculating the slot of the keys. Although this key is not manipulated, if these two keys are not in the same slot, an error will still be reported：CROSSSLOT Keys in request don't hash to the same slot
2、SlidingWindow lua expire time may be a decimal，an error: ERR value is not an integer or out of range
see token bucket and leaky bucket used math.ceil、math.floor function handle
![image](https://github.com/apache/shenyu/assets/34176334/cd2b3569-a6a2-42f8-aca4-23c3c813a7e0)
![image](https://github.com/apache/shenyu/assets/34176334/aa35d8f0-daa4-437c-9fc2-da2b3b7204c7)

### Environment

```markdown
ShenYu version(s): 2.6.0
```

**Comment by yu199195** [comment]
can you fix it？
