### ISSUE TITLE
[Question] nacos里的配置，与 shenyu-admin界面上看到的不一致

### ISSUE THREAD

**Issue by gMan1990** [apache/shenyu#5111]
### Question

nacos, data-id: `shenyu.register.service.dubbo.***`
`,\"rpcExt\":\"{\\\"loadbalance\\\":\\\"random\\\",\\\"retries\\\":2,\\\"timeout\\\":3000,\\\"sent\\\":false,\\\"cluster\\\":\\\"failover\\\"}\"`

shenyu-admin 界面端 `/plug/Proxy/dubbo`
Handler: `{"retries":0,"loadbalance":"random","timeout":3000}`

所以这2个地方，是同一个东西吗？rpcExt和Handler？生效的是哪个？我改如何去自定义配置？

**Comment by moremind** [comment]
pls use English

**Comment by moremind** [comment]
plugin handle
