### ISSUE TITLE
[Task] Dubbo plugin loadbalancer selector

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#5127]
### Description

![image](https://github.com/apache/shenyu/assets/20184263/49907d46-79de-4ae3-bf3c-753273102643)
change the loadbalance field of dubbo plugin to select load balance, use dropdown instead of input.

### Task List

1.use dropdown instead of input.
2.change mysql, h2, oracle, pg, og database sql and upgrade sql.

**Comment by misaya295** [comment]
assigned to me pls
