### ISSUE TITLE
[Task] WebSocket plugin add proxy ping

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#5142]
### Description

websocket plugin add proxy ping configuration

### Task List

1. add proxy ping configuration field.
2. add the filed to `WebsocketClientSpec` in `org.apache.shenyu.springboot.plugin.websocket.WebSocketPluginConfiguration`

**Comment by wenlongbrother** [comment]
Do assign it to me, thanks

**Comment by wenlongbrother** [comment]
#5144

**Comment by wenlongbrother** [comment]
Hi @moremind, are you able to help review this pr when you have spare time? Thanks
