### ISSUE TITLE
[Question] How to check the synchronization status between the admin service and bootstrap?

### ISSUE THREAD

**Issue by TroubledFirework** [apache/shenyu#5143]
### Question
version: 2.6.0
I have set up some selectors and rules, but I found they did not take effect. I suspect there is a problem with synchronization, but I don't know where to start troubleshooting, and I don't have a corresponding solution.

I hope to have the following solutions:
1. View real-time synchronization status and cluster nodes in admin;
2. Actively click to retry synchronization when admin synchronization fails;
3. Have some common solutions for synchronization failures.

**Comment by moremind** [comment]
which version？

**Comment by moremind** [comment]
you can get bootstrap cache data from `localhost:9195/actuator/ruleData`

**Comment by TroubledFirework** [comment]
> which version？

I have amended the question to add the version being used.

**Comment by TroubledFirework** [comment]
> you can get bootstrap cache data from `localhost:9195/actuator/ruleData`

```
{
    "code": -107,
    "message": "divide:Can not find selector, please check your configuration!"
}
```

**Comment by moremind** [comment]
do you change the manager config in application.yml ?

**Comment by moremind** [comment]
> ### Question
> version: 2.6.0 I have set up some selectors and rules, but I found they did not take effect. I suspect there is a problem with synchronization, but I don't know where to start troubleshooting, and I don't have a corresponding solution.
> 
> I hope to have the following solutions:
> 
> 1. View real-time synchronization status and cluster nodes in admin;
> 2. Actively click to retry synchronization when admin synchronization fails;
> 3. Have some common solutions for synchronization failures.

shenyu has shown sync log in the console

**Comment by TroubledFirework** [comment]
> > ### Question
> > version: 2.6.0 I have set up some selectors and rules, but I found they did not take effect. I suspect there is a problem with synchronization, but I don't know where to start troubleshooting, and I don't have a corresponding solution.
> > I hope to have the following solutions:
> > 
> > 1. View real-time synchronization status and cluster nodes in admin;
> > 2. Actively click to retry synchronization when admin synchronization fails;
> > 3. Have some common solutions for synchronization failures.
> 
> shenyu has shown sync log in the console

Think you, this method is useful.
