### ISSUE TITLE
HELP! Many sleeping Threads

### ISSUE THREAD

**Issue by ColdFragrance** [apache/shenyu#5162]
### Question

In my project,which built via shenyu-bootstrap mode,I found many sleeping threads while stress testing.This is picture as follows
![1694764764946](https://github.com/apache/shenyu/assets/31916039/830f0f9b-07ad-4f84-85aa-aad76199129f)

and jstack below
![1694743938711](https://github.com/apache/shenyu/assets/31916039/b25fef3b-4657-440d-965b-e82b238800df)
![1694743938728](https://github.com/apache/shenyu/assets/31916039/e70969fb-da5d-414b-9c00-03518b68ab72)
![1694743938762](https://github.com/apache/shenyu/assets/31916039/76440327-5204-4d0b-a9ac-8e9fad7b9556)
Why too many sleeping threads,and will it affect my program?
HELP me pls.Thanks a lot.

**Comment by moremind** [comment]
pls confirm thread type

**Comment by moremind** [comment]
currently, reactor-http-epoll-n thread is work thread

**Comment by ColdFragrance** [comment]
we have not operated threads directly.

**Comment by moremind** [comment]
> we have not operated threads directly.

can you send the dump log to me(hefengen@apache.org)

**Comment by moremind** [comment]
> > we have not operated threads directly.
> 
> can you send the dump log to me([hefengen@apache.org](mailto:hefengen@apache.org))

in addition, pls descript your config in application.yml and used plugin information

**Comment by ColdFragrance** [comment]
Well,I have already emailed you,Thanks

**Comment by moremind** [comment]
this issue will close because of mq question.
