### ISSUE TITLE
[Question] '@JsonFormat' Why not use 'yyyy' instead of 'YYYY'

### ISSUE THREAD

**Issue by pan071** [apache/shenyu#5181]
### Question

In org.apache.shenyu.e2e.model.response.PluginDTO, the date formatting in @JsonFormat uses @JsonFormat(pattern = "YYYY-MM-dd HH:mm:ss"). Why doesn't it use the lowercase letter 'y'?

**Comment by moremind** [comment]
this module waiting for refacting.
