### ISSUE TITLE
Suggested optimization

### ISSUE THREAD

**Issue by lixianli1987** [apache/shenyu#5201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I found an optimization when using the Hystrix plugin
![9096c6b62bce0117d3920e0ea8d4b1f](https://github.com/apache/shenyu/assets/14136245/e44a24ab-e1b6-43ed-afa4-c8c79011d798)
![图片](https://github.com/apache/shenyu/assets/14136245/e95796e9-f831-4c27-a3b2-a83860b00685)

### Environment

```markdown
ShenYu version(s):
```

**Comment by moremind** [comment]
thanks for your suggestion

**Comment by crudboy** [comment]
Pls assigned to me  maybe just need  modify  shenyu-dashboard ?

**Comment by moremind** [comment]
pls add the config in shenyu
