### ISSUE TITLE
[BUG]  menu pluginList don't exist, but data exist

### ISSUE THREAD

**Issue by zzzk1** [apache/shenyu#5247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I logged in to the backend management system, the page was normal, but when I refreshed it, the problem in the picture appeared.

### Expected Behavior

I did not change the initial password.

### Environment

```markdown
ShenYu version(master):
```

### Debug logs

![屏幕截图 2023-10-23 161003](https://github.com/apache/shenyu/assets/36791902/f2a8e5cf-6678-4532-a24d-ead122b7d772)

**Comment by moremind** [comment]
this has been fixed in shenyu-dashboard, but not synchronous to shenyu

**Comment by VampireAchao** [comment]
Sorry, my bad

**Comment by VampireAchao** [comment]
https://github.com/apache/shenyu/pull/5250
