### ISSUE TITLE
[BUG] Gateway access exception and document service exception

### ISSUE THREAD

**Issue by zzzk1** [apache/shenyu#5248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### When I choose to enter the background management system, I change the password as shown in the picture below
![开屏修改密码 2023-10-23 172047](https://github.com/apache/shenyu/assets/36791902/14e471e1-845d-48f4-a507-23558ad3d06c)

### After changing the password in this step, the service will not be able to access the gateway normally
![springcloud接入2023-10-23 172518](https://github.com/apache/shenyu/assets/36791902/f2995639-650a-463c-9d66-da25c8e45643)
![http接入 2023-10-23 172546](https://github.com/apache/shenyu/assets/36791902/b3691c1c-6c22-4f5f-8c17-68890b525150)

### Steps To Reproduce

1. Login to the systemadmin 123456
2. Change initialization password
3. Enable plugin
4. Start the service built into this project **Http** **SpringCloud**
5. Service cannot be accessed

### Environment

```markdown
ShenYu version(s):master
```

### Debug logs

Http Service debug log
![http-error 2023-10-23 174306](https://github.com/apache/shenyu/assets/36791902/36b55fdf-a5f4-4637-8e66-e8007f51cf32)
SpringCloud debug log
![springcloud-error 2023-10-23 174547](https://github.com/apache/shenyu/assets/36791902/6420a882-ba5e-4d14-82e8-bc8ad965cbc7)

**Comment by moremind** [comment]
change the password of shenyu-client configuration
