### ISSUE TITLE
how to converts http protocol into the webservice protocol?

### ISSUE THREAD

**Issue by diandiankou** [apache/shenyu#5252]
### Question

How to convert http protocol to webserice protocol? Is there plugin support for this?

**Comment by moremind** [comment]
> ### Question
> How to convert http protocol to webserice protocol? Is there plugin support for this?

divide plugin

**Comment by diandiankou** [comment]
> > ### Question
> > How to convert http protocol to webserice protocol? Is there plugin support for this?
> 
> divide plugin
