### ISSUE TITLE
http无法注册

### ISSUE THREAD

**Issue by lxqaoliao** [apache/shenyu#5257]
### Question

依赖是导入的2.5.1
![image](https://github.com/apache/shenyu/assets/136814416/a025d222-a667-4bde-9912-f9ca834dd662)
配置也加上了
![image](https://github.com/apache/shenyu/assets/136814416/588923d9-3f55-47fa-b833-43b904422f06)
包括注解
![image](https://github.com/apache/shenyu/assets/136814416/692d3222-376e-46c8-95e7-12709edbed99)
这是日志提示INFO  org.apache.shenyu.admin.service.register.FallbackShenyuClientRegisterService - Add to Fallback and wait for execution, /proxy:[URIRegisterDTO{protocol='http://', appName='proxy', contextPath='/proxy', rpcType='http', host='192.168.60.49', port=8999, eventType=null}]
2023-10-26 17:03:11 [shenyu-shared_wheel_timer-3] WARN  org.apache.shenyu.common.timer.AbstractRetryTask - Failed to execute task:/proxy:divide,retried：1 ,total retries:-1,cause:doRegister Failed to execute,wait

**Comment by lxqaoliao** [comment]
会是什么原因导致呢？

**Comment by YxYL6125** [comment]
remove the shenyu.client.http.props.port: 8999  and try it again

**Comment by YxYL6125** [comment]
> remove the shenyu.client.http.props.port: 8999 and try it again

or set your own http server's port as same as the shenyu.client.http.props.port. If them are not same, the server cannot be found
