### ISSUE TITLE
wafplugin cache bug

### ISSUE THREAD

**Issue by crazyStar00** [apache/shenyu#5279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. The access to the system using the network segment 192.168.40 is blocked, as expected
2. The network segment 192.168.42 is used to access the system. The forwarding is normal and meets expectations
3. The network segment 192.168.40 is used to access the system, and the forwarding is normal

Cause of the problem:
1. When network segment 192.168.42 accesses the system and no rule is matched, an empty rule is added to the MatchDataCache.RULE_DATA_MAP cache
3. When the 192.168.40 network segment is used again, the null rule is obtained from the MatchDataCache.RULE_DATA_MAP cache, and the actual rule does not take effect

Temporary solutions:
1. Modify defaultMatchRule in AbstractShenyuPlugin to write the empty rule rule to cached code comments

![image](https://github.com/apache/shenyu/assets/18380553/2e359bd3-3805-4c23-af9c-5ff0c2103f32)

![image](https://github.com/apache/shenyu/assets/18380553/bf97a129-2308-46d5-a952-1ed93da0cfaf)

I don't understand. Why do we need to cache empty rules？

**Comment by moremind** [comment]
can you fix it?

**Comment by crazyStar00** [comment]
> can you fix it?

I'd like to, but I don't understand why an empty object is put in the cache when no data is retrieved

**Comment by crazyStar00** [comment]
> > can you fix it?
> 
> I'd like to, but I don't understand why an empty object is put in the cache when no data is retrieved

![image](https://github.com/apache/shenyu/assets/18380553/ce1868d8-f0ab-4572-a0f6-c30debd1b446)
I did this directly, I wonder if it is OK?

**Comment by crazyStar00** [comment]
> > can you fix it?
> 
> I'd like to, but I don't understand why an empty object is put in the cache when no data is retrieved

![image](https://github.com/apache/shenyu/assets/18380553/4da57b62-0866-44a0-92b8-588f0e94e982)
I did this directly, I wonder if it is OK?

**Comment by moremind** [comment]
no, empty rule data or selector data means can't match the rule or selector

**Comment by moremind** [comment]
you can close the match cache to avoid cache error.

**Comment by crazyStar00** [comment]
thanks
