### ISSUE TITLE
shenyu网关能够实现dubbo的跨集群调用吗？

### ISSUE THREAD

**Issue by wang-laoshi** [apache/shenyu#5281]
### Question

hello，请问一下

我的dubbo3服务分别部署在两个不同集群
a和b，都使用nacos作为各自的注册中心

我想a集群里的dubbo-consumer端访问b集群的dubbo-provider服务
用什么样的方式比较好》

**Comment by moremind** [comment]
shenyu can't support this. you can change the code to support this feature.
