### ISSUE TITLE
[Question] Some plugin not found in the PluginList

### ISSUE THREAD

**Issue by YxYL6125** [apache/shenyu#5293]
### Question

I could not find some plugin menu. Then I checked the `schema.sql`, there was no data about them either in the `resource/permission` table. Maybe them missing? :thinking:

![image-20231112150323670](https://raw.githubusercontent.com/YxYL6125/imgBad/main/img/image-20231112150323670.png)

**Comment by moremind** [comment]
these plugin menus can generate by resource button

**Comment by YxYL6125** [comment]
> these plugin menus can generate by resource button

That means they're not required at initialization time, right?

**Comment by moremind** [comment]
yeap

**Comment by YxYL6125** [comment]
got it
