### ISSUE TITLE
[BUG] divide plugin config lost when network has problem

### ISSUE THREAD

**Issue by NightliarX** [apache/shenyu#5311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when the network experiences jitter,the ip:port configuration in divide plugin will be lost

### Expected Behavior

do not change divide plugin's configuration even the network is unreachable，because network jitter will recover soon

### Steps To Reproduce

1.click pluginList-proxy-divide-add,to add a new divide config
2,in this config,Ip:port set a Ip address that unreachable
3.save this config
4.click modify button to see Ip:port  config 

### Environment

```markdown
ShenYu version(s):2.5.1
```

**Comment by NightliarX** [comment]
<img width="681" alt="Screenshot 2023-11-21 185629" src="https://github.com/apache/shenyu/assets/31990865/f57fb410-1f8d-49db-a73d-a96a642634a8">
<img width="679" alt="Screenshot 2023-11-21 185815" src="https://github.com/apache/shenyu/assets/31990865/3c4eddc4-f985-44a7-85e5-b11aacbe99c7"><br/>
after reading the code ,I found that the code in org.apache.shenyu.admin.service.impl.UpstreamCheckService may have concurrency problem.<br/>
UPSTREAM_MAP.get(selectorId) in first picture may execute before updateHandler in method submit was executed.it leads to 
an error result after updated the database(updateHandler's update result in first picture will cover the update result in second picture)

**Comment by NightliarX** [comment]
and I dont understand why shenyu-admin would update database after the network changes,I dont think it is a good design.shenyu-admin can do this operation and publish event in memory,but update datebase make me very confusing and it occures problem<br/>
I losed almost all ip:port in divide configs after the jitte and it cannot recover automaticaly  because of this bug,that's a very serious problem.

**Comment by moremind** [comment]
yeah, shenyu will refactor the design, and keep the database, now, you can config `shenyu.register.props.checked=false`

**Comment by loongs-zhang** [comment]
@NightliarX Hi, I recommend increasing the value of `shenyu.register.props.zombieCheckTimes`.

As for concurrency problem, see https://github.com/apache/shenyu/pull/5587 , the PR also fix other bug.
