### ISSUE TITLE
[Question] 请问启动服务后，登录admin的时候遇到这个问题，该如何解决？

### ISSUE THREAD

**Issue by UncleCatWu** [apache/shenyu#5327]
### Question

<img width="1475" alt="image" src="https://github.com/apache/shenyu/assets/18675524/1a468914-3656-4c28-95d1-645ec49c2e60">

**Comment by UncleCatWu** [comment]
用的是最新的2.6.1-SNAPSHOT版本

**Comment by moremind** [comment]
the latest commit?

**Comment by UncleCatWu** [comment]
> /platform?

请问这个平台是指什么呢？我用docker是能正常登陆进去admin的，但是把源代码下下来启动admin平台能打开，但是输入用户名、密码、验证码之后点击login就报错了
