### ISSUE TITLE
[BUG] 自定义插件在关闭后，再开启不会加载

### ISSUE THREAD

**Issue by 1017206511** [apache/shenyu#5332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

问题复现方式：
自定义插件，配置相关的选择器、规则。可以正常命中。在关闭插件重新开启后，插件的选择器、规则均无法生效。
相关配置：
配置同步方式使用的nacos，插件加载方式是ext-lib扫描
PS:
在经过其他同步方式的尝试，以及upload jar的方式加载后，发现依然不行。
定位相关代码：
org.apache.shenyu.web.loader.ShenyuLoaderService#loadUploadedJarPlugins
建议对jar进行md5判断，以此来识别jar版本是否一致，避免不标准jar无法正常获取pom.properties导致无法加载

### Environment

```markdown
ShenYu version(s):
```

**Comment by 1017206511** [comment]
版本为2.6.0

**Comment by YxYL6125** [comment]
Maybe this is similar at https://github.com/apache/shenyu/issues/5292
