### ISSUE TITLE
Backfilling issue with selector rule configuration parameters

### ISSUE THREAD

**Issue by MRgenial** [apache/shenyu#5343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In shenyu admin, under the plugin list menu, after configuring the rules for the selector, the editing page does not fill in parameters

### Environment

```markdown
ShenYu version(s):2.6.0
```

### Anything else?

<img width="1687" alt="image" src="https://github.com/apache/shenyu/assets/49973336/d1c80fda-5022-42ee-bb76-a124157f5667">

**Comment by moremind** [comment]
thanks for your feedback, we will fix it

**Comment by eurecalulu** [comment]
Thank you for your feedback! I think I know where the bug is and I will fix it today.

**Comment by moremind** [comment]
it has fixed in https://github.com/apache/shenyu-dashboard/pull/385
