### ISSUE TITLE
[BUG] Alarm management added data form verification error

### ISSUE THREAD

**Issue by MRgenial** [apache/shenyu#5354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the system management alarm management, there is an abnormal verification of the newly added alarm switch. I understand that the switch should have a default value.

### Expected Behavior

I expect the switch default value verification to be modified.

### Environment

```markdown
ShenYu version(s):2.6.0
```

### Debug logs

<img width="1239" alt="image" src="https://github.com/apache/shenyu/assets/49973336/e1511aa6-872b-49f6-86a1-a6343bb4ae59">

**Comment by moremind** [comment]
hi, @tomsun28 ,pls check the error

**Comment by tomsun28** [comment]
hi @MRgenial, thanks for feedback, we will set the default value here.
