### ISSUE TITLE
Cluster current limiting

### ISSUE THREAD

**Issue by lzhenglin** [apache/shenyu#5376]
### Question

Dear gods, please ask whether the latest version of Sentinel in shenyu supports cluster limiting。

**Comment by lzhenglin** [comment]
Whether the correct usage is **RateLimiter** for cluster current limiting, **Hystrix** for fuse degradation,
Or does anyone have any suggestions for a more mature way to use it

**Comment by moremind** [comment]
> The correct usage is RateLimiter for cluster limiting and Hystrix for fuse degradation, right? Or does anyone have any suggestions for a more mature way to use it

yeap
