### ISSUE TITLE
[Question] Missing dependencies for 2.6.0-SNAPSHOT in shenyu-examples.

### ISSUE THREAD

**Issue by bestK** [apache/shenyu#5377]
### Question

https://repository.apache.org/content/groups/snapshots/org/apache/shenyu/shenyu-spring-boot-starter-client-springmvc/

![image](https://github.com/apache/shenyu/assets/14979305/6adf3a61-f29e-455d-a1cc-c72ceb67a651)

**Comment by bestK** [comment]
Fixed

![image](https://github.com/apache/shenyu/assets/14979305/53ee9c7b-d816-4b02-9632-1dd8b7ee4104)

**Comment by moremind** [comment]
sorry, not exist version 2.4.4
