### ISSUE TITLE
[Task] SpringCloud Dynamic route based on discovery

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#5466]
### Description

Now, ShenYu SpringCloud Plugin just supports shenyu-client-springcloud to upload the application data, ShenYu can support dynamic routes by discovery server including eureka, nacos, etcd, and so on.

### Task List

1. Add dynamic routes by the discovery in shenyu-springcloud-plugin
2. refactor the dashboard of springcloud plugin to support dynamic routes
3. update the documentation of springcloud plugin

**Comment by xcsnx** [comment]
I am willing to try

**Comment by sususama** [comment]
Hi, I'm not find this issue in apache website to GSOC. It's a GSOC projiect?

**Comment by moremind** [comment]
remove from gsoc
