### ISSUE TITLE
[Task] Plugin lifecycle and Chain lifecycle

### ISSUE THREAD

**Issue by Aias00** [apache/shenyu#5475]
### Description

Plugin lifecycle and lifecycle of Chain of Responsibility

**Comment by Aias00** [comment]
@moremind more description,  pls

**Comment by yu199195** [comment]
@Aias00  good idea～

**Comment by Aias00** [comment]
> @Aias00 good idea～

is actually @moremind 's idea :smiley:

**Comment by moremind** [comment]
you should add before and after methods in chain execute in `ShenyuWebHandler`
