### ISSUE TITLE
[BUG] timeLocal 比 responseHeader中的date字段的值还要晚

### ISSUE THREAD

**Issue by chinagoldline** [apache/shenyu#5489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/apache/shenyu/assets/6066006/1ba6c064-66dc-454d-aeb3-ad9b4898576d)
![image](https://github.com/apache/shenyu/assets/6066006/73f650c3-4e47-4581-ac5d-f6048d4cae7f)

### Steps To Reproduce

将shenyu网关的logs输出到elasticsearch，在kibana中看到上述现象。
但是通过源码看，理论上来讲应该不会存在该现象才对呀。

### Environment

```markdown
ShenYu version(s):2.6.1
```

**Comment by impactCn** [comment]
kibana 
Stack Management -> Advanced Settings ->Timezone for data formatting.

For es, the storage time is utc+0, which can be changed through settings. As for responseHeader, this is the time zone set by java. I don't think this is a bug. I will close this issue.
