### ISSUE TITLE
[Task] check sql 

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#5512]
### Description

now, shenyu supports MySQL, PostgreSQL, h2, and so on, but I found SQL may error.

**Comment by Aias00** [comment]
assign me , pls

**Comment by WindSearcher** [comment]
> SQL

can you be more specific? What are the SQL errors

**Comment by WindSearcher** [comment]
> ### Description
> now, shenyu supports MySQL, PostgreSQL, h2, and so on, but I found SQL may error.
> 
> ### Task List
> _No response_

can you be more specific? What are the SQL errors
