### ISSUE TITLE
[Task] <Upgrade sofa rpc version support>

### ISSUE THREAD

**Issue by tomsun28** [apache/shenyu#5517]
### Description

Now sofa rpc depends on the lower version of alibaba dubbo. We need to upgrade the sofa rpc version. The higher version depends on apache dubbo3.

please make sure this can running with java17 jdk

### Task List

1. Upgrade sofa rpc version support
2. Upgrad and test pass in `shenyu-examples/shenyu-examples-sofa`
3. Upgrad and test pass in `shenyu-integrated-test/shenyu-integrated-test-sofa`  `shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-sofa`

**Comment by Aias00** [comment]
assign me , pls , i wanna help

**Comment by tomsun28** [comment]
> assign me , pls , i wanna help

welcome, has assigned to you.

**Comment by Aias00** [comment]
> > assign me , pls , i wanna help
> 
> welcome, has assigned to you.

thx 😊
