### ISSUE TITLE
[Question] Get url parameters set to header

### ISSUE THREAD

**Issue by xdxTao** [apache/shenyu#5543]
### Question

Hello, I have a problem now. The front end cannot set the token into the header.

I want to use a plug-in to first get the token value from the url, and then set the token into the header.

I have tried for a long time without success. Can such a function be implemented?

**Comment by Aias00** [comment]
u mean admin or bootstrap?

**Comment by xdxTao** [comment]
> u mean admin or bootstrap?

Thank you for your reply.

I am using admin.

**Comment by Aias00** [comment]
> The front end cannot set the token into the header.

 u can get token value from header, why must url

**Comment by xdxTao** [comment]
> > The front end cannot set the token into the header.
> 
> u can get token value from header, why must url

Yes, in most scenarios we get the token from the header.

But we now have an app download function. The front end says that the universal preview component cannot set the header.

Now we think of an ending solution that is not to perform jwt verification on this method and manually verify the token in the method, but this is not very elegant.

**Comment by Aias00** [comment]
> > > The front end cannot set the token into the header.
> > 
> > 
> > u can get token value from header, why must url
> 
> Yes, in most scenarios we get the token from the header.
> 
> But we now have an app download function. The front end says that the universal preview component cannot set the header.
> 
> Now we think of an ending solution that is not to perform jwt verification on this method and manually verify the token in the method, but this is not very elegant.

maybe u can set header from backend, before the universal preview component ?

**Comment by xdxTao** [comment]
> > > > The front end cannot set the token into the header.
> > > 
> > > 
> > > u can get token value from header, why must url
> > 
> > 
> > Yes, in most scenarios we get the token from the header.
> > But we now have an app download function. The front end says that the universal preview component cannot set the header.
> > Now we think of an ending solution that is not to perform jwt verification on this method and manually verify the token in the method, but this is not very elegant.
> 
> maybe u can set header from backend, before the universal preview component ?

Sorry, I didn't understand what you meant

Our download is that the backend provides an HTTP interface, and the frontend only needs to pass an id as an input parameter.

In this situation? How can I let the backend set the request header?

**Comment by Aias00** [comment]
> > > > > The front end cannot set the token into the header.
> > > > 
> > > > 
> > > > u can get token value from header, why must url
> > > 
> > > 
> > > Yes, in most scenarios we get the token from the header.
> > > But we now have an app download function. The front end says that the universal preview component cannot set the header.
> > > Now we think of an ending solution that is not to perform jwt verification on this method and manually verify the token in the method, but this is not very elegant.
> > 
> > 
> > maybe u can set header from backend, before the universal preview component ?
> 
> Sorry, I didn't understand what you meant
> 
> Our download is that the backend provides an HTTP interface, and the frontend only needs to pass an id as an input parameter.
> 
> In this situation? How can I let the backend set the request header?

okay, i have submit a pr to suppurt this feature

**Comment by xdxTao** [comment]
> > > > > > The front end cannot set the token into the header.
> > > > > 
> > > > > 
> > > > > u can get token value from header, why must url
> > > > 
> > > > 
> > > > Yes, in most scenarios we get the token from the header.
> > > > But we now have an app download function. The front end says that the universal preview component cannot set the header.
> > > > Now we think of an ending solution that is not to perform jwt verification on this method and manually verify the token in the method, but this is not very elegant.
> > > 
> > > 
> > > maybe u can set header from backend, before the universal preview component ?
> > 
> > 
> > Sorry, I didn't understand what you meant
> > Our download is that the backend provides an HTTP interface, and the frontend only needs to pass an id as an input parameter.
> > In this situation? How can I let the backend set the request header?
> 
> okay, i have submit a pr to suppurt this feature

thank

**Comment by Aias00** [comment]
> > > > > > > The front end cannot set the token into the header.
> > > > > > 
> > > > > > 
> > > > > > u can get token value from header, why must url
> > > > > 
> > > > > 
> > > > > Yes, in most scenarios we get the token from the header.
> > > > > But we now have an app download function. The front end says that the universal preview component cannot set the header.
> > > > > Now we think of an ending solution that is not to perform jwt verification on this method and manually verify the token in the method, but this is not very elegant.
> > > > 
> > > > 
> > > > maybe u can set header from backend, before the universal preview component ?
> > > 
> > > 
> > > Sorry, I didn't understand what you meant
> > > Our download is that the backend provides an HTTP interface, and the frontend only needs to pass an id as an input parameter.
> > > In this situation? How can I let the backend set the request header?
> > 
> > 
> > okay, i have submit a pr to suppurt this feature
> 
> thank

no need , may be next time u can also do some contribute to this project

**Comment by xdxTao** [comment]
> > > > > > > > The front end cannot set the token into the header.
> > > > > > > 
> > > > > > > 
> > > > > > > u can get token value from header, why must url
> > > > > > 
> > > > > > 
> > > > > > Yes, in most scenarios we get the token from the header.
> > > > > > But we now have an app download function. The front end says that the universal preview component cannot set the header.
> > > > > > Now we think of an ending solution that is not to perform jwt verification on this method and manually verify the token in the method, but this is not very elegant.
> > > > > 
> > > > > 
> > > > > maybe u can set header from backend, before the universal preview component ?
> > > > 
> > > > 
> > > > Sorry, I didn't understand what you meant
> > > > Our download is that the backend provides an HTTP interface, and the frontend only needs to pass an id as an input parameter.
> > > > In this situation? How can I let the backend set the request header?
> > > 
> > > 
> > > okay, i have submit a pr to suppurt this feature
> > 
> > 
> > thank
> 
> no need , may be next time u can also do some contribute to this project

OK, if there's a chance, I'd be happy to.

**Comment by Aias00** [comment]
the change has been merged, could this issue be closed? https://github.com/apache/shenyu/pull/5547
