### ISSUE TITLE
[使用的时候在API处发现2个问题] <title>

### ISSUE THREAD

**Issue by lupeidong** [apache/shenyu#5551]
### Question

1、自己添加api，无法添加请求头参数与请求参数，如下图
![1714014088218](https://github.com/apache/shenyu/assets/17776065/dfe7ac56-1d9a-4012-b7bc-6e99676bb7fa)
2、接口调试中，增加了请求头进行保存时，会按字符拆。。。
![1714014167022](https://github.com/apache/shenyu/assets/17776065/1327519c-d8ae-4296-ae9f-7998eaeca5e8)
期待您的回复

**Comment by Aias00** [comment]
English pls
