### ISSUE TITLE
[Database key] Please ask whether the database table field is using oracle keywords

### ISSUE THREAD

**Issue by x519286925** [apache/shenyu#5569]
### Question

<img width="743" alt="image" src="https://github.com/apache/shenyu/assets/32434890/008bd2da-8db5-443b-a77f-2d0c68f2fc66">

**Comment by Aias00** [comment]
yes, some code may use the database keyword sometime.  if u got anytime , u can submit some refactor code to avoid this situation

**Comment by x519286925** [comment]
I only found it in the process of using it, and now I just manually added an s to the level to avoid it
