### ISSUE TITLE
[Task] Upgrade SpringBoot to 3.x

### ISSUE THREAD

**Issue by Aias00** [apache/shenyu#5582]
### Description

Upgrade SpringBoot to 3.x
Now, SpringBoot has been upgraded to 3.x version, and the SpringBoot 2.x version will not be supported in the near future.

### Task List

1. upgrade shenyu pom.xml springboot version to 3.x
2. upgrade shenyu-example pom.xml springboot version to 3.x
3. upgrade shenyu-e2e pom.xml springboot version to 3.x

**Comment by yu199195** [comment]
good idea
