### ISSUE TITLE
[Question] ShenYu Admin OceanBase Support

### ISSUE THREAD

**Issue by VampireAchao** [apache/shenyu#5615]
### Question

I would like to inquire about adding support for OceanBase in ShenYu Admin. OceanBase is a distributed, high-performance relational database developed by Ant Group. The Community Edition of OceanBase is open-source and widely used for its scalability, high availability, and compatibility with MySQL and Oracle databases. Integrating OceanBase with ShenYu would allow users to leverage its strengths in handling large-scale, distributed systems.

I am interested in contributing to this feature and would appreciate any guidance or suggestions on how to proceed with the integration. I'm eager to collaborate with the community to make this support a reality.

**Comment by dudiao** [comment]
Have you considered using mybatis-plus to decouple different databases?

**Comment by VampireAchao** [comment]
> Have you considered using mybatis-plus to decouple different databases?

As a member of the MyBatis-Plus development team, I agree with the suggestion. However, it’s important to note that MyBatis-Plus supports multiple databases primarily through the use of its API, such as the `QueryWrapper`. To truly decouple from specific databases, it would require converting the existing SQL written in XML to be executed through code. This approach is not straightforward and would have a significant impact. Additionally, there are other concerns, such as MyBatis-Plus not handling database keywords automatically.

The main purpose of introducing MyBatis-Plus is to reduce the amount of basic CRUD development, avoiding the repetitive task of writing MyBatis XML code, rather than quickly addressing the need to adapt to multiple databases. I look forward to further discussions within the community on whether to introduce MyBatis-Plus and the scope and extent of its integration.

**Comment by dudiao** [comment]
Use mybatis-plus to implement the logic in xml again, Many of them are CRUD.

For database keywords, you should try to avoid them in the table design. If it exists now, consider adding a prefix before the keyword field. When the version is upgraded, perform data migration.

However, this does require a significant amount of work and is worth it in the long run.

**Comment by VampireAchao** [comment]
> Use mybatis-plus to implement the logic in xml again, Many of them are CRUD.
> 
> 
> 
> For database keywords, you should try to avoid them in the table design. If it exists now, consider adding a prefix before the keyword field. When the version is upgraded, perform data migration.
> 
> 
> 
> However, this does require a significant amount of work and is worth it in the long run.

Sure, perhaps we could create a new issue to gather more feedback on integrating Mantis-Plus.
