### ISSUE TITLE
[BUG] class AdminConstants has  word spelling error

### ISSUE THREAD

**Issue by IceFoxs** [apache/shenyu#5636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1079" alt="image" src="https://github.com/user-attachments/assets/40402f7f-b4bc-4b50-9a09-7225c3f438f3">

### Expected Behavior

PLUGIN_ABSTRACR_PATH   modify to PLUGIN_ABSTRACT_PATH

### Environment

```markdown
ShenYu version(s):2.7.0-SNAPSHOT
```

**Comment by Aias00** [comment]
thx, can u submit a pr to fix it ?

**Comment by IceFoxs** [comment]
> thx, can u submit a pr to fix it ?

OK，I fix it!
