### ISSUE TITLE
[BUG] class AlertTransfer has word spelling error

### ISSUE THREAD

**Issue by IceFoxs** [apache/shenyu#5639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="873" alt="image" src="https://github.com/user-attachments/assets/54a86411-98d3-464a-8cf8-38bb6272e88c">

### Expected Behavior

Reciver modify to Receiver

### Environment

```markdown
ShenYu version(s): 2.7.0-SNAPSHOT
```

**Comment by Aias00** [comment]
hi, can u submit a pr to fix this . by the way , can u fix some typo errors in a pr together ?

**Comment by Aias00** [comment]
pls correct typo in one pr , thx

**Comment by Aias00** [comment]
![Uploading image.png…]()

**Comment by IceFoxs** [comment]
> <img alt="image" width="610" src="https://private-user-images.githubusercontent.com/25810623/363093248-7774baa7-165c-43d5-8f7b-bc23a19ee2f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyOTI0NzksIm5iZiI6MTcyNTI5MjE3OSwicGF0aCI6Ii8yNTgxMDYyMy8zNjMwOTMyNDgtNzc3NGJhYTctMTY1Yy00M2Q1LThmN2ItYmMyM2ExOWVlMmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDE1NDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMjFhYjQ1OGY2YzE0YjJiY2E3YjMwZWYwMmI2MmM5NmYxYmRlZWRmNTY1NTFiMmVkMGJhOTcwZDU2ZTllZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JwcnRLx_yxeMSyDVL1DNZJV5n_TWrvYOkdJt3JLp4Ck">
OK,I view code and find more than,than together fix it
