### ISSUE TITLE
[BUG] <Nested Interface>

### ISSUE THREAD

**Issue by ColdFragrance** [apache/shenyu#5675]
### Question

Hi everyone,
I configure 2 interfaces by shenyu-bootstrap, called /a and /b.They are work while single,but /b does not work until timeout while invoked by /a.After timeout, /b works again.Who can help me?

**Comment by ColdFragrance** [comment]
My shenyu.netty is default configurations.

**Comment by ColdFragrance** [comment]
OH,this problem only occurs when concurrency.

**Comment by Aias00** [comment]
Is your API functioning normally when accessed directly without going through Shenyu?

**Comment by ColdFragrance** [comment]
yes，it works
