### ISSUE TITLE
[Question] How to query the execution order between different plugin?

### ISSUE THREAD

**Issue by ochive** [apache/shenyu#5680]
### version
2.6.1
### Question

example like divide and rewrite, who run first?
 when the prefix have been strip(rewrite), the divide plugin uri still must have the prefix to match.

- Rewrite Config:
![image](https://github.com/user-attachments/assets/8a6ce2fa-404e-48d2-a720-13146b583cc3)
![image](https://github.com/user-attachments/assets/69551bd9-e3d6-40d7-bc07-56ad7252dacd)

- Divide Config:
![image](https://github.com/user-attachments/assets/ec5d81ab-0e47-4be1-ba43-42a33a1c1bde)
![image](https://github.com/user-attachments/assets/7f0dfd82-252f-4a44-af83-bd5c078f7cb9)

**Comment by moremind** [comment]
you can see it in plugin management page
