### ISSUE TITLE
[BUG] Can not edit Divide Discovery config

### ISSUE THREAD

**Issue by ochive** [apache/shenyu#5681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i try use divide to route to service behind nacos.
I meet some problem.When i create a divide ,the discovery can edit. but when edit the divde, i no longer can edit the discovery config.

- create divide:
![image](https://github.com/user-attachments/assets/8c390cd1-92cc-4926-b427-34a18fa1700f)

- edit divide:
![image](https://github.com/user-attachments/assets/7dc326b4-312b-41a9-af15-07c0f2f0d16d)

### Environment

```markdown
ShenYu version(s):2.6.1
```

**Comment by ywj1352** [comment]
At design time, a gateway is corresponding to a registry of the same type that can only be registered once. When you sign up for nacos. Do not need to modify nacos link configuration. And if you need to change the listener PATH. Theoretically a new divide listener. You need to re-create
