### ISSUE TITLE
[Question] Suggest add a function in Selector

### ISSUE THREAD

**Issue by ochive** [apache/shenyu#5683]
### Question

I suggest add a button in Selector config page, Rule config page, or other config page.When click the button, system will copy the json config of the page to clipboard. The button can place in the action bar of list view, too.
This is benefit for communicate and ask questions in the community. The snapshot is good, but not precise enough for convenience.

![image](https://github.com/user-attachments/assets/0352e78c-45eb-46aa-a2aa-8c6965fa8171)

![image](https://github.com/user-attachments/assets/93eaa725-e39f-4447-983d-2b62ea2c9709)

**Comment by moremind** [comment]
thanks for you suggestion
