### ISSUE TITLE
[BUG] enable namespace plugin failed

### ISSUE THREAD

**Issue by eye-gu** [apache/shenyu#5717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1474" alt="image" src="https://github.com/user-attachments/assets/3b58b2c1-de5b-4045-af81-0f4b8f0c2e29">

<img width="967" alt="image" src="https://github.com/user-attachments/assets/5b8be200-7056-4d97-b637-a1874347e715">

When enable the plugin, bootstrap reports an error. The reason for checking the logs is that the plugin name is null. Discovered that the namespace_plugin_rel table does not have a plugin name, nor is it associated with the plugin table to retrieve it

### Environment

```markdown
ShenYu version(s):
```

**Comment by xcsnx** [comment]
Thank you, there is indeed an error here, I will correct it
