### ISSUE TITLE
[Question] Support for gray release in divide-plugin.

### ISSUE THREAD

**Issue by barney-cs** [apache/shenyu#5751]
### Question

Hello Shenyu team,

In our production project, we encountered a limitation with the Shenyu Gateway due to the Divide plugin’s lack of support for gray release (canary release). I noticed that the Divide plugin documentation has a placeholder for gray release, so I attempted a simple modification to enable gray release in our project.

**Proposed Modifications:**

1. **Added a Field in `DiscoveryUpstreamData`**: I introduced a new field to `DiscoveryUpstreamData` to store a gray release identifier, which is set via environment variables when using `shenyu-spring-boot-starter-client-springmvc`. This identifier is passed through the Discovery module's process to the Upstream, allowing the Divide plugin to differentiate gray release nodes.

2. **Configuration Update for Traffic Identification in `shenyu-bootstrap`**: I also added a configuration property in the `shenyu-bootstrap` project to recognize marked (colored) traffic. Alternatively, this configuration could be included within the Divide plugin’s config settings.

These modifications have worked successfully in our project, and we can now utilize gray release with Shenyu. I am interested in contributing this code if there are plans to support gray release in the official Divide plugin. Could you share if there are any upcoming plans for this feature or guidance on integrating this functionality?

Thank you for considering this enhancement!

**Comment by moremind** [comment]
LGTM

**Comment by moremind** [comment]
@yunlongn  please focus on the issue
