### ISSUE TITLE
[Question] 网关的jwt选择器的压测问题

### ISSUE THREAD

**Issue by sunpengqi** [apache/shenyu#5758]
### Question

事情经过：
      部署了2套网关，网关01上启用mock，网关02上使用divide代理转发这个mock的这个请求至网关01上
     机器为8C/16G
     单独压测网关01的mock请求，吞吐量在5万，压测网关02后吞吐量在2万5，在网关02上开启JWT，压测网关02的mock接口吞吐量只有2000多,修改org.apache.shenyu.plugin.jwt.JwtPlugin类下的checkAuthorization方法，使用cache缓存jwt的验证结果后压测的吞吐量在1万4左右

咨询问题：JWT开启后，JWT的校验过程对吞吐量的影响怎么如此大，除了缓存jwt的验证结果，是否还有其它方式提高压测性能。

**Comment by Aias00** [comment]
can change netty properties to optimize the test result, link: https://shenyu.apache.org/docs/developer/shenyu-optimize/
