### ISSUE TITLE
[BUG] plugin page data not correct

### ISSUE THREAD

**Issue by eye-gu** [apache/shenyu#5785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/user-attachments/assets/f1bf5829-1f81-4588-a68f-347a97baf9f0)

The status and configuration of the plugin page should be `namespace_plugin_rel`, but currently it is in the `plugin` table

### Environment

```markdown
ShenYu version(s):
```

**Comment by Aias00** [comment]
link: https://github.com/apache/shenyu/pull/5790
