### ISSUE TITLE
[Question] <title>下载文件重复添加transfer-encoding响应头，报502错误

### ISSUE THREAD

**Issue by DongPoJuShi** [apache/shenyu#5788]
### Question

我有一个文件下载接口，文件无法提前获取大小， 使用curl -i 查看响应头信息，会添加Transfer-Encoding头
 curl -i http://127.0.0.1:8081/sso/file/download 
HTTP/1.1 200 OK
transfer-encoding: chunked
Set-Cookie: JSESSIONID=586720F3737BB4AC4151B8CF05F01BEF; Path=/; HttpOnly
Content-Type: application/octet-stream
Transfer-Encoding: chunked
Date: Fri, 15 Nov 2024 05:53:43 GMT

访问经过网关的接口，会再添加transfer-encoding头
url -i http://127.0.0.1:8080/sso/file/download
HTTP/1.1 200 OK
transfer-encoding: chunked
Set-Cookie: JSESSIONID=3286922940F3613FF9F17EFB5F3E117C; Path=/; HttpOnly
Content-Type: application/octet-stream
Transfer-Encoding: chunked
Date: Fri, 15 Nov 2024 05:55:43 GMT

调用接口http://127.0.0.1/sso/file/download，nginx报502错误
2024/11/15 05:44:57 [error] 20#20: *1 upstream sent duplicate header line: "Transfer-Encoding: chunked", previous value: "transfer-encoding: chunked" while reading response header from upstream
请问是我哪里设置的有问题吗，该如何处理？

网关设置如下：
![image](https://github.com/user-attachments/assets/ade37a82-bffa-4383-a695-526f7f03ea77)
![image](https://github.com/user-attachments/assets/73bd496d-c01a-4257-928f-0f7555b8682c)

nginx版本为1.27.2 设置如下：
location / {
      proxy_pass http://127.0.0.1:8080;
      proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Upgrade $http_upgrade;
}

**Comment by DongPoJuShi** [comment]
我用的shenyu 2.5.1版本，报错
handle error: [84979ebf-2] Resolved [ShenyuException: response modify failure. java.lang.String can not be converted to JSON] for HTTP GET /sso/verifyCode/test

org.apache.shenyu.common.exception.ShenyuException: response modify failure. java.lang.String can not be converted to JSON
        at org.apache.shenyu.plugin.modify.response.ModifyResponsePlugin$ModifyResponseDecorator.modifyBody(ModifyResponsePlugin.java:163) ~[shenyu-plugin-modify-response-2.5.1.jar!/:2.5.1]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        *__checkpoint ⇢ org.apache.shenyu.web.configuration.ErrorHandlerConfiguration$1 [DefaultWebFilterChain]
        *__checkpoint ⇢ cn.dev33.satoken.reactor.filter.SaReactorFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.apache.shenyu.web.filter.LocalDispatcherFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP GET "/sso/verifyCode/test" [ExceptionHandlingWebHandler]
配置如下：
![image](https://github.com/user-attachments/assets/df089dbf-64dc-495b-874e-bd6626a8dc60)
![image](https://github.com/user-attachments/assets/89800e0b-c857-4a28-b2c3-ae4462554404)
看代码的话是将响应转json报错了，下载文件接口返回的二进制流，是有什么设置还是需要升级shenyu版本？感谢您回答
![image](https://github.com/user-attachments/assets/7691ec80-6584-4f1f-ae32-4a909889f76f)

**Comment by moremind** [comment]
not remove header  key, you should upgrade to 2.6.1 or change your code like this pr: https://github.com/apache/shenyu/pull/5190
