### ISSUE TITLE
[BUG] apache-shenyu-2.6.1-admin[mappers/rule-sqlmap.xml]java.sql.SQLSyntaxErrorException: ORA-00911: 无效字符

### ISSUE THREAD

**Issue by weblayout** [apache/shenyu#5820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://mvnrepository.com/artifact/org.apache.shenyu/shenyu-admin/2.6.1：mappers.rule-sqlmap.xml：
<select id="getPluginNameBySelectorId" resultType="java.lang.String">
        select p.name
        from plugin p
        inner join selector s on p.id = s.plugin_id
        where s.id = #{selectorId}
        limit 1;
    </select>

### Expected Behavior

https://github.com/apache/shenyu/blob/master/shenyu-admin/src/main/resources/mappers/rule-sqlmap.xml：
<select id="getPluginNameBySelectorId" resultType="java.lang.String">
        select p.name
        from plugin p
        inner join selector s on p.id = s.plugin_id
        where s.id = #{selectorId}
        limit 1
    </select>

https://github.com/apache/shenyu/blob/master/shenyu-admin/src/main/java/org/apache/shenyu/admin/mybatis/oracle/OracleSQLPrepareInterceptor.java：
        // replace limit 1
        if (replaceSql.contains("select")) {
            if (replaceSql.contains("where")) {
                replaceSql = replaceSql.replace("limit 1", "and rownum = 1");
            } else {
                replaceSql = replaceSql.replace("limit 1", "where rownum = 1");
            }
        }

### Environment

```markdown
ShenYu version(s):2.6.1
```

**Comment by yu199195** [comment]
can you fix it？

**Comment by weblayout** [comment]
As a note for version 2.6.1, it makes it easier for other users of oracle Database to query known issues. Since it seems to have been fixed on the master branch, it should be normal on the next release tag.
