### ISSUE TITLE
[BUG] shenyu-admin can't enable or edit plugin

### ISSUE THREAD

**Issue by franciszhang** [apache/shenyu#5821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

shen-admin plugin can't operate 

<img width="1398" alt="image" src="https://github.com/user-attachments/assets/0ecd6593-24ea-4bf5-b8f5-c3e4460e05ce">

### Environment

```markdown
ShenYu version(s):tag v2.7.1
```

**Comment by yu199195** [comment]
pls provider pull reuqest

**Comment by franciszhang** [comment]
> pls provider pull reuqest

https://github.com/apache/shenyu/pull/5822
