### ISSUE TITLE
shenyu-admin最新的代码构建成docker镜像运行后无法页面无法正常加载到接口数据

### ISSUE THREAD

**Issue by me-snowyowl** [apache/shenyu#5831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1324" alt="image" src="https://github.com/user-attachments/assets/f23abb27-f31d-4a4b-b3f1-fc5bdadac4a3">
shenyu-admin最新的代码构建成docker镜像运行后，出现了该问题，静态资源可以加载，但是接口的请求使用的IP是容器内的IP

### Steps To Reproduce

1. git clone https://github.com/apache/shenyu.git
2. mvn clean package -Dmaven.javadoc.skip=true -Dmaven.test.skip=true
3. 构建   shenyu-dist/shenyu-admin-dist/docker/Dockerfile
4. docker run -d -p 9095:9095 --name shenyu-admin shenyu-admin:master
5. 访问 IP:9095

### Environment

```markdown
ShenYu version(s):2.7.0-SNAPSHOT
```

**Comment by Aias00** [comment]
u can set system property "shenyu.httpPath"

**Comment by Aias00** [comment]
or u can set docker env "docker_host_ip"

**Comment by Aias00** [comment]
link: https://github.com/apache/shenyu/pull/5833

**Comment by me-snowyowl** [comment]
docker 运行设置环境参数docker_host_ip是可以解决，但是在k8s里，端口需要改变, 我设置了shenyu.httpPath没有生效
<img width="660" alt="image" src="https://github.com/user-attachments/assets/5879d713-4d57-4655-9eb9-eab2bf5c18d8">

**Comment by Aias00** [comment]
> docker 运行设置环境参数docker_host_ip是可以解决，但是在k8s里，端口需要改变, 我设置了shenyu.httpPath没有生效 <img alt="image" width="660" src="https://private-user-images.githubusercontent.com/9654222/392215659-5879d713-4d57-4655-9eb9-eab2bf5c18d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODQ0NDksIm5iZiI6MTczMzI4NDE0OSwicGF0aCI6Ii85NjU0MjIyLzM5MjIxNTY1OS01ODc5ZDcxMy00ZDU3LTQ2NTUtOWViOS1lYWIyYmY1YzE4ZDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDRUMDM0OTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDE3NmI5ZmRjYmE3OThiNDU0NTZmODAxYTQ1NjNlNGM3Zjc1OWJkNTQ1MDNiZTVlNjc5OWI3ODM1YmU2YWY5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.slHU9noq7widJ_fSOTt_wilF4RresER8JB8MWMMRlwI">

hi, the pr https://github.com/apache/shenyu/pull/5833 can fix this

**Comment by me-snowyowl** [comment]
问题已经解决了，非常感谢！
