### ISSUE TITLE
[BUG] springCloud ruleData path setting didn't used

### ISSUE THREAD

**Issue by frank8g2g3** [apache/shenyu#5840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

springCloud ruleData path setting invalid
<img width="1355" alt="image" src="https://github.com/user-attachments/assets/94482641-968b-4a3d-af10-2b707883e623">

<img width="1220" alt="image" src="https://github.com/user-attachments/assets/72744540-5259-4e78-920c-da01374a6fb0">

in the org.apache.shenyu.plugin.springcloud.SpringCloudPlugin#doExecute line 88 (URI.create method)，it's used shenyuContext.getRealUrl() ,the realUrl is from contextPathPlugin。ruleHandle.path didn't used

### Environment

```markdown
ShenYu version(s):2.7.1
```

**Comment by yu199195** [comment]
yes， springCloud plugin maybe removed.
