### ISSUE TITLE
[BUG] <The nacos data proxy.selector and discovery.divide for divide selector delete failed when the divide selector be deleted>

### ISSUE THREAD

**Issue by Wweiei** [apache/shenyu#5844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In divide plugin, the selector's selector config、proxy_selector and discovery config will be sync to nacos, when use nacos as data sync center. When delete the selector, the relevant information for the selector should be delete at the same time. But currently, only the selector config has been removed, the proxy_selector and discovery config have not been deleted.
1、add one selector as follows, the selector id is 1866733538682441728.
![image](https://github.com/user-attachments/assets/f9b32256-a37f-425e-b659-f4d7b0af4a4d)
![image](https://github.com/user-attachments/assets/0154afa5-b823-44de-835a-fc70fab1bc3c)
2、nacos data.
![image](https://github.com/user-attachments/assets/3b0138a7-4aa0-4d0c-bbdf-55a9ee7d9caa)
3、delete selector, the proxy.selector config and discovery.divide config still exists.
![image](https://github.com/user-attachments/assets/b43281d1-fac8-4d41-b870-64f5b2688c45)

### Expected Behavior

The divide selector's proxy.selector and discovery config should be deleted when the selector is deleted.

### Steps To Reproduce

1. check out to master branch and pull the lastest code.
2. use nacos as data sync center.
3. add one divide selector.
4. delete the selector.

### Environment

```markdown
ShenYu version(s): branch master latest
```

### Anything else?

1. The proxy.selector is deleted failed is due to the ProxySelectorDTO missing the id value and pluginName set the wrong value when unbindDiscovery .
2. When deleting the selector, there is no method to delete the discovery configuration.

**Comment by yu199195** [comment]
good job～
